### ISSUE TITLE
Call to undefined method Proengsoft\JsValidation\JsValidator::make()

### ISSUE THREAD

**Issue by vishalbhide** [proengsoft/laravel-jsvalidation#10]
I do not know how to resolve this, so I am opening a github ticket.

I am unable to use the JsValidator, as I get this error - 'Call to undefined method Proengsoft\JsValidation\JsValidator::make()'

Code snippets
~~~
//Imported the correct class
use Proengsoft\JsValidation\JsValidator;

//Called the correct method
$rules = [
 'owner_name' => 'required',
 'owner_pan' => 'required',
 'owner_email' => 'required|email',
 'owner_mobile' => 'required',
 'owner_std_code' => 'required',
 'owner_landline' => 'required',
 ];

$validator = JsValidator::make($rules);

//Still the below exception gets thrown on Runtime.
Call to undefined method Proengsoft\JsValidation\JsValidator::make()
~~~

**Comment by drjoju** [comment]
Hi,

Have you included in the config/app.php the service provider and the Facade?

See this page.
https://github.com/proengsoft/laravel-jsvalidation/wiki/Installation

After add both, remove 

use Proengsoft\JsValidation\JsValidator;

and try again.

Best regards

**Comment by vishalbhide** [comment]
Hi,

Things are working fine now. All my initial installation steps were fine.

Instead of using this line
~~~
use Proengsoft\JsValidation\JsValidator;
~~~
I used the below line in my controller

~~~
use JsValidator;
~~~
Things are working fine after the above change. If possible, could you please update the documentation in PostController.php to include the above import? (In this page -
https://github.com/proengsoft/laravel-jsvalidation/wiki/Controller-Validation-Example )

Thanks for the prompt reply!

**Comment by vishalbhide** [comment]
Hi Jose and Albert,

Thank you for the prompt response! My problem is resolved. I have updated
my original issue with my solution and closed the ticket. Thanks for the
great library!

Regards,

Vishal

**Comment by vishalbhide** [comment]
Just curious - Does JsValidation support 'Complex Conditional Validation'
(as specified in
http://laravel.com/docs/4.2/validation#conditionally-adding-rules )?

I tried to add this code -
$validator = JsValidator::make($this->detailPageValidationRules);
$validator->sometimes('operatingAddress[address1]', 'required',
function($input){
            return false;//return $input->
        });

But got this error -
Call to undefined method Proengsoft\JsValidation\JsValidator::sometimes()

Regards,

Vishal

**Comment by torrentalle** [comment]
Conditional validations are not suported in current release.  This feature is planned for the next release

**Comment by vishalbhide** [comment]
Ok thanks.

**Comment by torrentalle** [comment]
New version is released to avoid problems with IDE's code completion that's causing confusion
