### ISSUE TITLE
Tabs issue

### ISSUE THREAD

**Issue by sivon12** [proengsoft/laravel-jsvalidation#100]
I noticed that, when using jQuery tabs, the validation does not fire on inactive tabs. This appears to be because of the ignore: ":hidden" in jsvalidation.js. Is there any reason why this is not set to "" so that the validator can work automatically with tabs?

**Comment by derekmd** [comment]
You'll have to create a new template to pass the `ignore` parameter into jQuery Validation Plugin's `$.validate()` function. Just copy and paste https://github.com/proengsoft/laravel-jsvalidation/blob/master/resources/views/bootstrap.php into a new file and add the `ignore` parameter to include hidden fields in tabs. Then change `view` in your project's `config/jsvalidation.php`.

I've submitted pull request #94 to allow overriding `ignore` on a per-form basis but this project is in a state of inactivity.

**Comment by sivon12** [comment]
Many thanks Derek, will do this.

**Comment by sweetswa** [comment]
i have the same proplem plz explain in detail....

**Comment by Nuranto** [comment]
It has been pulled, and it works the validation does not pass with ignore option.
However, the focus is done without switching to correct tab, so it is quite confusing for the user. How did you deal with that @derekmd  ?
For now, I think about a global message on top of tabs #353 ?
