### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by Coornifex** [proengsoft/laravel-jsvalidation#1005]
### Subject of the issue

Hello,

Can you add Laravel 11 support please.

Regards.

**Comment by bytestream** [comment]
See https://github.com/proengsoft/laravel-jsvalidation/pull/1003#issuecomment-1973952708

If it works, let me know

**Comment by Coornifex** [comment]
I tested and I can update composer with dev branch.

However, I have an error when with JsValidator::formRequest tag :

Illuminate\Session\SymfonySessionDecorator::__construct(): Argument #1 ($store) must be of type Illuminate\Contracts\Session\Session, Illuminate\Session\SymfonySessionDecorator given, called in /home/cornifex/laravel/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 578

**Comment by bytestream** [comment]
What's the full stacktrace?

**Comment by Coornifex** [comment]
https://flareapp.io/share/lm2vn0Om

**Comment by bytestream** [comment]
Please could you composer update and try https://github.com/proengsoft/laravel-jsvalidation/pull/1003/commits/5c35fb378bd86101d44ee280246704e516cd93a7 ?

**Comment by Coornifex** [comment]
It seems working fine now, thanks.

**Comment by bytestream** [comment]
@Coornifex please open another issue if you spot anything else. I won't be using Laravel 11 for quite some time.
