### ISSUE TITLE
JsValidation facade overriding Laravel's Validation facade

### ISSUE THREAD

**Issue by derekmd** [proengsoft/laravel-jsvalidation#103]
When I configure my project:

`config/app.php`
```
    'aliases' => [
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'JsValidator'   => Proengsoft\JsValidation\Facades\JsValidatorFacade::class,
    ],
```

`use Validation` will manage a `Proengsoft\JsValidation\Validator` instance rather than the expected `Illuminate/Validation/Validator`. The cause is at https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/JsValidationServiceProvider.php#L69

`vendor/proengsoft/laravel-jsvalidation/src/JsValidationServiceProvider.php` Line 69
```
        $this->app->booting(function ($app) {
            $app['validator'] = $app['jsvalidator.validator'];
        });
```

What is the justification for overwriting the 'validator' singleton facade? Why would a dev want the extra memory footprint caused by bringing your wrapper class into memory when they're validating backend form submission controllers or an API endpoint?

**Comment by derekmd** [comment]
I'm assuming it's for Ajax callbacks.

**Comment by torrentalle** [comment]
Yes, it's for AJAX validation. 
I'm rewriting this part of code to wrap Validator instance only when AJAX validation is done!
