### ISSUE TITLE
How can I use submit method in form request?

### ISSUE THREAD

**Issue by omerozturk0** [proengsoft/laravel-jsvalidation#104]
![ekran alintisi](https://cloud.githubusercontent.com/assets/10808405/11840870/e3b799e8-a401-11e5-908d-c99972e11f58.PNG)

{!! \JsValidator::formRequest('App\Http\Requests\Backend\UserRequest', '#my-form') !!}

**Comment by josenicomaia** [comment]
I guess that $this->route()->getMethods() is your guy.
