### ISSUE TITLE
Problem on client side validation

### ISSUE THREAD

**Issue by javenosa** [proengsoft/laravel-jsvalidation#11]
I do the configuration based on the example on this web.
When I submit the form I got this error on the JS console:

:boom: TypeError: a.validator.methods[d] is undefined :boom:

Version of jquery validation: 1.13.1
Version of Laravel-jsvalidation: latest

The form request rules:

    public function rules()
    {
   	    return [
		   "test1"   =>    "required|integer|min:0",
		   "test2"  =>    "required|url|min:5|max:100",
		   "test3"	=>	  "required|min:5|max:100",
		   "test4"	=>	  "required|min:5|max:100"
	   ];
    }

The view:

	<div class="container">
		{!! Form::open(['route' => 'test.store', 'method' => 'post', 'id' => 'testForm', 'class' => 'form-horizontal']) !!}
		{!! Form::hidden('test1', 0, ['id'=>'test1']) !!}
		<div class="form-group">
			{!! Form::label('test2', 'Test2') !!}
			{!! Form::text('test2', null, ['id'=>'test2', "class" => "form-control typeahead", 'placeholder'=>'Type your test2']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('test3', 'Test3') !!}
			{!! Form::text('test3', null, ['id'=>'test3', "class" => "form-control", 'placeholder'=>'Type your test3']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('test4', 'Test4') !!}
			{!! Form::text('test4', null, ['id'=>'test4', "class" => "form-control", 'placeholder'=>'Type your test4']) !!}
		</div>
		<div class="form-group">
			{!! Form::submit('OK', ["class" => "btn btn-success btn-block"]) !!}
		</div>

		{!! Form::close() !!}
	</div>
    {!! JsValidator::formRequest('App\Http\Requests\TestForm', '#testForm'); !!}
The js generated:

    jQuery(document).ready(function(){

        $("#testForm").validate({
            highlight: function (element) { // hightlight error inputs
                $(element)
                        .closest('.form-group, .checkbox').addClass('has-error'); // set error class to the control group
            },
            unhighlight: function (element) { // revert the change done by hightlight
                $(element)
                        .closest('.form-group, .checkbox').removeClass('has-error'); // set error class to the control group
            },
            errorElement: 'p', //default input error message container
            errorClass: 'help-block help-block-error', // default input error message class
            focusInvalid: false, // do not focus the last invalid input
            ignore: "",  // validate all fields including form hidden input
            errorPlacement: function(error, element) {
                if (element.attr("type") == "radio") {
                    error.insertAfter(element.parents('div').find('.radio-list'));
                }
               else if (element.attr("type") == "checkbox") {
                    error.insertAfter(element.parents('label'));
                }
                else {
                    if(element.parent('.input-group').length) {
                        error.insertAfter(element.parent());
                    } else {
                        error.insertAfter(element);
                    }
                }
            },
            success: function (label) {
                label
                        .closest('.form-group, .checkbox').removeClass('has-error'); // set success class to the control group
            },
            rules: {"test1":{"laravelRequired":[],"laravelInteger":[],"laravelMin":["0"]},"test2":{"laravelRequired":[],"laravelUrl":[],"laravelMin":["5"],"laravelMax":["100"]},"test3":{"laravelRequired":[],"laravelMin":["5"],"laravelMax":["100"]},"test4":{"laravelRequired":[],"laravelMin":["5"],"laravelMax":["100"]}} ,
            messages: {"test1":{"laravelRequired":"The test1 field is required.","laravelInteger":"The test1 must be an integer.","laravelMin":"The test1 must be at least 0."},"test2":{"laravelRequired":"The test2 field is required.","laravelUrl":"The test2 format is invalid.","laravelMin":"The test2 must be at least 5 characters.","laravelMax":"The test2 may not be greater than 100 characters."},"test3":{"laravelRequired":"The test3 field is required.","laravelMin":"The test3 must be at least 5 characters.","laravelMax":"The test3 may not be greater than 100 characters."},"test4":{"laravelRequired":"The test4 field is required.","laravelMin":"The test4 must be at least 5 characters.","laravelMax":"The test4 may not be greater than 100 characters."}}        })
    })

Do you have any idea to fix this?
Thanks.

**Comment by torrentalle** [comment]
I cannot reproduce your error. Can you post the entire HTML generated?

**Comment by javenosa** [comment]
Sorry for my delayed answer.

I think my mistake is about the lack of using of your edited jquery validation plugin. At the moment with I try this bundle I use the original version of jquery validation.

This is can be the problem, right?

**Comment by torrentalle** [comment]
The jquery validation plugin is not modified. The custom validators are joined with jQuery Validation Plugin.
You can use the original jQuery Validation Plugin if you includes the scritps located at resources/assets/js
