### ISSUE TITLE
Depends functionality 

### ISSUE THREAD

**Issue by Varun006** [proengsoft/laravel-jsvalidation#110]
Hello,

How can i implement depends validation just like in jquery-validation. 

I am building a form with shipping and billing address. 

If the checkbox is checked then it should not validate billing address form else it should validate.

How can i achieve this?

**Comment by torrentalle** [comment]
Hi,

you can use the rule [RequiredWith](https://laravel.com/docs/5.1/validation#rule-required-with)

```php
$rules = array(
            'shipping_address' => 'required',
            'billing_address' => 'required_with:billing_checkbox'
        );
```
