### ISSUE TITLE
submit button doesn't work

### ISSUE THREAD

**Issue by jvidalgz** [proengsoft/laravel-jsvalidation#12]
I follow the FormRequest Example, validation work fine, but when I press the submit button, nothing happens

please some help

**Comment by torrentalle** [comment]
Can you post the generated html?

**Comment by jvidalgz** [comment]
Here: http://pastebin.com/D6kHnM38 
Scripts in lines: 114-117

Thanks

**Comment by torrentalle** [comment]
tonight I will make som tests

**Comment by torrentalle** [comment]
I think that you are using an outdated version , this part of code is causing yourt ploblem

```javascript

  jQuery.validator.setDefaults({
            debug: true        });
 
```



Try to  run `composer update` and publish the views provided by the package

`php artisan vendor:publish --provider="Proengsoft\JsValidation" --tag="views"`

**Comment by jvidalgz** [comment]
Perfect, I'll try that!

**Comment by torrentalle** [comment]
The correct command to update is 

`php artisan vendor:publish --provider="Proengsoft\JsValidation" --tag="views" --force`

with `force` option to allow override previous view

**Comment by torrentalle** [comment]
Can you comfirm if the package is working for you with last version?
