### ISSUE TITLE
Should remote re-validation take place after every keystroke?

### ISSUE THREAD

**Issue by jonnywilliamson** [proengsoft/laravel-jsvalidation#120]
Hi,

I have my remote validation working well. I now have a query about how often any revalidation takes place and if this is intended/on purpose with the library.

The Scenario

I have a form with two fields, both use remote validation.

* When the form is loaded, both fields are blank.
* I type into field_1 a suitable word. Nothing happens until I *TAB* out of the field into the next field. This fires the validation and I get a green border which is what I want.
* I type another (incorrect) word into field_2, again nothing happens until I TAB out (or change focus) from that field. I get a red field with a warning message, this is what I want.
* I return to field_2 and delete the word and start again typing the correct word. At THIS stage every single time I release a keystroke, the form gets revalidated. I don't think I want this.

I traced down the call to this section (click to enlarge):

![image](https://cloud.githubusercontent.com/assets/2513663/12210380/6358970e-b651-11e5-9798-a1126dcbcd71.png)

I can see that by commenting out line 292, I can bypass the onkeyup event making the form revalidate.

However I don't fully understand line 291, as in why do we check to see if it is the lastElement or that the `element.name` is in `this.submitted`...

So my question is,

1) Is it intentional that AFTER an initial validation, if a field has an error, any further editing of the field will fire a re-validation after every keypress?

2) Is this customisable?

3) By committing out that line (292) am I causing myself any further issues that I am not aware of?

Thank you for your help!

**Comment by torrentalle** [comment]
Hi,
This package uses [jQuery Validation Plugin](http://jqueryvalidation.org/) to perform validations. The [javascript provided](https://github.com/proengsoft/laravel-jsvalidation/blob/master/public/js/jsvalidation.js) by this package contains the code from [jquery-validation 1.13.1](https://github.com/jzaefferer/jquery-validation/blob/1.13.1/dist/jquery.validate.js).

1) This is the default behaviour of  [jQuery Validation Plugin](http://jqueryvalidation.org/). 

2) You can disable [**onkeyup**](http://jqueryvalidation.org/validate/#onkeyup) event in jsvalidation view **resources/views/vendor/jsvalidation/bootstrap.php**. 
``` html
<script>
    jQuery(document).ready(function(){
        $("<?php echo $validator['selector']; ?>").validate({
            errorElement: 'span',
            errorClass: 'help-block error-help-block',
            onkeyup: false,


```

3) committing out line 292 could cause unexpected behaviour. Disable

**Comment by jonnywilliamson** [comment]
>2) You can disable onkeyup event in jsvalidation view resources/views/vendor/jsvalidation/bootstrap.php.


A ha! This is the exactly solution I was looking for. I would not have know to do that without your help. Thank you. It's working exactly how I would like now. Much appreciated.
