### ISSUE TITLE
Laravel 5.2: Section-Include throws error

### ISSUE THREAD

**Issue by heikobihlmaier** [proengsoft/laravel-jsvalidation#126]
Hello,

I try to use the following code:

    @section('jsvalidator')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\FontUploadRequest') !!}
    @stop

This section is in an template and include master template.
When i put this directly in master template all works correctly.

This results in the following error:

 `Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Method Proengsoft\JsValidation\Manager::__toString() must not throw an exception`

I use currently the newest version.

Can u help ?

**Comment by torrentalle** [comment]
Hi,
can you post your 'App\Http\Requests\FontUploadRequest' ?

**Comment by heikobihlmaier** [comment]
Hi,

here is it:

    <?php

    namespace App\Http\Requests;

    use App\Http\Requests\Request;

    class FontUploadRequest extends Request
    {
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'font_name' => 'required',
            'font_normal' => 'mimes:ttf',
            'font_bold' => 'mimes:ttf',
            'font_italic' => 'mimes:ttf',
            'font_bolditalic' => 'mimes:ttf'
        ];
    }

    public function attributes() {
        return [
            'font_name' => _('Schriftname'),
            'font_normal' => _('Normal'),
            'font_bold' => _('Bold'),
            'font_italic' => _('Italic'),
            'font_bolditalic' => _('Bold & Italic'),
        ];
    }
    }

Thanks.

**Comment by torrentalle** [comment]
Hi 
I can't reproduce your error. I think that your are not using latest version (**1.3.1**). 
The class [Proengsoft\JsValidation\Manager](https://github.com/proengsoft/laravel-jsvalidation/blob/v1.2.0/src/Manager.php) was removed in release 1.3.0

Check your `composer.json` file, it shlould be like this.

```
{
    "require": {
        "laravel/framework": "5.2.*",
        ...
        "proengsoft/laravel-jsvalidation": "~1.1"
    },
    ...
    "scripts": {
        "post-update-cmd": [
            ....
            "php artisan vendor:publish --provider=\"Proengsoft\\JsValidation\\JsValidationServiceProvider\" --tag=public --force"
        ],
    },
}
```
then run 
```
$ composer update
```

**Comment by torrentalle** [comment]
Hi,
I have tested your code with:
- Laravel 5.1, JsValidation master
- Laravel 5.2, JsValidation 1.3.1

In all case is working.

I took a look into [your fork](https://github.com/Pseudoagentur/laravel-jsvalidation) and it seems ok. 

This is my test views.

**template-master.blade.php**
```html
@extends('app')
@include('jsvalidator-template')

@section('content')
    <form> 
      <!-- ....... -->
    </form>
    @yield('jsvalidator')

@endsection

```
**template-jsvalidator.blade.php**

``` html
@section('jsvalidator')
<script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
{!! \JsValidator::formRequest('App\Http\Requests\FontUploadRequest') !!}
@stop
```

**Comment by heikobihlmaier** [comment]
Hello,

I make a cleanup.

Now I get the following error:

`Method Proengsoft\JsValidation\Javascript\JavascriptValidator::__toString() must not throw an exception`

In your example you have a depth of 2 views. I have more then two. Currently my views are so:

**master.blade.php**
```
 <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
 @yield('jsvalidator');
```

**configurator.blade.php**
```
@extends('master')
@include('font_upload_button');
```

**font_upload_button.blade.php**
```
<div>
HTML-CODE, no SECTION
</div>
@section('jsvalidator')
    {!! \JsValidator::formRequest('App\Http\Requests\FontUploadRequest') !!}
@stop
```

With this markup I get the error
```
Method Proengsoft\JsValidation\Javascript\JavascriptValidator::__toString() must not throw an exception 
```
This error is in file **font_upload_button.blade.php**

Can u help ?

**Comment by heikobihlmaier** [comment]
I use my fork, which is based on your current master.

I tested it to put it in master, but i get the same error.

**Comment by heikobihlmaier** [comment]
Hello,

all is okay, I have a writing mistake in config for view path.

Can u make here a better error message ? For example view not found or so ?

Thanks for help!

**Comment by torrentalle** [comment]
Hi,

If the view is rendered using `__toString()`magic method [you cannot throw an exception from within a __toString()](http://php.net/manual/en/language.oop5.magic.php#object.tostring).

A quick solution for debugging is to use [render()](https://github.com/proengsoft/laravel-jsvalidation/wiki/JsValidator-Reference#renderview-selector) method tho generate Javascript Validations. In this case the exception is thrown as usual.

```php
JsValidator::formRequest('App\Http\Requests\FontUploadRequest')->render()
```

Now I'm looking how to **render instead of throw the Exceptions** in [__toString](https://github.com/proengsoft/laravel-jsvalidation/wiki/JsValidator-Reference#__tostring) method.

**Comment by torrentalle** [comment]
This is fixed  in `dev-master` branch. Now when Exception occurs in Jascacript Rendering, is converted to Error.
