### ISSUE TITLE
Method Not Allowed using remote validation

### ISSUE THREAD

**Issue by adamtester** [proengsoft/laravel-jsvalidation#128]
Hi

When updating a model, where the form is `put` or `patch` I get

```
PATCH http://localhost:8000/clients/16/edit 405 (Method Not Allowed)
```

The form is pointing to the correct url

```html
<form method="POST" action="http://localhost:8000/clients/16" accept-charset="UTF-8" id="update-client-form" novalidate="novalidate">
<input name="_method" type="hidden" value="PATCH">
```

Do you have any idea why it's pointing to the current url instead of the url of the form?

**Comment by torrentalle** [comment]
It's strange behaviour. 
In AJAX Validation, [the request is set to the form action URL](https://github.com/proengsoft/laravel-jsvalidation/blob/v1.3.1/resources/assets/js/jsvalidation.js#L142).

Wich version are you using?

**Comment by adamtester** [comment]
Its version `v1.3.1` according to the lock file, Ill try and set up a sample site and see if it still does it I'll post it here

**Comment by adamtester** [comment]
I created a sample app but it works! I will try to make it more like my production app until it breaks to find out whats going on

http://ancient-ocean-3050.herokuapp.com/user
https://github.com/adamtester/validation-sample-laravel

**Comment by torrentalle** [comment]
Try to update the public assets

```
php artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider" --tag=public --force
```

**Comment by adamtester** [comment]
This is really confusing, I've disabled all other JS and added
```javascript
console.log('Sending ' + formMethod + ' to:');
console.log($(validator.currentForm).attr('action'));
```

and I get

```
Sending PATCH to:
http://localhost:8000/clients/15
PATCH http://localhost:8000/clients/15/edit 405 (Method Not Allowed)
```

Which doesn't make sense!

I'll keep you posted with what I find

**Comment by torrentalle** [comment]
Can you post your `public/vendor/jsvalidation/js/jsvalidation.js` file somewere?

I will take a look.

**Comment by adamtester** [comment]
https://jsfiddle.net/d139va9x/
Here you go

**Comment by adamtester** [comment]
If you send me an email I could give you access to the actual project?

**Comment by adamtester** [comment]
Well, turns out I didn't put the request on the controller, it was just set like

```php
public function update(Request $request, $id)
```

So my bad! Still strange behaviour though
