### ISSUE TITLE
Call to undefined method Proengsoft\JsValidation\JsValidator::make()

### ISSUE THREAD

**Issue by virtualstep** [proengsoft/laravel-jsvalidation#13]
Hi,

following situation:

use Proengsoft\JsValidation\JsValidator;

protected $validationRules=[
        'email'     => 'required|email',
        'password'  => 'required',
    ];

$validator = JsValidator::make($this->validationRules);
        return view('base::login.login')->with('validator', $validator);

Gives the error in issue subject.

Where is the error ?

**Comment by torrentalle** [comment]
Hi,
JsValidator is a facade. The code should be

```php
use JsValidator;

protected $validationRules=[
'email' => 'required|email',
'password' => 'required',
];

$validator = JsValidator::make($this->validationRules);
return view('base::login.login')->with('validator', $validator);
````
This is causing confusion, in the next relese I will fix it.
You also car refer to issue #10

**Comment by torrentalle** [comment]
New version is released to avoid problems with IDE's code completion that's causing confusion
