### ISSUE TITLE
HttpResponseException

### ISSUE THREAD

**Issue by bytestream** [proengsoft/laravel-jsvalidation#130]
Would it be possible to change:
https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/Remote/Validator.php#L64

To be inline with recent changes made in Laravel 5.2:

> The ValidatesRequests trait now throws an instance of Illuminate\Foundation\Validation\ValidationException instead of throwing an instance of Illuminate\Http\Exception\HttpResponseException. This is unlikely to affect your application unless you were manually catching this exception.

[Laravel - Upgrade Guide](https://laravel.com/docs/5.2/upgrade)

For the mean time I've just added it to the `$dontReport` error handler.

**Comment by kyranb** [comment]
Would love to see this as well! 

In the meantime a reference in the docs would be helpful :smile:

**Comment by bytestream** [comment]
What was the fix? All you did was add a reference to this issue in the changelog.

**Comment by torrentalle** [comment]
Sorry was a mistake in CHNAGELOG
