### ISSUE TITLE
 BadRequestHttpException Undefined  attribute with array validation

### ISSUE THREAD

**Issue by sakalauskas** [proengsoft/laravel-jsvalidation#131]
Hello,

Since some update I started experiencing problems with array remote validation.

For example I have a rule 'customer.email' => 'email|unique....'

And method in https://github.com/proengsoft/laravel-jsvalidation/blob/v1.3.1/src/Remote/Validator.php#L58 line makes the attribute name customer_email. Therefore the rule is not found in Request and I get  BadRequestHttpException Undefined 'customer_email'  attribute.

I am using the latest version v1.3.1. I tried master branch, but I think it is on development, as I am getting some other errors.

Thanks,

**Comment by torrentalle** [comment]
I take a look.

Can you create another issue with the errors of master branch? This can help me a lot....

**Comment by torrentalle** [comment]
Hi,
this issue shlould be resolved in `hotfix/issue131` branch.
Please try it, an let me know if its working to publish new release

**Comment by sakalauskas** [comment]
Hi Albert,

Thank you!  It works now, you can close and publish new release.

**Comment by torrentalle** [comment]
This is fixed in master branch
