### ISSUE TITLE
Multiple form validation on same page

### ISSUE THREAD

**Issue by Varun006** [proengsoft/laravel-jsvalidation#137]
Hello,

How can i validate multiple form on the same page? 

Also can i change the action attribute of the form?
As it by default takes the current URL and sends it as a post request, i am not able to manage multiple forms on same page.

Thank you.

**Comment by torrentalle** [comment]
You should pass jQuery Selector using [**selector** method](https://github.com/proengsoft/laravel-jsvalidation/wiki/JsValidator-Reference#selectorselector) 

##### Example

*Controller*
```php
    $validator1 = JsValidator::make(['search' => 'min:3']);
    $validator2 = JsValidator::make(['name' => 'required']);
    // ...
    return view('my-form-view', compact('validator1', 'validator2'));
```
*View*
```html
    <form id="form-search">
        <input name="search" />
    </form>
    <form id="form-post">
        <input name="name" />
    </form>
    {!! $validator1->selector('#form-search') !!}
    {!! $validator2->selector('#form-post') !!}

```

**Comment by MrCrankHank** [comment]
Is there a way to validate multiple forms using the formRequest method?

**Comment by torrentalle** [comment]
Refer to [documentation](https://github.com/proengsoft/laravel-jsvalidation/wiki/Basic-Usage#validating-multiple-forms) to get more info
