### ISSUE TITLE
Dynamically added row validation

### ISSUE THREAD

**Issue by Skintillion** [proengsoft/laravel-jsvalidation#139]
Having trouble with validation of a row of data.

```
<input name='building[0][name]'>
<input name='building[0][type]'>
<input name='building[0][date]'>

<input name='building[1][name]'>
<input name='building[1][type]'>
<input name='building[1][date]'>

<button>ADD ROW</button>
```

I couldn't find any reference on this, most of the examples I could find require that you know the qty of inputs beforehand. I suppose I could set a maximum of inputs and just add rules for them each manually, but it's not very nice looking doing it that way.

Perhaps someone has had success with this?

**Comment by Skintillion** [comment]
Well I ended up doing the following for the CustomValidation.php

Dot notation did not work in this scenario (d.1.n) it only worked when using square brackets.



```
$input = parent::all();

if ($input) {
	$somethingcount = count($input->something);
} else {
	$somethingcount= 0;
}

for ($num = $somethingcount; $num <= 7; $num++) {
	//Roof System Fields
	$rules['something[' . $num . '][name]'] = 'required';
	$rules['something[' . $num . '][type]'] = 'required|numeric|min:1|max:99999';
}

return $rules;
```

and in the validation language file (validation.php):

```
<?php
for ($i = 0; $i <= 7; $i++) {
	$customInputMessages['something[' . $i . '][name]'] = [
		'required' => 'You must put a name.',
	];
	$customInputMessages['something[' . $i . '][type]'] = [
		'required' => 'You must put a type',
	];

	$customInputAttributes['systemtypes[' . $i . '][name]'] = 'Name';
	$customInputAttributes['systemtypes[' . $i . '][type]'] = 'Type';
}

return [

	'custom' => array_merge([
		'someotherfield' => [
			'required' => 'Some custom message for some other field.',
		],
	],
		$customRoofSystemTypeMessages
	),

	'attributes' => array_merge([
		'someotherotherfield' => 'Some Field name',
	],
		$customRoofSystemTypeAttributes
	),

];

```

Perhaps there is a more elegant way of doing this but if this helps someone then great.

**Comment by torrentalle** [comment]
Validating Arrays like
```php
$validator = Validator::make($request->all(), [
    'person.*.email' => 'email|unique:users',
    'person.*.first_name' => 'required_with:person.*.last_name',
]);
```
**Is not supported yet**

**Comment by majestic84** [comment]
+1 for this enhancement request. I'm in need of something like this, I will see if I can't put something together and add a pull request.

**Comment by torrentalle** [comment]
This feature is supported in latest version

**Comment by akkhan20** [comment]
doesnt generate the rule for wildcard field at all in laravel 5.4

**Comment by magnosis** [comment]
Why is this closed?
Array validation support was added, but it does not fix the issue of dynamically adding form fields on the page. JsValidation will only validating array values that are on-page at load time. Adding new inputs dynamically won't have them validated.
