### ISSUE TITLE
Laravel "required_without" rules not working properly for me

### ISSUE THREAD

**Issue by lordalaqua** [proengsoft/laravel-jsvalidation#14]
Hello, really good work with this package, it is simple and effective.
I am only having problems with the "required_without" and "required_without_all" rules in my application.

I have a field 'email' which should be required if none of fields 'phone1', 'phone2' and 'phone3' are present (required_without_all), and field 'phone1' should be required if 'email' is not present (required_without).

When all fields are empty it works as expected, validation fails giving a message that field is required when the other is not present. The problem is when I fill in any of the fields, validation still fails (e.g. phone1 is present and email is empty, but validation fails saying "phone1 is required when email is not present"), even if all fields are filled correctly the validator will keep failing saying a field is required when the other is empty when both fields are filled.

I have tested my code without jsvalidation and the Laravel validation works as expected, only when I add JS validation I get this error.

The generated HTML for the page is here: http://pastebin.com/rapW1yva

I am still a newbie in this, so I hope this is a valid issue, if it is not, excuse me.

Regards,
Lorenzo

**Comment by torrentalle** [comment]
I'm workin in this bug. The rules `required_without` and  `required_without_all`doesn't work as expected

**Comment by torrentalle** [comment]
The bugfix will be published in the next release. 
To solve this issue now, replace this files
- [`public/vendor/jsvalidation/js/jsvalidation.js`](https://raw.githubusercontent.com/proengsoft/laravel-jsvalidation/issue-14/public/js/jsvalidation.js)
- [`public/vendor/jsvalidation/js/jsvalidation.min.js`](https://raw.githubusercontent.com/proengsoft/laravel-jsvalidation/issue-14/public/js/jsvalidation.min.js)

**Comment by lordalaqua** [comment]
Thank you very much, it worked perfectly.

**Comment by torrentalle** [comment]
This bug is fixed in `master` branch

**Comment by fatenfalfoul** [comment]
Hello I have the same problem and I can't find the files : 404: Not Found
Help please
