### ISSUE TITLE
Recaptcha2 (nocaptcha) validation

### ISSUE THREAD

**Issue by dinajpuri** [proengsoft/laravel-jsvalidation#140]
Hello,
How could I enable validate Recaptcha before submission? Once it was possible with your package, maybe around version 1.0. Now it does not ajax validate Recaptcha.

Regards

![recaptcha](https://cloud.githubusercontent.com/assets/5769361/13026505/2d23f13c-d254-11e5-8909-d6ed6788be80.JPG)

**Comment by torrentalle** [comment]
Hi,
In recent versions this package doesn't validate *hidden* fields by default, this change is causing some issues.
I'm planning to revert this change, validating all input types by default and providing a method to override this behavior.

To workaround you can use the method **[ignore](https://github.com/proengsoft/laravel-jsvalidation/wiki/JsValidator-Reference#ignoreselector)** to enable validation for hidden fields

``` php
$validator = JsValidator::formRequest('App\Http\Requests\StoreBlogPostRequest')
$validator->ignore(' ');
```

**Comment by marcelogarbin** [comment]
@dinajpuri Were you able to use it with recaptcha? You could show how you did, thanks.
