### ISSUE TITLE
Question/Issue: How to make Conditional and Custom Rules work?

### ISSUE THREAD

**Issue by martin9348** [proengsoft/laravel-jsvalidation#141]
I have tried conditional and custom rules that work server-side but that don't seem handled by this plugin/laravel-jsvalidation (client-side validation is not done). Since conditional and custom rules are supposed to be supported, I am wondering what I am doing wrong or if it's a bug/unsupported.

In the config file, disable_remote_validation = false
I am using Laravel 5.1

What I have done (Conditional Rule) with sometimes()

```
[AddRequest.php]
namespace App\Http\Requests\Post;

use App\Http\Requests\Request;

class AddRequest extends Request
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth();
    }

    /**
     * Insert sometimes rules
     *
     * @return validator
     */
    protected function getValidatorInstance()
    {
        $validator = parent::getValidatorInstance();

        $validator->sometimes('field2_en', 'required|min:2', function($input)
        {
            return ($input->language == 'en' && $input->radiobutton == '2');
        });

        //...

        return $validator;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'language'             => ['required', 'in:en,de'],
            'field1_en'             => ['required_if:language,en'],
            'field1_de'             => ['required_if:language,de'],
            'radiobutton'          => ['required', 'in:1,2'],
            'field2_en'             => [],
            'field2_de'             => []
        ];
    }
}
```

What I have done (Custom Rule) with extend

```
[AddRequest.php]
class AddRequest extends Request
{
    //...

    public function rules()
    {
        return [
            'field2_en'             => ['custom_validation_en:radiobutton,2']
            //...
        ];
    }
}
```

```
[AppServiceProvider.php]
namespace App\Providers;

use Validator;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Validator::extendImplicit('custom_validation_en', function($attribute, $value, $parameters, $validator){
            $language = array_get($validator->getData(), 'language');
            $p = count($parameters) - 1;

            if ($language == 'en' && $p >= 1)
            {
                $attribute_value = array_get($validator->getData(), $parameters[0]);
                $i = 1;

                while ($i <= $p)
                {
                    if ($attribute_value == $parameters[$i])
                    {
                        return (!empty($value));
                    }

                    ++$i;
                }
            }

            return true;
        });
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

Am I doing something wrong? Why client-side validation does not work with those? When I look into Firebug I do not see any ajax requests being done.

Thank you.

**Comment by torrentalle** [comment]
Which version are you using? Conditional rules are supported in **master** branch.

**Comment by torrentalle** [comment]
To enable conditional validations call **sometimes** method passing the attribute name and rules to be validated conditionally

``` php
$validator = JsValidator::formRequest('App\Http\Requests\Post\AddRequest');
$validator->sometimes('field2_en', 'required|min:2');
```

This is not documented yet

**Comment by franciscojun** [comment]
What about complex sometimes conditions? The implementation of sometimes() in ValidatorHandler class (https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/Javascript/ValidatorHandler.php) only takes 2 parameters, but native Laravel sometimes() accepts a 3rd parameter (closure to define complex sometimes conditions, as the example provided by martin9348).

**Comment by bytestream** [comment]
Any update on "Complex Conditional Validation" (https://www.laravel.com/docs/5.2/validation#conditionally-adding-rules)?

**Comment by torrentalle** [comment]
For [Contitionally addiding rules](https://laravel.com/docs/5.3/validation#conditionally-adding-rules) you must indicate to JsValidation object witch `attribute` and `rules` will be validated conditionally. The $callback function is not
needed because is evaluated using AJAX.

```php
$js = JsValidator::make($rules);
$js->sometimes('reason', 'required|max:500');
```
You can get more information of how to use Complex Conditional Validation in [Conditional Validation Example](https://github.com/proengsoft/laravel-jsvalidation/wiki/Conditional-Validation-Example) and [Basic Usage wiki](https://github.com/proengsoft/laravel-jsvalidation/wiki/Basic-Usage)

**Comment by Braunson** [comment]
@torrentalle Is there no way to do this from within the Form Request? It seems messy to have to define the sometimes items within each view that have them (when you define the `{!! JsValidator::formRequest('My\FormRequest') !!}`)
