### ISSUE TITLE
ability to validate laravel rule string directly?

### ISSUE THREAD

**Issue by pocketmax** [proengsoft/laravel-jsvalidation#147]
is something like this possible? Being able to use the laravel validation string directly in JS without a PHP backend? I've been reading over the code and it looks like it can be done but I can't find the right method to validate from.

```
    <script>
        $( document ).ready(function() {
            $("#commentForm").validate({
                rules: {
                    email: 'required|unique:posts|max:255'
                }
            });
        });
    </script>
```

**Comment by torrentalle** [comment]
This is not supported. You need the Lavarel backend to parse rules and parameters
