### ISSUE TITLE
validateNoJsValidation does not exist

### ISSUE THREAD

**Issue by kyranb** [proengsoft/laravel-jsvalidation#149]
Edit: upgraded to master and seems to be fixed :+1: Thanks so much for all of your work on this package! 

I'm getting a `validateNoJsValidation does not exist` error when using the following rule in a Form Request.

To make things confusing, it works fine with a PUT request, but not POST.

What could be causing this to happen?

```php

public function rules()
    {
        return [
                    'rating' => 'in:clean,explicit|no_js_validation',
        ];
    }

``` 

Stack Trace:

```

BadMethodCallException: Method [validateNoJsValidation] does not exist. in home/vagrant/Code/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:3001
Stack trace:
#0 /home/vagrant/Code/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(416): Illuminate\Validation\Validator->__call('validateNoJsVal...', Array)
#1 /home/vagrant/Code/app/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(356): Illuminate\Validation\Validator->validate('rating', 'NoJsValidation')
#2 /home/vagrant/Code/app/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(24): Illuminate\Validation\Validator->passes()
#3 /home/vagrant/Code/app/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(44): Illuminate\Foundation\Http\FormRequest->validate()
#4 

```

**Comment by rsantosmello** [comment]
I got this same error here.

How do you fixed it:

BadMethodCallException in Validator.php line 3162:
Method [validateNoJsValidation] does not exist.
in Validator.php line 3162
at Validator->__call('validateNoJsValidation', array('email', 'melo', array(), object(Validator))) in Whoops, looks like something went wrong.
