### ISSUE TITLE
AJAX submission of form

### ISSUE THREAD

**Issue by geraldarcega** [proengsoft/laravel-jsvalidation#153]
Hi! I'm trying to submit my form through ajax, and I added submitHandler to handle it, but unfortunately when I'm going to submit the form, the ajax call triggers even though the form is still invalid. I added a variable just to check if the page just got loaded, because this is the time the validation is still submitting the form even it is blank.

`var just_loaded = true;
$('#frmUnit').validate({
            submitHandler: function(form) {
                if($(form).valid() && !just_loaded) {
                    var ans = confirm('Are you sure you want to save?');
                    if (ans) {
                        units.save($(form).serialize())
                                .done(function (data) {
                                    console.log('saving:', data);
                                })
                                .error(function () {
                                    alert("Oops! There's something wrong with the system.");
                                });
                    }
                }
                just_loaded = false;
                return false;
            }
        });`

Am I missing something? or it is a bug? Thanks you in advance for the help.

**Comment by geraldarcega** [comment]
Got the fix.

**Comment by MrCrankHank** [comment]
How did you fix it? Please share...

**Comment by geraldarcega** [comment]
@MrCrankHank Sorry for the late reply, I hope you already found a solution for this, but in case you don't, here it is:

`
$('form').on('submit', function() {
    if($(this).valid()) {
        // do your ajax stuff here    
    }
    return false;
});
`
