### ISSUE TITLE
Laravel JsValidation is not working with Ajax submitted form

### ISSUE THREAD

**Issue by Mobasher-NetLinks** [proengsoft/laravel-jsvalidation#154]
When we need to submit a form with ajax, JsValidation is not working.

**Comment by littletreex** [comment]
This is probably too late, but you can run `$('#myForm').valid()` which returns a `boolean` and has the side effect of displaying all the validation errors. In other words, for ajax you would do something like:
```javascript
if ($('#myForm').valid()) {
    //do ajax submission
}
else {
    //cry in a corner
}
```

**Comment by OzanKurt** [comment]
@littletreex Doesn't it submit the form, if it's valid anyway? How do I prevent that?
