### ISSUE TITLE
Validating Multiple Select or Group of Checkboxes

### ISSUE THREAD

**Issue by web-surgeon** [proengsoft/laravel-jsvalidation#158]
Is it possible to validate against either of these scenarios? They're being handled properly by Laravel, but I can't seem to generate a notice from JS using:

`'regions'      => 'required|array'`

Normal selects and single checkboxes are ok, but if it's multi-select or group of checkboxes with the same name, I haven't had success.

**Comment by aleixfabra** [comment]
👍

**Comment by HarleyFuagras** [comment]
Same problem here. If I try to validate something like 

`'roles => 'required'`

And in the view, the name of the input is roles[], because more than one role can be selected, the error is never printed.

**Comment by EugeneG9** [comment]
You can add square brackets or dot to attribute name, however this rule doesn't work on server side:
'mult_1[]' => 'required',
'mult_2.' => 'required',

**Comment by f0rtis** [comment]
You can add square brackets or dot to attribute name, however this rule doesn't work on server side:
'mult_1[]' => 'required',
'mult_2.' => 'required',

**Comment by a-komarev** [comment]
@f0rtis nice catch!

There will be good to add square brackets after name dynamically if `array` requirement met.

**Comment by a-komarev** [comment]
But... I just realized that `required` started to work but `array` is failing then.

**Comment by torrentalle** [comment]
This is fixed in release v1.4.3
