### ISSUE TITLE
Laravel rule "required_if" not working

### ISSUE THREAD

**Issue by adriandmitroca** [proengsoft/laravel-jsvalidation#16]
JS is rendered with these rules but validation doesn't work (actual value isn't applied)

**Comment by torrentalle** [comment]
Can you post the rules that yo are trying to validate?

**Comment by adriandmitroca** [comment]
Sure thing. Example two rules:
`            'distributor_city_id' => 'required_if:type,distributor',`
`            'distributor_name_id' => 'required_if:type,distributor',`

It means that these two fields should be required only when input named `type` has `distributor` value. Unfortunately these fields are required always, no matter what `type` input value is.

**Comment by torrentalle** [comment]
I cannot reproduce this error. Can you post the rules and the output generated ?

Thank's

**Comment by torrentalle** [comment]
maybe your problem is related to issue #17

**Comment by torrentalle** [comment]
This bug is fixed in `master` branch
