### ISSUE TITLE
Laravel 5.2 unique validation

### ISSUE THREAD

**Issue by danilodelacruz** [proengsoft/laravel-jsvalidation#164]
When i trying to validate unique validation, session randomly destroy and it create another session data and it throw a Token Mismatch Exception.

**Comment by marcelogarbin** [comment]
@danilodelacruz Hi, have you been able to use unique for validation?

**Comment by danilodelacruz** [comment]
@marcelogarbin, Yes, I'm using it for L5.2 and L5.3.

**Comment by marcelogarbin** [comment]
@danilodelacruz I want to use L5.4, are you using it in the Request? Would you like to show an example of validation with Unique? I opened this issue https://github.com/proengsoft/laravel-jsvalidation/issues/255

I know how to use all the validation of Laravel, but I could not use the unique issue with this package.

My idea was to use something like:
```
public function rules()
    {
        switch($this->method()){
            CASE 'POST':
            {
                return [
                    'readable_name'  => 'required|alpha_spaces|max:255|unique:nw_roles,readable_name'
                ];
            }
            CASE 'PUT':
            CASE 'PATCH':
            {
                return [
                    'readable_name'  => 'required|alpha_spaces|max:255|unique:nw_roles,readable_name,'.$this->role_id
                ];
            }
            default: break;
        }
    }
```

**Comment by danilodelacruz** [comment]
public function rules()
{
    return [
         'name' => 'unique:roles,name,'.(($this->get_id_from_url()) ? $this->get_id_from_url():'NULL').',id',

    ];
}

public function get_id_from_url()
{
    
    return $this->roles; //return 3
}

**Comment by marcelogarbin** [comment]
@danilodelacruz Fine, thanks for sharing. And is it working properly? Did you have any problem?

With this package no longer use the `switch($this->method())` to separate the POST / GET / PATCH requests, use only one rule for everything, that's right?

**Comment by a-komarev** [comment]
@marcelogarbin Yes. You need to have separate form request for each form. You can make base form request for entity and extend it with concrete ones.

**Comment by marcelogarbin** [comment]
@a-komarev @danilodelacruz  Ok, let me try to understand.  I'm making individual request for each form.
I wrote the following in my RequestRole:
```
public function rules()
    {
        $id = (isset($this->permissao))? Hashids::decode($this->permissao)[0] : 'NULL';
        return [
            'readable_name'  => 'required|alpha_spaces|max:255|unique:nw_roles,readable_name,'.$id.',id'
        ];
    }
```

@a-komarev By doing only this rule I can answer the store and update method, right? If yes, you can close this issue https://github.com/proengsoft/laravel-jsvalidation/issues/255

This worked for me =)

**Comment by a-komarev** [comment]
@marcelogarbin If `store` and `update` methods has the same validation rules - you could use the same `FormRequest` for it.

**Comment by marcelogarbin** [comment]
@a-komarev Okay, but when I use the unique method, it ends up changing all the validation, in that case it would have to have each form have its Request rules, right?
I'm creating an application in modules. I believe I will have to use the individual Request validations for each form.

Application structure to date:
![image](https://user-images.githubusercontent.com/9335588/28088213-5d42925a-665b-11e7-9ba8-b5af915b714b.png)

**Comment by a-komarev** [comment]
@marcelogarbin Laravel allows you to have same `unique` validation rule for `store` and `update` methods.

```
unique:table,column,except,idColumn
```

Just pass `null` value as `except` attribute and it should work.

```php
public function rules()
{
    $id = isset($this->permissao) ? Hashids::decode($this->permissao)[0] : null;
    return [
        'readable_name'  => 'required|alpha_spaces|max:255|unique:nw_roles,readable_name,'.$id.',id
    ];
}
```

**Comment by a-komarev** [comment]
Closing this issue since solution was found. Thanks for confirmation.
