### ISSUE TITLE
Form gets robbed when using AJAX (submit button values are missing.)

### ISSUE THREAD

**Issue by druc** [proengsoft/laravel-jsvalidation#165]
Hello, 
I found an issue with sending submit button values (when you need two submit buttons with different values to take different actions on the backend - e.g one to redirect to the index, another one to the edit page).

For some reason it only does that when an AJAX check is made (unique/exists rule).

Basically the submit values are not sent..and I have no idea why...

**Comment by druc** [comment]
Hello, 

I did some digging in the source code and I found that the form gets submitted using jQuery (daah), so the submit values aren't passed through.

My "fix" was to modify the  `stopRequest` method by appending hidden fields. I'm pretty sure it's not the best way to go about it, but it seems to be working.  

```
stopRequest: function( element, valid ) {
    this.pendingRequest--;
    // sometimes synchronization fails, make sure pendingRequest is never < 0
    if ( this.pendingRequest < 0 ) {
        this.pendingRequest = 0;
    }
    delete this.pending[ element.name ];
    if ( valid && this.pendingRequest === 0 && this.formSubmitted && this.form() ) {

        var currentForm = $( this.currentForm);

        //look for submit buttons
        currentForm.find('button, :submit').each(function(i, item) {
            var self = $(item),
                tempElement = $("<input type='hidden'/>");
            
            // clone name&value and append them to the form
            tempElement
                .attr("name", item.name)
                .val(self.val())
                .appendTo(currentForm);
        });

        currentForm.submit();
        this.formSubmitted = false;
    } else if (!valid && this.pendingRequest === 0 && this.formSubmitted ) {
        $( this.currentForm ).triggerHandler( "invalid-form", [ this ]);
        this.formSubmitted = false;
    }
},
```

**Comment by stmn** [comment]
The code above will add all button values to the post.

I created hidden field:
```<input type="hidden" name="action" autocomplete="off" value="" />```

And onclick for buttons:
```
<button type="submit">Save</button>
<button type="submit" name="print" onclick="$('[name=action]').val(this.name)">Save and print</button>
```

No vendor source code editing. This should be fixed, I don't think it is intended effect.

**Comment by druc** [comment]
Old...?
