### ISSUE TITLE
Chrome and IE LowerParams release v1.3.1 (related issue #136)

### ISSUE THREAD

**Issue by aleixfabra** [proengsoft/laravel-jsvalidation#167]
As I could read in the #136 issue, you discuss about this problem.

But, why this is not fixed in the latest version v1.3.1?

https://github.com/proengsoft/laravel-jsvalidation/blob/v1.3.1/resources/assets/js/validations.js#L368

**Comment by HarleyFuagras** [comment]
:+1:

**Comment by torrentalle** [comment]
This should be fixed in current release `v1.4.0`
