### ISSUE TITLE
Odd Javascript code

### ISSUE THREAD

**Issue by Bertuzb** [proengsoft/laravel-jsvalidation#169]
https://github.com/proengsoft/laravel-jsvalidation/blob/master/resources/assets/js/helpers.js#L102

What is this? it throws me an error and that seems obvious to me.

Also is there any way all the files in https://github.com/proengsoft/laravel-jsvalidation/blob/master/resources/assets/js can be neatly organised into 1 file? seems like all are needed for a functioning js-validation and i was initially having trouble with the order these files are being included

**Comment by torrentalle** [comment]
All [assets](https://github.com/proengsoft/laravel-jsvalidation/tree/master/resources/assets/js) are mixed into a file publised to [public/js/jsvalidation.js](https://github.com/proengsoft/laravel-jsvalidation/blob/master/public/js/jsvalidation.js).

You only have to include the javascript files published into `vendor/jsvalidation/js` folder

See [Basic Usage](https://github.com/proengsoft/laravel-jsvalidation/wiki/Basic-Usage) and [Contributing Guide](https://github.com/proengsoft/laravel-jsvalidation/wiki/Contributing) to get more information
