### ISSUE TITLE
How to validate array inputs?

### ISSUE THREAD

**Issue by emmanuelLS** [proengsoft/laravel-jsvalidation#174]
Hi Im trying to validate an array inputs like this.

```
{!!Form::open()!!}
   <input type="text" name="value1[]">
   <input type="text" name="value1[]">
  {!! Form::submit('submit') !!}
{!! Form::close()!!}

```

This is my controller

```
 $rules = [


                       'value1[]' => 'required|array',

                ];
$data = $request->all()

 $validator = Validator::make($data, $rules);

                if ($validator->fails())
                {
                    return redirect()->back()->withErrors($validator->errors());
                }

```

Unfortunately, it doesn't seem to work. Any work around for this? 

Thanks,

**Comment by moiroca** [comment]
I would suggest creating a Form Request.

[Creating Form Request](https://laravel.com/docs/master/validation#form-request-validation)

And Handle you validation using

`$this->request->get('array_input_name_here');`


You can loop through and create custom message for your validation.

**Comment by emmanuelLS** [comment]
Unfortunately Im getting error when getting the value for request. I did loop however, it was getting null. For now it is not working for JsValidator::formRequest()

**Comment by a-komarev** [comment]
@emmanuelLS #158 is it what you are looking for?

**Comment by emmanuelLS** [comment]
@a-komarev actually I already read that thread, however it only validate the first element,

**Comment by moiroca** [comment]
> Unfortunately Im getting error when getting the value for request. I did loop however, it was getting null. For now it is not working for JsValidator::formRequest()
@a-komarev
 
Can you post your error so I can take a look? Thanks!

**Comment by Lescazel** [comment]
I have the same problem with my form. I also have array fields and tried to loop through.

Code in view:
```
{!! Form::text('test[][name]', null, array('value' => '', 
												'class' => 'form-control', 
												'placeholder' => 'test' )) !!}
```
Code in FormRequest:
```
for ($i = 1; $i <= count($this->request->get('test')); $i++) {
			$rules['test.' . $i . '.name'] = 'required';
		}
```
Validation on server side works as expected, but on clientside $this->request->get('test') always returns 0, so it won't loop through the rules. 

Moreover I read in the wiki, that it should be possible to validate with dot-notation (new in Laravel 5.2). I also tried this:
Code in FormRequest:
```
$rules = [
	'test.*.name' => 'required', 
        [...]
];
```
serverside validation works as expected, but clientside nothing happens. It seems that JSValidation ignores the array-field.

**Comment by set0x** [comment]
I have the same problem. In the documentation say "Validating Arrays using wildcards ['person.*.email' => 'email|unique:users'] is not supported. #139 (supported in master branch)", I have tried to use  the master branch but not working. I found a very bad solution, adding to request the rule "person.0.name" for example. _Sorry for my bad English._

**Comment by sakalauskas** [comment]
@emmanuelLS  have you tried just  'value1' instead of 'value1[]'? I think it should work.

**Comment by Lescazel** [comment]
@sakalauskas it doesn't work for me to omit the []. With them it works on clientside, but on serverside I get displayed the error.

Does anyone else found a solution to use the wildcards in JSValidation?

**Comment by torrentalle** [comment]
This feature is supported in latest version
