### ISSUE TITLE
required_unless is not working (or I don't understand how it's supposed to work)

### ISSUE THREAD

**Issue by littletreex** [proengsoft/laravel-jsvalidation#177]
I have verified that I can get something like `required_if:intendedStoreID,2|required_if:intendedStoreID,3` to work. However `required_unless:intendedStoreID,2` is not functioning. When I view code I see a crazy token in place of the usual array of name/value pairs. 

Is this a known issue? How can I work around this, in any case?

**Comment by torrentalle** [comment]
Hi,
required_unless rule is working on release `v1.4.2`
