### ISSUE TITLE
Add support to validate multi-select fields

### ISSUE THREAD

**Issue by dcro** [proengsoft/laravel-jsvalidation#180]
Multi-select fields like the one in the following example are not currently validated on the JS side:

**HTML form**

``` html
<form>
     <select multiple name="group[]">
         <option value="1">Administrators<option>
         <option value="2">Editors</option>
    </select>
</form>
```

**Laravel Validation Rules**

``` php
$rules = [
    'group' => 'required|array|exists:groups,id',
];
```

The server side validation works properly in this case, but the jQuery Validation plug-in is never triggered for the multi-select field as it expects the field's name to be `group[]` in the rules array.

**Comment by torrentalle** [comment]
This is fixed in release v1.4.3
