### ISSUE TITLE
Class 'App\Http\Controllers\JsValidator' not found

### ISSUE THREAD

**Issue by Alexmg86** [proengsoft/laravel-jsvalidation#183]
Hi, i used this guide
https://github.com/proengsoft/laravel-jsvalidation/wiki/Installation
wrote in controller
$validator = JsValidator::make(['type_list'=>'required']);
and have error
Class 'App\Http\Controllers\JsValidator' not found

Laravel 5.2

**Comment by rhonz10** [comment]
It does not work even though it's already on alias in config/app.php

Try this:

`<?php`
`namespace App\Http\Controllers;`

`use Proengsoft\JsValidation\Facades\JsValidatorFacade;`

`$validator = JsValidatorFacade::make(['type_list'=>'required']);`

**Comment by Alexmg86** [comment]
Thanks!

**Comment by torrentalle** [comment]
Hello

You can simply add `use JsValidator;` in your class

```php
<?php
namespace App\Http\Controllers;
use JsValidator;

class MyController extends Controller {
    public function form() {
        $validator = JsValidator::make(['type_list'=>'required']);
    }
}
```
