### ISSUE TITLE
Numeric and numbers

### ISSUE THREAD

**Issue by femanso** [proengsoft/laravel-jsvalidation#21]
The js is not using laravel´s language file when I call the numeric/number validation. It works as validation but it is using the Javascript language string.

```
 $validationRules=[
                'title' => 'required|max:100',
                'description' => 'required|max:1000',
                'plan' => 'required',
                'winners' => 'required|numeric|min:1',
                'tags' => 'required|numeric',
                'category' => 'required',
                'draw_at' => 'required|date_format:d/m/Y H:i|after:now'
    ];
```

**Comment by torrentalle** [comment]
I will check it

**Comment by torrentalle** [comment]
I can't reporoduce your error. Can you send me the your language file?

**Comment by femanso** [comment]
I found out this only happens when I set the input field type as "number" and set min and max values:

```html
<input type="number" name="winners" value="1" class="form-control" min="1" max="50" aria-invalid="true" aria-describedby="winners-error">
```
Laravel validation:
```php
'winners' => 'required|numeric|min:1|max:50',
```
If i set 99 to the field i get the msg: "Please enter a value less than or equal to 50."
This msg isn't coming from Laravel lang files.
If I don't set the min and max, it works properly, so I'm not sure this needs a fix.

**Comment by torrentalle** [comment]
I will check it

**Comment by torrentalle** [comment]
There's a bug in numeric validation. I'm working on that

**Comment by torrentalle** [comment]
I think that this issue is related to #29

**Comment by torrentalle** [comment]
This bug is fixed in `master` branch
