### ISSUE TITLE
my own methods

### ISSUE THREAD

**Issue by ryuphi** [proengsoft/laravel-jsvalidation#22]
Hi! I want to know how to implements my own validation methods that extends from laravel validation class? or How to use these methods?

**Comment by torrentalle** [comment]
Is not supported now. In the next release will be prossible.

**Comment by dennisoderwald** [comment]
+1

**Comment by torrentalle** [comment]
This feature is implemented in `master` branch.
Shortly I will release new version

**Comment by torrentalle** [comment]
This is now supported in latest release using 
[Custom Validation Rules](http://laravel.com/docs/5.1/validation#custom-validation-rules). 
Custom validator clases are not supported in this release
