### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by reganjohnson** [proengsoft/laravel-jsvalidation#222]
You will need to change the following in `/laravel-jsvalidation/src/JsValidatorFactory.php`:

```
if ($session = $request->getSession()) {
    $formRequest->setSession($session);
}
```

to 

```
if ($session = $request->getSession()) {
    $formRequest->setLaravelSession($session);
}
```

This change will cause incompatibility with Laravel 5.3 and below but get's your 5.4 working.

**Comment by reganjohnson** [comment]
Also receiving error:

```
BadMethodCallException in Validator.php line 1067:
Method [parseRule] does not exist.
```

**Comment by a-komarev** [comment]
We should check for laravel version and decide which laravel set session method should be called then.

**Comment by reganjohnson** [comment]
For some more fixes:

`parseRule` has been moved from `\Illuminate\Validation\Validator@parseRule` and to `\Illuminate\Validation\ValidationRuleParser@parse`.

`doReplacements` has been renamed from `\Illuminate\Validation\Validator@doReplacements` to `\Illuminate\Validation\Validator@makeReplacements `.

**Comment by jackkitley** [comment]
Thanks @reganjohnson! When will these fixes be merged in for 5.4?

**Comment by reganjohnson** [comment]
Haven't had time to make a proper PR for the update - hoping someone else can use the above info to do so, or the package maintainer. I am just running off a private fork for the time being.

**Comment by OzanKurt** [comment]
@reganjohnson Where did you do the changes about the renames?

**Comment by reganjohnson** [comment]
They are referenced in the last comment... `\Illuminate\Validation\Validator@parseRule` is the same as `\Illuminate\Validation\Validator.php` at method name `parseRule`.

The package maintainer seems somewhat MIA on these updates.

**Comment by OzanKurt** [comment]
@reganjohnson Can you add me to your private fork?

**Comment by reganjohnson** [comment]
Sure!

In your composer.json file, use the following...

```
{
    "require": {
            "proengsoft/laravel-jsvalidation": "^1.6.0-dev"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/reganjohnson/laravel-jsvalidation"
        }
    ]
}
```

I will also be submitting a PR with these changes for the package maintainer to review, however, more work is needed to support version below 5.4.

**Comment by wnasirou** [comment]
@reganjohnson! When will these fixes be merged in for Laravel 5.4?

**Comment by OzanKurt** [comment]
You should stop waiting for that and use the method we did.

Ozan Kurt

**Comment by simonigd** [comment]
Updated composer  "proengsoft/laravel-jsvalidation": "^1.6.0-dev"
as above. I have a lot of rules that use the following.

This is from the request validation on the server.
'billing_address' => 'required_without:previous_address|max:40',
These seem to have stopped working now..

**Comment by csthink** [comment]
3Q

**Comment by codemonkeynorth** [comment]
with 1.6.0-dev, it appears that some rules like min and max don't work if remote validation is disabled?

`'firstname' =>             'required|alpha|min:1|max:35',` 

gives

`rules: {"firstname":{"laravelValidation":[["Required",[],"Please enter your first name",true],["Alpha",[],"The firstname may only contain letters.",false]]}`


whereas with remove validation enabled

`rules: {"firstname":{"laravelValidation":[["Required",[],"Please enter your first name",true],["Alpha",[],"The firstname may only contain letters.",false]],"laravelValidationRemote":[["Min:1",["firstname","eyJpdiI6ImFmZFdZOWhDXC9CcTU0bHo2N3QrN1ZRPT0iLCJ2YWx1ZSI6IjdDaEJhN3E0Uk9mUVBSVDN1QWZSXC8rRXVrQkhVSkZod3dFTDB5U015RmpRVTc4aGZIeDdtQUtpM0Y0eHdsOThWXC81K05iK3FJbEJJaEQ5UmJIXC9OWTVnPT0iLCJtYWMiOiI5MjZiODE2YjJmYTYwZjY1Y2ZiNjcwNWQ1NGQ0MTY2MmM0NmFkYzYxNzc1NTVjYTAzNzJiN2RmZmFjOGY0NzU2In0=",false],"validation.min:1",false],["Max:35",["firstname","eyJpdiI6ImFmZFdZOWhDXC9CcTU0bHo2N3QrN1ZRPT0iLCJ2YWx1ZSI6IjdDaEJhN3E0Uk9mUVBSVDN1QWZSXC8rRXVrQkhVSkZod3dFTDB5U015RmpRVTc4aGZIeDdtQUtpM0Y0eHdsOThWXC81K05iK3FJbEJJaEQ5UmJIXC9OWTVnPT0iLCJtYWMiOiI5MjZiODE2YjJmYTYwZjY1Y2ZiNjcwNWQ1NGQ0MTY2MmM0NmFkYzYxNzc1NTVjYTAzNzJiN2RmZmFjOGY0NzU2In0=",false],"validation.max:35",false]]}`

**Comment by codemonkeynorth** [comment]
i worked out why some of the validation functions aren't working...

 this function is tagging them as remote rules as it's trying to look for "Min:1" in an array with "Min", therefore it's not being put into the rules to validate when remote is disabled. (This is also going to cause problems with custom rule names eg I created a 'postcode' and a 'alpha_num_spaces' rule)

```php
protected $clientRules = ['Accepted', 'After', 'Alpha', 'AlphaDash',
        'AlphaNum', 'AlphaNumSpaces', 'Array', 'Bail', 'Before', 'Between', 'Boolean', 'Confirmed', 'Date', 'Dimensions',
        'DateFormat', 'Different', 'Digits', 'DigitsBetween', 'Distinct', 'Email', 'File', 'Filled', 'Image',
        'In', 'InArray', 'Integer', 'Ip', 'Json', 'Max', 'Mimes', 'Mimetypes', 'Min', 'NotIn', 'Nullable',
        'Numeric', 'Regex', 'Required', 'RequiredIf', 'RequiredUnless', 'RequiredWith', 'RequiredWithAll',
        'RequiredWithout', 'RequiredWithoutAll', 'Same', 'Size', 'Sometimes',
        'String', 'Timezone', 'Url', ];

protected function isRemoteRule($rule)
{   
        return in_array($rule, $this->serverRules) ||
            ! in_array($rule, $this->clientRules);
}
```

ideally it needs to strip anything before `:` before comparing

**Comment by simonigd** [comment]
Are you going to release these changes?

**Comment by azorpax** [comment]
the validating arrays are not working.
'person.*.first_name' => 'required',
----------------
not generating js rule for the above condition. 
can anyone confirm please?

**Comment by akkhan20** [comment]
update to dev-master for L5.4

**Comment by meltzow** [comment]
acknowledge dev-master is working with laravel v5.4.25

**Comment by a-komarev** [comment]
Yeah... Laravel 5.4 is supported. The only thing is left - return back support of Laravel < 5.4 and we will be ready for new stable release. Follow: #242 
I'm closing this issue since 5.4 is working. If there any more problems with it - reopen this issue or open a new one. Thanks.

**Comment by marcelogarbin** [comment]
Can the form be submitted even with blank required fields?

**Comment by marcelogarbin** [comment]
And sometimes the user field is required and sometimes not. Staying in this state.

![image](https://user-images.githubusercontent.com/9335588/27363922-b4ed3702-560d-11e7-8dfc-c181b27b2b60.png)

**Comment by a-komarev** [comment]
@marcelogarbin I'd recommend you to make separate Issue for your question. Since this one is related to Laravel versions support and already closed.

**Comment by marcelogarbin** [comment]
@a-komarev Okay, I already did that =)

https://github.com/proengsoft/laravel-jsvalidation/issues/248
