### ISSUE TITLE
Inconsistent URL validation

### ISSUE THREAD

**Issue by bytestream** [proengsoft/laravel-jsvalidation#232]
[jsvalidation's](https://github.com/proengsoft/laravel-jsvalidation/blob/master/public/js/jsvalidation.js#L1196) URL validation is inconsistent with [Laravel's validation](https://github.com/scrothers/framework/blob/master/src/Illuminate/Validation/Validator.php#L1201)

For example:
````http://localhost/test```` is valid in Laravel but not by jsvalidation

**Comment by simonigd** [comment]
I think this package doesn't seem to be getting maintained anymore

**Comment by pulselife** [comment]
I think maybe there is some fork with fixes.

**Comment by a-komarev** [comment]
@simonigd I'm not sure about it. @torrentalle has pushed a lot of fixes not so far.

@bytestream @pulselife Feel free to add PRs here =)
