### ISSUE TITLE
[L5.4] seems like last two days you and laravel both released new package and by that some error was occured, so kindly check it out.

### ISSUE THREAD

**Issue by harshad-concetto** [proengsoft/laravel-jsvalidation#236]
current im facing the error like,
----------------------------
array_key_exists() expects parameter 2 to be array, boolean given (View page)

![e224f8ee76596b2258cb400823fb9965eefe2516fc09322a75 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/19650013/25084831/621aec04-237c-11e7-8df7-b5dc230ae049.png)

**Comment by HarshadPatel4** [comment]
i have latest version of laravel 5.4.19

**Comment by panttojo** [comment]
I have the same problem

**Comment by mohanmunusamy** [comment]
I'm having the same problem. It's fine with Laravel 5.3 but getting the "array_key_exists() expects parameter 2 to be array, boolean given" error in Laravel 5.4.

**Comment by kamrava** [comment]
same here

**Comment by gregc88** [comment]
you could add some small workaround. I changed one line in file "`vendor/proengsoft/laravel-jsvalidation/src/JsValidatorFactory.php`" on line 157 from: 
`$formRequest = $this->app->build($class, $params);`
to:
`$formRequest = new $class;`
it seems to work on all my projects that use Laravel 5.4.19 but that's probably not the best solution, but it works :)
of course for Laravel 5.4 I also using this patch: [Add Support For Laravel 5.4](https://github.com/proengsoft/laravel-jsvalidation/pull/234/files)

**Comment by HarshadPatel4** [comment]
great @gregc88

**Comment by a-komarev** [comment]
You can use my temporary repository. In `composer.json` change `proengsoft/laravel-jsvalidation` in `require` section to this one:
```
"proengsoft/laravel-jsvalidation": "dev-dev-laravel54",
```

And Add `repositories` section with following content:

```
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/cybercog/laravel-jsvalidation"
        }
    ],
```
After performed changes make `composer update`.

**Comment by a-komarev** [comment]
Laravel Container was fixed in recent PR. It will be included in next Laravel release.
