### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, boolean given (View: C:\wamp\www\aot\resources\views\pages\subjectcategory\add_subject_category.blade.php)

### ISSUE THREAD

**Issue by bindusree** [proengsoft/laravel-jsvalidation#237]
Iam getting the issue
array_key_exists() expects parameter 2 to be array, boolean given (View: C:\wamp\www\aot\resources\views\pages\subjectcategory\add_subject_category.blade.php)
while including jsvalidator

**Comment by Adebolavictor** [comment]
I am also having the same issue

**Comment by thetispro** [comment]
+1

**Comment by laemol** [comment]
same after update to 5.4

**Comment by nhtahoe** [comment]
Same issue here after update from Laravel 5.4.18 to 5.4.19. Something to do with https://github.com/laravel/laravel/pull/4229 ?

**Comment by moehtet** [comment]
same issue after update from Laravel 5.4.16 to 5.4.19.

**Comment by landart** [comment]
Issue introduced with 5.4.19, 5.4.18 works fine

**Comment by roshimon** [comment]
I'm also facing the same issue. I'm using Laravel 5.4.21

**Comment by JoseSantillan** [comment]
same here, I'm using Laravel v5.4.21 as well

**Comment by nouzun** [comment]
same here!

**Comment by joelbaluma** [comment]
how to solve this?

**Comment by JoseSantillan** [comment]
I used the workaround from this comment: https://github.com/proengsoft/laravel-jsvalidation/issues/236#issuecomment-295954078

What I did is use this

"require": {
    "proengsoft/laravel-jsvalidation": "dev-master#84fe201dd1be838f6ca8c90e7be461443472f1ee"
  },

and then in vendor\proengsoft\laravel-jsvalidation\src\JsValidatorFactory.php line 158 change
$formRequest = $this->app->build($class, $params);
to
$formRequest = new $class;

I got all this from here:

**Comment by a-komarev** [comment]
You can use my temporary repository. In `composer.json` change `proengsoft/laravel-jsvalidation` in `require` section to this one:
```
"proengsoft/laravel-jsvalidation": "dev-dev-laravel54",
```

And Add `repositories` section with following content:

```
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/cybercog/laravel-jsvalidation"
        }
    ],
```
After performed changes make `composer update`.

**Comment by a-komarev** [comment]
Laravel Container was fixed in recent PR. It will be included in next Laravel release.
