### ISSUE TITLE
[JS] JPEG mime-type check in image rule

### ISSUE THREAD

**Issue by JoseSantillan** [proengsoft/laravel-jsvalidation#239]
I'm trying to upload an image with jpeg extension, using the image rule.
If i disable the client validation, the image validates correctly, but when using the javascript validation, the client side validation fails.

When I add jpeg in this line https://github.com/proengsoft/laravel-jsvalidation/blob/master/public/js/jsvalidation.js#L3991  in my local copy it seems to be fixed.

**Comment by a-komarev** [comment]
@JoseSantillan I've pushed changes in PR #261. If PR will be approved it will be available in `2.0`.
