### ISSUE TITLE
Laravel 5.4 Support?

### ISSUE THREAD

**Issue by akkhan20** [proengsoft/laravel-jsvalidation#240]
any deadline when will the package be updated to support Laravel 5.4 as i see a few PRs that claims to make it compatible with Laravel 5.4

**Comment by a-komarev** [comment]
We are waiting for @torrentalle check and accept one of the PRs :\

**Comment by akkhan20** [comment]
i see 2 PRs 1 got 3/5 checks ok & other 1 got 4/5 checks ok, i tried implementing the changes in the PRs but wasn't able to succeed, i hope he accept & merge the changes soon

**Comment by a-komarev** [comment]
@akkhan20 This one is working for me: #224

**Comment by akkhan20** [comment]
ok im going to implement it but can you guide me on one more thing i.e i'll make these changes in the current stable package but when later on he updates the package, will my changes be overridden completely or will they create a conflict and if a file that i have changed in his package and he doesn't change anything in that file in his update will that create an issue?

**Comment by a-komarev** [comment]
You can make fork and use it, and later when it will be released just switch back to this package.

I've described earlier what I'm using right now: https://github.com/proengsoft/laravel-jsvalidation/issues/237#issuecomment-300660493

**Comment by akkhan20** [comment]
@a-komarev alright thanks alot

**Comment by akkhan20** [comment]
@a-komarev im trying to validate this rule on a dynamic field
`'tasks.*'    =>    'required|min:10|max:65500'`
and in form this field is present by default and others will be added on demand:
`<textarea class="form-control" name="tasks[]" rows="3" placeholder="Task to be done"></textarea>`
but it doesnt validate or show any errors but just sends the form without validating this field, is it because of the temporary package or what? like i see in the comment that the default package can validate such fields

**Comment by a-komarev** [comment]
Maybe it's not supported in Laravel 5.4 :( We should check it then. I haven't using it with wildcards.

**Comment by akkhan20** [comment]
Laravel 5.5 is on its way and yet this awesome package ❤️ is falling back on the updates, a sad story 😞

**Comment by a-komarev** [comment]
@akkhan20 Laravel 5.5 will be published in the end of July - start of August.

**Comment by akkhan20** [comment]
@a-komarev yes my friend its exactly like that but we haven't hit 5.4 yet and may be 5.5 brings some more hurdles.

**Comment by drjoju** [comment]
Hi, I accepted the last pull request.

**Comment by marcelogarbin** [comment]
@akkhan20  @a-komarev  How is the issue of compatibility with L 5.5? It's working? Thank's =)

**Comment by a-komarev** [comment]
@marcelogarbin changes in Laravel API were made in Laravel 5.4. So after making 5.5 support we've automatically should have working L5.4. And yes, as far as I know it's working, but with some validation problems, but it's highlighted in other opened issues.
