### ISSUE TITLE
[L5.2] Has problem with larvel 5.2 after your new changes.

### ISSUE THREAD

**Issue by Mobasher-NetLinks** [proengsoft/laravel-jsvalidation#242]
FatalErrorException in ValidationRuleParserProxy.php line 17:
Class 'Illuminate\Validation\ValidationRuleParser' not found

Please help on this.

**Comment by a-komarev** [comment]
@Mobasher-NetLinks Don't use `dev-master` dependency. It seems latest release breaks backward compatibility. We need to update the code or make a major release with dropping Laravel < 5.4 support in them.

**Comment by a-komarev** [comment]
@Mobasher-NetLinks You still can use `"proengsoft/laravel-jsvalidation": "^1.0"` in your composer.json file.

**Comment by a-komarev** [comment]
For Laravel 5.4 support `dev-master` should be used until old versions of Laravel wouldn't be supported as well.

**Comment by a-komarev** [comment]
@simonigd Lets move discussion to more appropriate issue.
It seems the problem is related to `ValidationRuleParser` class call which was introduced in Laravel 5.4. Old Laravel versions don't have it.

**Comment by Mobasher-NetLinks** [comment]
Yeah! when i changed my composer.json and used from the older version its
working.
