### ISSUE TITLE
Which version to pull for Laravel 5.3x?

### ISSUE THREAD

**Issue by kunxin-chor** [proengsoft/laravel-jsvalidation#244]
It seems that a latest commit to the dev-master branch of the package does not work with Laravel 5.3

Is there an official version that we should use for Laravel 5.3 and below?

**Comment by a-komarev** [comment]
#242

**Comment by a-komarev** [comment]
For Laravel < 5.4 use stable releases.
`"proengsoft/laravel-jsvalidation": "^1.0"` in your composer.json file is a good choice.

**Comment by akkhan20** [comment]
yes use 1.5 version
