### ISSUE TITLE
[L5.4] Method [parseRule] does not exist.

### ISSUE THREAD

**Issue by abdulrahim9** [proengsoft/laravel-jsvalidation#247]
Controller:
```
<?php

namespace App\Http\Controllers;
use JsValidator;


class ValidationTestController extends Controller
{
    protected $validationRules=[
        'name' => 'required|string|max:255',
        'email' => 'required|string|email|max:255|unique:users',
        'password' => 'required|string|min:6|confirmed',
    ];


    public function test()
    {
        $validator = JsValidator::make($this->validationRules);

        return view('validationTest')->with([
            'validator' => $validator
        ]);

    }
}
```

In the .blade.php I put the following after the divs and before @endsection:
```
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
<!-- Laravel Javascript Validation -->
<script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js', '#my-form')}}"></script>
{!! $validator->render() !!}
```

Result: `Method [parseRule] does not exist.`

If I change the `$validator->render()` to only `$validator` I get:
`Method Proengsoft\JsValidation\Javascript\JavascriptValidator::__toString() must not throw an exception`

I tried to remove the `#my-form` argument in the .blade.php and there was no difference.
I also tried to send `#my-form` as the fourth argument from the controller to the view and there was no difference.

Edit:
I'm using Laravel 5.4 with package version 1.5.

**Comment by a-komarev** [comment]
@abdulrahim9 What Laravel and package versions are you using?

**Comment by abdulrahim9** [comment]
Laravel 5.4 with package version 1.5.

**Comment by a-komarev** [comment]
@abdulrahim9 Laravel 5.4 is working on `dev-master` for now only. Stable versions are for Laravel 5.3 and lower.

**Comment by a-komarev** [comment]
Laravel 5.4 support will be released soon in `2.x` branch.
