### ISSUE TITLE
Multiple forms in the same view

### ISSUE THREAD

**Issue by asaf050** [proengsoft/laravel-jsvalidation#25]
Hey,
How can I create multiple instance of jsvalidation and use it in a view? (for multiple forms with different rules).

Thanks

**Comment by CylonSK** [comment]
In this case you should create a FormRequest for each validation then inject it into a controller method. In view you call this
` {!! JsValidator::formRequest('App\Http\Requests\StoreBlogPostRequest', '#my-form'); !!}`
where you can set path to your FormRequest and ID of form that is related to.


Hope it helps
