### ISSUE TITLE
Guess Date Rule has a typo

### ISSUE THREAD

**Issue by bastman69** [proengsoft/laravel-jsvalidation#250]
resources/assets/js/helper.js
 /**
         * This method allows you to intelligently guess the date by closely matching the specific format.
         * @param value
         * @param format
         * @returns {Date}
         */
        gessDate: function (value, format) {
            var fmt = new DateFormatter();
            return fmt.guessDate(value, format)
        },

**Comment by a-komarev** [comment]
Where is it using? In user app custom scripts?
