### ISSUE TITLE
Travis failed to build app because of missing dependencies

### ISSUE THREAD

**Issue by bastman69** [proengsoft/laravel-jsvalidation#252]
PHP Fatal error:  Class 'Illuminate\Validation\ValidationRuleParser' not found in /home/travis/build/proengsoft/laravel-jsvalidation/src/Remote/Validator.php on line 157

**Comment by akkhan20** [comment]
'home'??
isn't that related to path?

**Comment by a-komarev** [comment]
Thats an issue with Laravel < 5.4 support.

**Comment by a-komarev** [comment]
I've started to fix Travis tests: #257

**Comment by a-komarev** [comment]
Closing this issue since Travis build is working well with Laravel 5.4 now. For older Laravel versions use `1.x` releases.
