### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by antonkomarev** [proengsoft/laravel-jsvalidation#265]
We are close to 2.0 release!

Please read [changelog](https://github.com/proengsoft/laravel-jsvalidation/blob/master/CHANGELOG.md#200---2017-07-10) and test `dev-master` in your applications. If no issues would be reported today - I'll make a release tomorrow.

CC: @simonigd @akkhan20 @bastman69 @asurace

**Comment by simonigd** [comment]
Excellent stuff.
I will try it on my application its uses it to the limit

**Comment by a-komarev** [comment]
@simonigd any news on it?

**Comment by akkhan20** [comment]
i think we should go ahead with 2.0 release and fix the reported and known issues while incrementing patch versions, the basic rules are working well but if u want me to test all the rules listed in laravel validation i can do that on a dummy form, will take an hour or 2

**Comment by a-komarev** [comment]
@akkhan20 It's up to you. If you have a free time for it - it will be good to test everything and collect current issues for next patch releases.

**Comment by a-komarev** [comment]
I'll try to publish 2.0 release today in any case.

**Comment by akkhan20** [comment]
ill update you about that in a few hours

**Comment by a-komarev** [comment]
@akkhan20 Feel free to use for tests stable 2.0.0 version. I'll leave this issue open for a some time until everybody will test new version.

**Comment by akkhan20** [comment]
Tested the Version 2.0 of this package for the given below validation rules in Laravel Framework 5.4.28

________________________
:heavy_check_mark: **Pass**
:x: **Fail**
:negative_squared_cross_mark: **Not Tested**
:heavy_exclamation_mark: **Unconfirm**
_______________________

- [:heavy_check_mark:] **accepted**

- [:heavy_check_mark:] **active_url**

- [:heavy_check_mark:] **after**

- :heavy_check_mark:] **after_or_equal**

- [:heavy_check_mark:] **alpha**

- [:heavy_check_mark:] **alpha_dash**

- [:heavy_check_mark:] **alpha_num**

- [:negative_squared_cross_mark:] **array**

- [:heavy_check_mark:] **before**

- [:heavy_check_mark:] **before_or_equal**

- [:heavy_exclamation_mark:] **between** 
> (Strings & Numeric works fine not tested on arrays & files)

- [:heavy_check_mark:] **boolean**

- [:heavy_check_mark:] **confirmed**

- [:heavy_check_mark:] **date**

- [:x:] **date_format** 
> (format: dd-mm-yyyy but submitting the form when '1st june' is input)

- [:heavy_check_mark:] **different**

- [:heavy_check_mark:] **digits**

- [:heavy_check_mark:] **digits_between**

- [:negative_squared_cross_mark:] **dimensions**

- [:negative_squared_cross_mark:] **distinct**

- [:heavy_check_mark:] **email**

- [:heavy_exclamation_mark:] **exists**
> (doesn't work on rule:
`'state' => 'exists:states'`
> needs clarification what column is it supposed to look for if it require the column state then that
> wasn't present in DB, works with:
`'state' => 'exists:states,state_name'`
> not tested with:
`'email' => 'exists:connection.staff,email'`
> requires more testing)

- [:negative_squared_cross_mark:] **file**

- [:heavy_check_mark:] **filled**

- [:negative_squared_cross_mark:] **image**

- [:heavy_exclamation_mark:] **input**
> ( works fine with:
`'test' => 'in:abc,xyz'` 
> not tested with imploding an array)

- [:negative_squared_cross_mark:] **in_array**

- [:heavy_check_mark:] **integer**

- [:heavy_check_mark:] **ip**
> (both IPv4 & IPv6)

- [:heavy_check_mark:] **ipv4**

- [:heavy_check_mark:] **ipv6**

- [:heavy_exclamation_mark:] **json**
> (Requires extensive testing)

- [:heavy_exclamation_mark:] **max**
> (Strings & Numeric works fine not tested on arrays & files)

- [:negative_squared_cross_mark:] **mimetypes**

- [:negative_squared_cross_mark:] **mimes**

- [:heavy_exclamation_mark:] **min**
> (Strings & Numeric works fine Not tested on arrays & files)

- [:heavy_check_mark:] **nullable**

- [:heavy_exclamation_mark:] **not_in**
> ( works fine with
`'test' => 'not_in:abc,xyz'`
> not tested with imploding an array)

- [:heavy_check_mark:] **numeric**

- [:heavy_exclamation_mark:] **present**
> (Usage undefined for the front end validation, expected usage is for back end validation)

- [:heavy_check_mark:] **regex**

- [:heavy_exclamation_mark:] **required**
> (works fine on Strings & Numeric Not tested with value is an empty array or empty Countable object, > The value is an uploaded file with no path.)

- [:heavy_check_mark:] **required_if**

- [:heavy_check_mark:] **required_unless**

- [:heavy_check_mark:] **required_with**

- [:heavy_check_mark:] **required_with_all**

- [:heavy_check_mark:] **required_without**

- [:heavy_check_mark:] **required_without_all**

- [:heavy_exclamation_mark:] **same**
> (Works fine if field 'test' has an input & field 'test2' is left empty or not match but submits the form
> when field 'test' is empty but field 'test2' has input the rule is as follows:
`'test' => 'same:test2'`
 > it requires the rule 'required' on 'test' to work as expected)

- [:heavy_exclamation_mark:] **size**
> (Strings & Numeric works fine not tested on arrays & files)

- [:heavy_check_mark:] **string**

- [:heavy_check_mark:] **timezone**

- [:heavy_check_mark:] **unique**
> (works with
`'test' => 'unique:users,uname'`
> not tested with 
`unique:table,column,except,idColumn`
> &
`'email' => 'unique:connection.users,email_address'` 
> & Forcing A Unique Rule To Ignore A Given ID & Adding Additional Where Clauses)

- [:heavy_check_mark:] **url**

___________________
Validating Arrays
___________________

- [:heavy_check_mark:] **test.foo**

- [:x:] **test.***
> (No rule generated in JS)

- [:x:] **test.*.foo**
> (No rule generated in JS)


#### Note:

- Some rules are submitting the form when a secondary field is required by the rule but not present on the page e.g 'confirmed,different'
 - Package not tested with "Conditionally Added Rules"
- Package not tested with "Custom Validation Rules"

**Comment by a-komarev** [comment]
@akkhan20 huge work! Thanks a lot. This is a roadmap.

**Comment by akkhan20** [comment]
will update the untested, conditionally added and custom rules by tomorrow

**Comment by kyranb** [comment]
Thanks so much for updating this 🔥

**Comment by madamGwapa** [comment]
![image](https://user-images.githubusercontent.com/20568595/28200600-b5da1780-689f-11e7-9922-c3af538aaced.png)
it automatically submits the data on my form

**Comment by akkhan20** [comment]
@madamGwapa what rule is doing that?

**Comment by madamGwapa** [comment]
@akkhan20 i'm having a custom validation though...i removed the validation and it was solved...

**Comment by akkhan20** [comment]
custom validations are most likely supposed to validate remotely
