### ISSUE TITLE
form not submitted with unique rule

### ISSUE THREAD

**Issue by meltzow** [proengsoft/laravel-jsvalidation#267]
we use a unique validator (also validation with ajax) in laravel 5.4 but the form can't submited after the validation is done successfully. If I disable this rules its working. we use validation with FormRequest.

any ideas?

**Comment by a-komarev** [comment]
This issue seems to be the more required by community: #138 #142 #176 #162 #164

**Comment by a-komarev** [comment]
@torrentalle wrote that it's implemented in `dev-master`, but I'm not sure about it. Hope he can answer on this question.

**Comment by akkhan20** [comment]
try 'exists' rule if it works or not

**Comment by meltzow** [comment]
hi, I am at dev-master. exists rule doesn't work here.

**Comment by akkhan20** [comment]
can u confirm if the JS is being generated for the rule?

**Comment by a-komarev** [comment]
@meltzow thanks for the test.

**Comment by a-komarev** [comment]
@meltzow here @danilodelacruz posted (solution for unique rule usage)[https://github.com/proengsoft/laravel-jsvalidation/issues/164#issuecomment-314355677]

**Comment by a-komarev** [comment]
Closing it since solution was found and confirmed as working.
