### ISSUE TITLE
Image dimensions supported?

### ISSUE THREAD

**Issue by njbarrett** [proengsoft/laravel-jsvalidation#268]
Does this plugin support validation of image dimensions?

I tried this validation:

`
'avatar_image' => 'image|mimes:jpeg,png|dimensions:min_width=140,min_height=140,ratio:1,max_width=500,max_height=500',`

and it does not seem to work.

**Comment by a-komarev** [comment]
Here is a list made by @akkhan20 with [all validation rules test results](https://github.com/proengsoft/laravel-jsvalidation/issues/265#issuecomment-314862954).

**Comment by a-komarev** [comment]
@njbarrett What Laravel version are you using? What package version are you using?

**Comment by akkhan20** [comment]
i believe for images you can only check file size, extension and mime-type. Dimensions are not supported by the [plugin](https://jqueryvalidation.org) used in this package to validate frontend elements

**Comment by njbarrett** [comment]
Ok, thanks @akkhan20
