### ISSUE TITLE
Class jsvalidator does not exist

### ISSUE THREAD

**Issue by kapilprabhudessai** [proengsoft/laravel-jsvalidation#269]
there is no class called jsvalidator in the project.
the facede has the code 
    protected static function getFacadeAccessor()
    {
        return 'jsvalidator';
    }

**Comment by a-komarev** [comment]
Hello @kapilprabhudessai What version of Laravel are you using? What version of Package are you using?

**Comment by a-komarev** [comment]
Here is a singleton registering on this name: https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/JsValidationServiceProvider.php#L31
