### ISSUE TITLE
How can i change the default validation message ?

### ISSUE THREAD

**Issue by AmirAmin** [proengsoft/laravel-jsvalidation#27]
Hello,

First of all, You have done a great job.

Right now i am validating a filed with name/id "desc", but i don't want to the message like this "The desc field is required." .
So, How can i change the default validation message ? either to be "The description field is required." or at least "This field is required." ?

Note: The validation.required expecting passing a variable :attribute so when i try to remove this variable the code crashes.

Regards,
Amir

**Comment by torrentalle** [comment]
Try it in `master` branch

**Comment by torrentalle** [comment]
I can't reproduce this issue. Can you post the rules and translations that are you using?

**Comment by torrentalle** [comment]
Try with the latest release if your issue is solved

**Comment by cerw** [comment]
Hello

I am having same issue, some of the field have "validation.required" under and not sure how to change that?
I am using latest version.

**Comment by torrentalle** [comment]
fixed in `dev-master`
