### ISSUE TITLE
Using with CKEditor plugin

### ISSUE THREAD

**Issue by garbinmarcelo** [proengsoft/laravel-jsvalidation#271]
Hello, 
I'm using the CKEditor (https://ckeditor.com/) plugin for texts. 
The validation via Request without the Laravel JS-Validation plugin happens, but with it active it ends up happening without being validated.

Could someone help me how could I do this validation?

**Comment by anmolsurmountsoft** [comment]
i have same problem can you help  me out?

i have text area which is replaced by Ckeditor plugin now laravel js validation plugin does not validating it ?

**Comment by anmolsurmountsoft** [comment]
@marcelogarbin  thanks for reply i think it's not possible right?

**Comment by marcelogarbin** [comment]
@anmolsurmountsoft I can't confirm this, I am still waiting for a response from the creators/maintainers of the laravel-jsvalidation package.

**Comment by julles** [comment]
i have same problem

**Comment by dhsont** [comment]
if we can pass 
```
ignore: [],
````
to jsvalidator it will validate ck editor also

**Comment by marcelogarbin** [comment]
today I came across this again =/

**Comment by marcelogarbin** [comment]
Any tips on how to validate the CKEditor4 field?

**Comment by marcelogarbin** [comment]
@anmolsurmountsoft Can you do some form of validation for CKEditor?

**Comment by garbinmarcelo** [comment]
How do I manually call the field validation function? Could anyone help?

**Comment by garbinmarcelo** [comment]
I managed to modify the js script and add a new one. However, I don't know how I could integrate this modification into this package. I also have doubts about the use of ignore which opened an issue(https://github.com/proengsoft/laravel-jsvalidation/issues/416).

![modo](https://user-images.githubusercontent.com/9335588/76640436-ae932000-652e-11ea-88bd-554e0024f9fd.gif)

**Comment by bytestream** [comment]
The solution mentioned in https://github.com/proengsoft/laravel-jsvalidation/issues/271#issuecomment-388600490 is correct.

jquery-validate has a default ignore value of `:hidden` and nearly all wysiwyg editors hide their input element. So you need to modify the `ignore` param

**Comment by krit0627** [comment]
This same problem for me.

Example config jquery validate with ckeditor.

http://jsfiddle.net/rohanppatil/BmZ93/8/

but not working in laravel-jsvalidation
