### ISSUE TITLE
Bootstrap 4-Beta class changes in the bootstrap.php

### ISSUE THREAD

**Issue by dercodercom** [proengsoft/laravel-jsvalidation#272]
**From**
`$(element).closest('.form-group').removeClass('has-success').addClass('has-danger'); `

**To**
`$(element).closest('.form-control').removeClass('is-valid').addClass('is-invalid');`

see [https://getbootstrap.com/docs/4.0/components/forms/#validation](https://getbootstrap.com/docs/4.0/components/forms/#validation)

**Comment by a-komarev** [comment]
Related to: #306, #321
