### ISSUE TITLE
laravel-jsvalidation with Ajax and uniquewith-validator

### ISSUE THREAD

**Issue by garbinmarcelo** [proengsoft/laravel-jsvalidation#275]
Hello,
I'm using the uniquewith-validator(https://github.com/felixkiss/uniquewith-validator) package together with laravel-jsvalidation and triggering the form via Ajax(http://malsup.com/jquery/form/#ajaxForm).

When I use both, when submitting the registration form it works normally. However when triggering the registration update form it is duplicating data of the file type.

I ran several tests, and then I found this error in the request using the uniquewith-validator package with laravel-jsvalidation.

I don't know if Laravel itself offers a multi-field validation feature with unique. I accept suggestions.

my code:
```
public function rules()
    {
        $id = (Hashids::decode($this->publicacao))? Hashids::decode($this->publicacao)[0] : 'NULL';
        return [
            'id_situacao'       => 'required',
            'id_categoria'      => 'required',
            'numero'            => 'required|max:10|unique_with:table,numero,id_categoria,'.$id,
            'titulo'            => 'required|max:255|unique_with:table,titulo,numero,id_categoria,'.$id,
            'data_abertura'     => 'nullable|date_format:d/m/Y H:i',
            'data_encerramento' => 'nullable|date_format:d/m/Y H:i|after_or_equal:data_abertura',
        ];
    }

    public function messages()
    {
        return [
            'numero.unique_with' => 'Número já existe nessa Categoria',
            'titulo.unique_with' => 'Título já existe nessa Categoria e Número',
        ];
    }
```

**Comment by marcelogarbin** [comment]
Today I came across the same error = /

Is there any way to check if js-validation is making a request via ajax?

What I thought was to verify that it is being a single field verification, and to allow the form to be sent only after it has been completed and validated.

**Comment by marcelogarbin** [comment]
I have this code inside ajaxForm:

```javascript
 beforeSubmit: function(){
            if($form.valid()){
                $("#carregando").fadeIn(1000);
                $("#info-progress").fadeIn(1000);
                return true;
            }
            return false;
        },
```
In this case, check if the form is valid.
However in my Request I have the following rule:
`'titulo'                 => 'required|max:255|unique:informativo_audios,titulo,'.$id,`

In this case, mine if I type something in the field and click the submit before the return of the "unique" rule, the form will be sent. This is occurring error.
![delay_validation](https://user-images.githubusercontent.com/9335588/41445784-4afd275a-7022-11e8-81d7-d4fe8eb6816d.gif)

Note that to a delay due to the ajax request, between this delay I can click the submit button and the form is sent as valid, but it is invalid.

Would there be any way to wait for this delay when using the "unique" rule? @a-komarev  Would you help me?

**Comment by a-komarev** [comment]
I think you need to add some internal logic to block submit button before response will be received. But this could lead to some unexpected behavior, when connection was lost, response wasn't received and after connection resume submit button will be still disabled.

**Comment by jawadsahil** [comment]
> Would there be any way to wait for this delay when using the "unique" rule? @a-komarev Would you help me?

I had same issue and I did this:

    var form = this;
     //.....
     if ($.active > 0) {
	  event.preventDefault();
          setTimeout(function () {
              form.submit();
          }, 300);
          return false;
      }

      return true;

**Comment by bytestream** [comment]
You can detect AJAX requests in the submit handler using;
```js
            submitHandler: function (form) {
                $(form).find(':submit').prop('disabled', true);

                // Validate the form.
                if (validator.form()) {
                    // Handle remote validation rules.
                    if (validator.pendingRequest) {
                        validator.formSubmitted = true;
                        return false;
                    }

                    // Submit the form (will cause the page to refresh etc).
                    form.submit();
                } else {
                    $(form).find(':submit').prop('disabled', false);
                    validator.focusInvalid();
                    return false;
                }
            },

            focusInvalid: true,

            invalidHandler: function(event, validator) {
                // Enable submit button again (necessary for invalid remote validation).
                $(this).find(':submit').prop('disabled', false);

                if (!validator.numberOfInvalids())
                    return;
            }
```

This disables the submit button wihle the AJAX runs, if successful submits the form, and if unsuccessful re-enables the submit button and focuses the invalid inputs.
