### ISSUE TITLE
Wrong tag name 2.1.0

### ISSUE THREAD

**Issue by Omranic** [proengsoft/laravel-jsvalidation#278]
Should be **v**2.1.0 trivial, but needed for consistency 🙂 
![screenshot 2017-08-31 00 30 23](https://user-images.githubusercontent.com/406705/29897932-9c240f76-8de3-11e7-92cb-3a54d7b26242.png)

**Comment by a-komarev** [comment]
@Omranic you are totally right, thanks for pointing this out. Made new tag and removed old one.
