### ISSUE TITLE
jQuery Repeater Validation Issue

### ISSUE THREAD

**Issue by jhayiwg** [proengsoft/laravel-jsvalidation#279]
Hello,

First, thanks for this package.

My application uses this validation and I am also using jQuery Repeater to duplicate inputs.

The problem is that in the repeatable fields it is not working.

Any advice!

-Jhay-ar

**Comment by ilyaskazi** [comment]
almost an year.. m bumping into this issue as faced the same on using jquery repeater plugin. It needs to support validation on these fields as now it is too common everyone using repeater plugin.

**Comment by marcelogarbin** [comment]
2020 :raised_hands: did you get any solution? @jhayiwg @ilyaskazi

**Comment by bytestream** [comment]
jQuery validation plugin doesn't support the same element defined multiple times. This is an issue upstream https://github.com/jquery-validation/jquery-validation/pull/717
