### ISSUE TITLE
Unique parameter...

### ISSUE THREAD

**Issue by Zhenjas** [proengsoft/laravel-jsvalidation#28]
Hello!
How can I use unique parameter for check email or username in DB?

Thanks

**Comment by minkbear** [comment]
I am facing this problem as well. please

**Comment by torrentalle** [comment]
I'm working in this enhacement. It will be ready shortly

**Comment by seanthepottingshed** [comment]
Fantastic package **torrentalle**, really easy to implement particulary using *Form Requests*. Looking forward to unique parameter support, that would be the icing on the cake!

Keep up the good work ;)

**Comment by torrentalle** [comment]
This feature is implemented in `master` branch.
Shortly I will release new version
