### ISSUE TITLE
POST request actually sent as PUT?

### ISSUE THREAD

**Issue by bert-w** [proengsoft/laravel-jsvalidation#283]
So I basically moved to a new webhost, with the same codebase. However, now a simple

```
<form method="POST" ...>
<input type="hidden" name="_method" value="PUT"/>
</form>
```

is being sent as a PUT request (which i see in the browser debug window). This breaks my laravel implementation since it throws 405 Method Not Allowed. Anyone got a clue why this happens? I disabled the implementation for now, and I dont know what's causing it.

**Comment by a-komarev** [comment]
@bert-w I suppose that [`_method` spoofing](https://laravel.com/docs/5.5/routing#form-method-spoofing) is not related to this library.

**Comment by bert-w** [comment]
issue can be closed, it was a javascript issue which for some reason behaved differently on another webserver

**Comment by a-komarev** [comment]
@bert-w you can close your own issues
