### ISSUE TITLE
Get ajax request for validation "unique"

### ISSUE THREAD

**Issue by garbinmarcelo** [proengsoft/laravel-jsvalidation#285]
Hello,
I would like another help with form validation verification. It turns out that I'm using "unique" validation, in my case when I click to send in a certain time the form is validated before even checking the "unique" condition.

I would like some help on this, my idea is to make a call to change button status only after the validation is true. In a way it's working, but not how I really like it.
The form is not sent, however the button style is changed anyway.

![btn_status](https://user-images.githubusercontent.com/9335588/30756910-e8606d46-9fa2-11e7-93dd-8d3c7f332b8f.gif)

Code btn js:
```
$(document).ready(function() {
        $(".btn-submit").click(function() {
            let $btn     = $(this);
            let $btn_txt = $btn.text();
            let $form    = $btn.parents('form');
            // check if the input is valid
            if($form.valid()){
                $form.submit(function(event) {
                    // disable btn and change text
                    $btn.prop('disabled', true);
                    $btn.html('<i class="fa fa-circle-o-notch fa-spin"></i> Aguarde...');
                    // return original btn
                    setTimeout(function () {
                        $btn.prop('disabled', false);
                        $btn.html($btn_txt);
                    }, 8000);
                });
            }
        });
    });
```

Can anybody help me?

thank you

**Comment by a-komarev** [comment]
Try to prevent autovalidation in `resources/views/vendor/jsvalidation/bootstrap.php` file:
```php
$("<?= $validator['selector'] ?>").validate({
            onkeyup: false,
            onclick: false,

            // Other code
});

**Comment by a-komarev** [comment]
If this wouldn't help you can add this code at the end of the script:

```js
jQuery.validator.defaults.onfocusout = function (element, event) {
        // detectect if is the element you dont want validate
        // the element has to have the attribute 'data-validate="live"'
        // you can also identify your element as you please
        if ($(element).data('validate') !== 'live') return;
        if (!this.checkable(element) && (element.name in this.submitted || !this.optional(element))) {
            this.element(element);
        }
    };
    jQuery.validator.defaults.onkeyup = function (element, event) {
        // detectect if is the element you dont want validate
        // the element has to have the attribute 'data-validate="live"'
        // you can also identify your element as you please
        if ($(element).data('validate') !== 'live') return;
        if (event.which === 9 && this.elementValue(element) === '') {
            return;
        }
        else if (element.name in this.submitted || element === this.lastElement) {
            this.element(element);
        }
    };
```

**Comment by marcelogarbin** [comment]
@a-komarev Thanks for the willingness to help. But it still has not worked, it is not yet entering the rule "`if ($ form.valid ())`" when using validation with "unique".
![btn_status](https://user-images.githubusercontent.com/9335588/30773642-f1b899ce-a04a-11e7-8a30-ce6403bfd6e3.gif)

I would like the button not to be modified as long as the form was not valid, but since "unique" validation requests ajax, I think I'm wasting my time to check whether or not it's valid in the JS code I put earlier in this post.

![btn_status](https://user-images.githubusercontent.com/9335588/30773671-6c812cb6-a04b-11e7-9e62-c011b60cd9d2.gif)

The correct would be as above, when there is no content (false valid form) the contents of the button becomes static, it does not change.

Do not you use this in your projects?

I do not know if I did something wrong, I tried many things, but without success. I make this button lock so that the user can not click multiple times and send multiple requests to the server.

**Comment by a-komarev** [comment]
I've disabled all the realtime validations and doing them only after the click submit button.

**Comment by marcelogarbin** [comment]
How did you do? could you show an example?

**Comment by a-komarev** [comment]
In `bootstrap.php` file I've added this code before `</script>`: https://github.com/proengsoft/laravel-jsvalidation/issues/285#issuecomment-331526261
And disabled validation on `keyup` and `onclick` in the same file: https://github.com/proengsoft/laravel-jsvalidation/issues/285#issuecomment-331525874

I've got custom solutions in my code, so I'm not sure that complete example would be useful. If you need to customize validation process you should search solution on the [official jquery validation website](https://jqueryvalidation.org/) on their github repository.

**Comment by marcelogarbin** [comment]
Hello, after a while I came back on the same issue.

Would there be any way to only submit submit if all ajax calls are already completed?

I ask this, as I have a form problem, if I make a quick register where a field uses the "unique" rule, it is validated as correct (even though it is wrong) and the form is sent, after that a exception due to call in Ajax.

**Comment by marcelogarbin** [comment]
> Hello, after a while I came back on the same issue.
> 
> Would there be any way to only submit submit if all ajax calls are already completed?
> 
> I ask this, as I have a form problem, if I make a quick register where a field uses the "unique" rule, it is validated as correct (even though it is wrong) and the form is sent, after that a exception due to call in Ajax.

https://github.com/proengsoft/laravel-jsvalidation/issues/406

**Comment by bytestream** [comment]
You need to use a combination of `submitHandler` and `invalidHandler` to achieve this:

```js
            submitHandler: function (form) {
                $(form).find(':submit').prop('disabled', true);

                // Validate the form.
                if (validator.form()) {
                    // Handle remote validation rules.
                    if (validator.pendingRequest) {
                        validator.formSubmitted = true;
                        return false;
                    }

                    // Submit the form (will cause the page to refresh etc).
                    form.submit();
                } else {
                    $(form).find(':submit').prop('disabled', false);
                    validator.focusInvalid();
                    return false;
                }
            },

            invalidHandler: function(event, validator) {
                // Enable submit button again (necessary for invalid remote validation).
                $(this).find(':submit').prop('disabled', false);
```

Please refer to https://jqueryvalidation.org/documentation/ for the full set of options that are available.
