### ISSUE TITLE
min and max condition not working correctly for integer

### ISSUE THREAD

**Issue by ajithmohan** [proengsoft/laravel-jsvalidation#29]
public function rules()
	{
		return [
			'name' => 'required|min:2|max:1000',
            'base_occupancy' => 'required|integer|min:0|max:100',
            'max_occupancy' => 'required|integer|min:0|max:100'
		];
	}

even if i give values between 0&100, its showing error

**Comment by torrentalle** [comment]
This bug is fixed in `master` branch
