### ISSUE TITLE
Cannot set property 'classRuleSettings' of undefined

### ISSUE THREAD

**Issue by Tarasovych** [proengsoft/laravel-jsvalidation#300]
I'm using Laravel 5.5.28, I set up package according to [this topic](https://github.com/proengsoft/laravel-jsvalidation/wiki/Laravel-5.4-installation).
On my page where I have only one form I put this
```
<!-- Scripts -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>

<!-- Laravel Javascript Validation -->
<script type="text/javascript" src="{{ url('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
```
on the bottom of the page (just to make sure scripts are loaded correctly).

And I get an error
```
Uncaught TypeError: Cannot set property 'classRuleSettings' of undefined
    at Object.init (jsvalidation.js? [sm]:21)
    at HTMLDocument.<anonymous> (jsvalidation.js? [sm]:242)
    at j (jquery.js:3094)
    at Object.fireWith [as resolveWith] (jquery.js:3206)
    at Function.ready (jquery.js:3412)
    at HTMLDocument.I (jquery.js:3428)
```
I tried to put scripts in `<head></head>`. Also I reied to republish
`php artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider" --tag="public" --force`. Nothing helped.
What to do?

**Comment by Tarasovych** [comment]
@Himhotep Sorry, I'm not using this package yet. I've solved that problem but I can't remind now...

**Comment by Doomkyn** [comment]
@Himhotep get rid of the following line in the ` \views\layouts\app.blade.php` file:
`<script src="{{ asset('js/app.js') }}" defer></script>`

**Comment by dbrw** [comment]
> @Himhotep get rid of the following line in the ` \views\layouts\app.blade.php` file:
> `<script src="{{ asset('js/app.js') }}" defer></script>`

I think you might want to just delete `defer` then move that line after `</body>`.

**Comment by cp-vrkansagara** [comment]
yes @dbrw  is right because this library having some dependencies on  `app.js`  so it must be loaded into dom first.
