### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by neflictus** [proengsoft/laravel-jsvalidation#304]
Method Proengsoft\JsValidation\Javascript\JavascriptValidator::__toString() must not throw an exception, caught TypeError: Argument 5 passed to Symfony\Component\HttpFoundation\File\UploadedFile::__construct() must be of the type integer or null, string given, called in E:\http\dgaspc\vendor\proengsoft\laravel-jsvalidation\src\Javascript\MessageParser.php on line 106

Request:
'avatar' => 'sometimes|mimes:jpeg,png,jpg,gif,svg|max:1024',

**Comment by a-komarev** [comment]
@neflictus could you write a test for this case, please?

**Comment by neflictus** [comment]
namespace Symfony\Component\HttpFoundation\File;
public function __construct(string $path, string $originalName, string $mimeType = null, int $size = null, int $error = null, bool $test = false)

JsValidate
MessageParser.php

    protected function createUploadedFile()
    {
        return new UploadedFile('fakefile', 'fakefile', null, null, 'fakefile', true);
    }

5th Param.

**Comment by a-komarev** [comment]
@neflictus could you confirm that fix from @Marcuzz resolves this issue? You should update to [v2.2.1](https://github.com/proengsoft/laravel-jsvalidation/releases/tag/2.2.1).

**Comment by neflictus** [comment]
Sorry. I was using a fork. Tried it today. Awesome work.

**Comment by a-komarev** [comment]
Thank you for the confirmation, @neflictus!
