### ISSUE TITLE
Composer install with Laravel 5.6

### ISSUE THREAD

**Issue by chienit2k** [proengsoft/laravel-jsvalidation#305]
![image](https://user-images.githubusercontent.com/32790030/36304242-89e46070-1341-11e8-8aa2-cb6f570310be.png)

help me !

**Comment by a-komarev** [comment]
Try to update `proengsoft/laravel-jsvalidation` in your composer.json. Could you show you definition?

I suppose you have `"proengsoft/laravel-jsvalidation": "2.1.*"` now.
If yes, change it to `"proengsoft/laravel-jsvalidation": "^2.1"`.

**Comment by a-komarev** [comment]
I think this issue is resolved and should be closed. If you still have problems with upgrade process - feel free to continue conversation here or open a new issue.
