### ISSUE TITLE
Laravel 5.5.28 and Bootstrap 4

### ISSUE THREAD

**Issue by Tarasovych** [proengsoft/laravel-jsvalidation#306]
Hello! I'm using Laravel 5.5.28 and Bootstrap 4. Because of Bootstrap 4 has different `css` logic to show errors, my inputs aren't getting red border if error, also `span` error text is black not red. Is it possible to use `2.1.0` version with Bootstrap 4 in any way?

**Comment by Tarasovych** [comment]
@digvijayad take a look on [bootstap docs](https://getbootstrap.com/docs/4.0/components/forms/#server-side). Now `is-invalid` class is used to show errors.

**Comment by digvijayad** [comment]
I got that,  but how do I have the Validator add the `is-invalid` class instead of `error-help-block` and `has-error`

**Comment by a-komarev** [comment]
@digvijayad change it in `resources/views/vendor/jsvalidation/bootstrap.php` file in a `highlight` function.

**Comment by digvijayad** [comment]
@a-komarev Thanks didn't notice the cheeky vendor folder inside the views.
