### ISSUE TITLE
Focus on errors when form is validated

### ISSUE THREAD

**Issue by samuelfa** [proengsoft/laravel-jsvalidation#31]
Hello:

I fork your repository to add a new feature in your component:

When We are validating the form I want to move the view to the first error and set the focus on the first component on my form.

I added two new parameters on the config to active or not this feature and to control the time of the animate to move the scroll.

PD: I created a pull requet at https://github.com/proengsoft/laravel-jsvalidation/pull/32

Thank you
Samuel

**Comment by torrentalle** [comment]
Thank's a lot.
