### ISSUE TITLE
How to use Custom Rule Messages?

### ISSUE THREAD

**Issue by magnosis** [proengsoft/laravel-jsvalidation#313]
JsValidator fails at getting my **Custom Rule** messages through a **FormRequest**

I have this rule:
```php
use Illuminate\Contracts\Validation\Rule;

class MyRule implements Rule 
{
    public function passes($attribute, $value) {
        return $value > 10;
    }
    public function message() {
        return 'Your :attribute is pretty small, dawg!';
    }
}
```

My form request uses this rule:
```php
use Illuminate\Foundation\Http\FormRequest;
use App\Rules\MyRule;

class MyRequest extends FormRequest 
{
    public function authorize() {
        return true;
    }
    public function rules() {
        $rules = [
            'foo' => 'required|numeric',
            'bar' => ['required', new MyRule()],
        ];
        return $rules;
    }
}
```

This should work, but I get thrown an Exception on
```php
{!! JsValidator::formRequest('\App\Http\Requests\MyRequest') !!}
```
and it seems to be caused by `Proengsoft\JsValidation\Javascript\MessageParser.php` which does not look at the rule type (string vs Object) before calling `Illuminate\\Validation\\Validator->getMessage($attribute, $rule);`

Can I make this work without a pull request or modifying JsValidation src?

**Comment by dfoxxdfoxx** [comment]
Any update on this?

**Comment by Braunson** [comment]
Same issue here with custom rules.. hmm

**Comment by a-komarev** [comment]
@magnosis @dfoxxdfoxx fix made by @Braunson was merged to `dev-master`. It will be great if you had a chance to test it on your projects. If there is no new issues introduced I will make a release with it.

**Comment by antonkomarev** [comment]
Sorry for the long delay. Released as part of the [v2.3.0](https://github.com/proengsoft/laravel-jsvalidation/releases/tag/2.3.0).

**Comment by magnosis** [comment]
Absolutely fantastic! Works like a charm (just tested on 2.3.2).

To be clear - __toString still required to be defined in custom Rule, and that's okay.

Thanks + apologies for the suuuuper long delay.

**Comment by mdmahbubhelal** [comment]
This should be on the readme. I had spent an hour before I stumbled upon this issue.

**Comment by kamkyi** [comment]
> @magnosis @proengsoft @dfoxxdfoxx
> 
> Ok I think I've found a solution (there's probably a better one but this works). I've put in a PR to solve the issue.
> 
> In addition to this PR fix, for custom rules, another error will be thrown by Illuminate's `ValidationRulesParser.php` about expecting a array not an object. The solution to this is to define the `__toString` in your custom rule, the returned string should be your rule name.
> 
> ```
> public function __toString()
> {
>     return 'USPhoneNumber';
> }
> ```

Can you show the complete codes with added "__toString()" method. I am still struggling on putting __toString

**Comment by Braunson** [comment]
@kamkyi So this is my example, with code removed but so you get the idea:

**app\Rules\USPhoneNumber.php**:

```php
<?php

namespace App\Rules;

use Validator;
use Illuminate\Contracts\Validation\Rule;

class USPhoneNumber implements Rule
{
    public function __toString()
    {
      return 'USPhoneNumber';
    }

    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        // Do some logic
        return true;
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'This field contains an invalid phone number.';
    }
}
```
