### ISSUE TITLE
Ajax Initialization of Plugin

### ISSUE THREAD

**Issue by Braunson** [proengsoft/laravel-jsvalidation#322]
### Use-case

Form HTML is loaded in with an ajax call. The Laravel-JSValidator PHP/blade snippet is included in that returned HTML, how can we initialize the form validation after the ajax call is complete. As far as I know the plugin uses `document ready` and that's already triggered before the ajax call is even made.

Thoughts? I know this is a very specific use-case. Perhaps I can extend the response somehow to replace the document ready and instead as a function that is called on load/insert of the HTML?

**Comment by a-komarev** [comment]
You could make changes in `resources/views/vendor/jsvalidation/bootstrap.php` file and make initialization not after page load, but when your application will be ready to initialize javascript validator.

**Comment by Braunson** [comment]
I entirely forgot about that file, th anks!

**Comment by trueWD** [comment]
This problem appeared in laravel 5.8
