### ISSUE TITLE
Password Confirmed

### ISSUE THREAD

**Issue by Lydon** [proengsoft/laravel-jsvalidation#33]
The <b>confirmed</b> field for password shows that the passwords (<b>password</b> and <b>password_confirmation</b>) do not match. The rules are set as follows:

<pre>
public function rules()
{
    return [
			'username' => 'required|min:5|max:50|unique:users',
            'email'  => 'required|email|unique:users',
            'password' => 'required|min:8|confirmed',
            'password_confirmation' => ' 'required|min:8',
            'g-recaptcha-response' => 'required|recaptcha',
        ];
}
</pre>

My Laravel Version is <b>5.1</b>

**Comment by yazfield** [comment]
you don't need 'password_confirmation' => ' 'required|min:8' when you use 'confirmed' at the password, this might be confusing the validator, remove if and try.

**Comment by Lydon** [comment]
@yazfield Thanks it actually worked!
