### ISSUE TITLE
Array validation misapplied

### ISSUE THREAD

**Issue by bytestream** [proengsoft/laravel-jsvalidation#333]
Laravel: 5.5.40
jsvalidation: latest

Support to validate array fields using non array rules was added in https://github.com/proengsoft/laravel-jsvalidation/commit/4bf612a63f04ac62f658cc56e011df73cfb6345e under https://github.com/proengsoft/laravel-jsvalidation/pull/206

I have inputs such as:
`<input name="emails[0][id]" type="hidden" value="">`
`<input size="30" name="emails[0][address]" type="email" value="" id="emails[0][address]">`

Which is validated with:
`'emails'                     => 'required_if:parent,0|nullable|array'`
````php
$emailRules = [];
foreach ($this->request->get('emails', []) as $k => $v) {
    $emailRules["emails.$k.address"] = 'required_if:parent,0|nullable|email';
````

The `emails` rule is getting applied to both elements above, because of https://github.com/proengsoft/laravel-jsvalidation/blob/00c0fadb8a04cf9e274b42e9eb9286c73ac6b69d/resources/assets/js/helpers.js#L352 which produces: `^emails\[.*\]$` and matches both of the above elements.

I don't expect the `emails` rule to be applied to all children. I suspect, it's a special case as it was introduced to cater for: https://github.com/proengsoft/laravel-jsvalidation/issues/180. With this in mind, the regex should be 
````js
return new RegExp('^'+regexpParts.join('[^\\]]*')+'$');
````
 so it only matches single dimensional arrays. At the moment the greedy quantifier means it's matching `[0][id]`

**Comment by maganius** [comment]
I have the same issue the form request array does not appear on javascript code it's empty and the fixes don't work for me. im using laravel 5.5.4

**Comment by bytestream** [comment]
@maganius please provide a test case, the fix works fine for the case I wrote above

**Comment by maganius** [comment]
I have selects such as:
`<select class="form-control" id="service_type" name="services[0][service_type]">`

In the FormRequest validator

`public function rules()
    {
        return [
            'port' => 'required',
            'services.*.service_type' => 'required|array',
            'services.*.subservice_type' => 'required|array',
        ];
    }
`

I tried change the RegExp and 
the JsValidatorFactory.php where this replace * for # <- with this in the js validator appear the rule but it no validate the selects. #298 

The first select is static but I have a button to add more select dynamically
