### ISSUE TITLE
Multiple forms with same selector

### ISSUE THREAD

**Issue by leonardoldr23** [proengsoft/laravel-jsvalidation#336]
I need a fix to allow a generic validation through multiple forms with same selectors.

suggested patch attached in zip format.
[laravel-jsvalidation.zip](https://github.com/proengsoft/laravel-jsvalidation/files/2202898/laravel-jsvalidation.zip)

**Comment by antonkomarev** [comment]
@leonardodarosa23 thank you for the contribution! Pull Requests are welcomed to keep contributors authorship.

**Comment by leonardodarosa23** [comment]
No problem, I really don't need the authorship. I use it on my personagem project and I really need this feature to be on. :)

**Comment by antonkomarev** [comment]
This feature was released in v2.3.0
