### ISSUE TITLE
The form input not remove error class when input correct data

### ISSUE THREAD

**Issue by henryonsoftware** [proengsoft/laravel-jsvalidation#343]
When I type wrong data to input form, it shows the error red form. After that I re-type correct data but it does not remove the red error. I think this is the bug because I see this code in **bootstrap4.php**

`$(element).closest('.form.control').removeClass('is-valid').addClass('is-invalid'); // add the Bootstrap error class to the control group`

Of course I edited it to:

`$(element).closest('.form-control').removeClass('is-valid').addClass('is-invalid'); // add the Bootstrap error class to the control group`

as I reported in https://github.com/proengsoft/laravel-jsvalidation/issues/342. But it still don't remove error class.

Any help to fix this bug?

**Comment by o7n** [comment]
Uncommenting the `unhighlight` function (just below "Uncomment this to mark as validated non required fields") appears to fix this issue. 

I don't know if this behaviour is intended but at least that comment above it is really misleading.

**Comment by henryonsoftware** [comment]
Great!
I uncommented the `unhighlight` function and edit the bootstrap class like as
```
unhighlight: function(element) {
    $(element).closest('.form-control').removeClass('is-invalid').addClass('is-valid');
},
```
and it's worked like a charm. Thanks @o7n
