### ISSUE TITLE
Update composer for Laravel 5.8

### ISSUE THREAD

**Issue by Braunson** [proengsoft/laravel-jsvalidation#372]
With Laravel 5.8 coming out tomorrow the package supports up to 5.7.* so it'll throw composer errors.

**Comment by Braunson** [comment]
Looks like there's a PR for this alerady https://github.com/proengsoft/laravel-jsvalidation/pull/373

**Comment by ofumbi** [comment]
Very little will change or break in the laravel 5.* series , why not just leave this open for laravel <6 ? will save everyone a tonne of time.

**Comment by gwleuverink** [comment]
Any idea when a new release will be tagged? I'm eager to upgrade

**Comment by modestguy** [comment]
waiting...

**Comment by mechelon** [comment]
Waiting as well.

**Comment by macagoraga** [comment]
still not yet done?

I am getting proengsoft/laravel-jsvalidation ^2.4.0 -> no matching package found.

**Comment by drjoju** [comment]
Anyone interested in to be administrator? I have been out of the project for 3 years. I give privileges to anyone interested.

**Comment by mathiasonea** [comment]
This is already supported, so the issue is getting closed.
