### ISSUE TITLE
after_or_equal / before_or_equal not working

### ISSUE THREAD

**Issue by Nuranto** [proengsoft/laravel-jsvalidation#378]
These rules seems to not be managed :
https://laravel.com/docs/5.8/validation#rule-after-or-equal
https://laravel.com/docs/5.8/validation#rule-before-or-equal

However, after and before seems to be managed 🤔

**Comment by Nuranto** [comment]
@bytestream 
Does not work with `today` keyword (`before_or_equal:today`). Probably with other keywords as well.
Error is : 
```
jsvalidation.js:1047 Uncaught TypeError: string.replace is not a function.  Exception occurred when checking element date_of_birth, check the 'laravelValidation' method.
```

Probably the problem occurs on Before/After too ?

**Comment by Nuranto** [comment]
Ugly fix to understand the issue : 

```
        compareDates: function (validator, value, element, params, operator) {

            var timeCompare = parseFloat(params);
            
+            if(params == 'today') {  //todo manage also tomorrow and other keywords.
+               timeCompare = Date.now();
+            } 
+
            if (isNaN(timeCompare)) {
                var target = this.dependentElement(validator, element, params);

```

**Comment by bytestream** [comment]
Please can you open a fresh issue for those?

**Comment by garbinmarcelo** [comment]
Hello, has this problem been resolved? How to make "after_or_equal" work? Thanks
