### ISSUE TITLE
Please make it support Laravel 5.8

### ISSUE THREAD

**Issue by trueWD** [proengsoft/laravel-jsvalidation#379]
I'm looking forward to the 5.8 version of this beautiful system. thank you

**Comment by Destinais** [comment]
It's perfectly working on Laravel 5.8

**Comment by OmathiasO** [comment]
As of the Release [2.4.0](https://github.com/proengsoft/laravel-jsvalidation/releases/tag/2.4.0) it's compatible with Laravel 5.8
