### ISSUE TITLE
File size is being treated as string size

### ISSUE THREAD

**Issue by mjfavaro** [proengsoft/laravel-jsvalidation#38]
File size is being treated as string size

When validates laravel
"The logo may not be greater than 100 kilobytes."

When validates javascript
"The logo may not be greater than 100 characters."

**Comment by torrentalle** [comment]
Can you post your validation rules?

**Comment by mjfavaro** [comment]
I'm using
Laravel 5.1
laravel-jsvalidation 1.0

My form request:
    public function rules()
    {
        return [
            'domain' => 'required|domain',
            'name' => 'required|max:255',
            'logo' => 'image|size:100',
        ];
    }

Congratulations for this package, is the best package :)

**Comment by torrentalle** [comment]
Thank's.
I found the bug. I will publish it shortly, I'm preparing new release

**Comment by torrentalle** [comment]
This bug is fixed in `master` branch
