### ISSUE TITLE
$js_validator->sometimes for array field such as bedroom.*.partners Not Working

### ISSUE THREAD

**Issue by avictory6** [proengsoft/laravel-jsvalidation#384]
Hello,
When using generics field name of array, this rule is not working in jsValidator. (But works on Laravel server side validation)
`$js_validator->sometimes('bedroom.*.partners',['required','enum_value:' . BedroomPartners::class . ',[strict]'], function ($request){
                return $request->bedrooms >= 3;
            });`

But if I loop for each index and create a different call to sometimes('bedroom.2.partners',...) for example, it works just fine in jsValidator.
Is it a feature that was not introduced yet on jsValidator? Or I do something wrong?

Thanks,
Avi

**Comment by MusaZhou** [comment]
I met this issue also, It seems that is due to the upgrading of laravel. While I was in laravel 5.8.17, it is working. after I upgrading to 5.8.29, validation on the server side failed

**Comment by peter44322** [comment]
the same here when I used the * (wildcard) the field just disappeared from the rules array

**Comment by OppPMatos** [comment]
Check this https://github.com/proengsoft/laravel-jsvalidation/issues/297#issuecomment-490545854

**Comment by bytestream** [comment]
Most likely duplicate as commented above.
