### ISSUE TITLE
Date after/before validation rules don't appear to be working.

### ISSUE THREAD

**Issue by haakym** [proengsoft/laravel-jsvalidation#39]
Here are my rules:

```
public function rules()
{
    return [
        'date_start' => 'date|date_format:d-m-Y|before:date_finish',
        'date_finish' => 'date|date_format:d-m-Y|after:date_start',
    ];
}
```

Outcomes from varying input:

1. Expected

Input
date_start: 10-10-2015
date_finish: 10-10-2016

Messages
date_start: "The date start must be a date before date finish."
date_finish: Nothing

2. Erroneous

Input
date_start: 10-10-2017
date_finish: 10-10-2016

Messages
date_start: "The date start must be a date before date finish."
date_finish: Nothing

3. Same

Input
date_start: 10-10-2016
date_finish: 10-10-2016

Messages
date_start: "The date start must be a date before date finish."
date_finish: Nothing

Please note I've tried with my rules like this

```
public function rules()
{
    return [
        'date_start' => 'before:date_finish',
        'date_finish' => 'after:date_start',
    ];
}
```

and this

```
public function rules()
{
    return [
        'date_start' => 'date|date_format:Y-m-d|before:date_finish',
        'date_finish' => 'date|date_format:Y-m-d|after:date_start',
    ];
}
```

Any guidance if I'm doing something wrong would be most appreciated! Excellent package btw, big thanks to the creator.

**Comment by torrentalle** [comment]
This bug is fixed in `master` branch

**Comment by thanosalexander** [comment]
any fix here? it seems not working

**Comment by bytestream** [comment]
@thanosalexander please open a new issue.

**Comment by thanosalexander** [comment]
ok @bytestream
