### ISSUE TITLE
Laravel 6 LTS Support

### ISSUE THREAD

**Issue by marcelogarbin** [proengsoft/laravel-jsvalidation#390]
Hello, today Laravel 6 LTS was released, will it be supported/updated for this version? Thank you

**Comment by marcelogarbin** [comment]
Hi @antonkomarev , thanks for the contact. I am not very experienced in this part of packages and collaboration with third party code. But I would be interested in helping.
My doubts in this part are:
- Where to start? (as far as I know, I do a fork of this project and then a pull and make changes, that?)
- How can I test the changes and make sure they are correct?
- How to check if composer will install correctly?
- Would you indicate any study material that involves this part of the collaboration?

Thank you for your attention

**Comment by antonkomarev** [comment]
@marcelogarbin here is [Contribution Guide](https://github.com/proengsoft/laravel-jsvalidation/wiki/Contributing) which is best point of start.

**Comment by antonkomarev** [comment]
Here is how you can do [Testing](https://github.com/proengsoft/laravel-jsvalidation/wiki/Testing).

**Comment by antonkomarev** [comment]
@marcelogarbin you don't need to change js or recompile anything:
1. fork this repository
2. clone your fork repository
3. create branch in your fork with name for example: "add/laravel-v6-support"
4. make changes in `composer.json` & `.gitignore` files
5. commit & push

Make pull request on GItHub from this branch.

**Comment by marcelogarbin** [comment]
@antonkomarev 
Other questions arose here.
- I made the changes to composer.json (https://github.com/marcelogarbin/laravel-jsvalidation/tree/add/laravel-v6-support), so I would like to install and test on a local project, would I like to do that? if so how?
- About the documentation, how is the composer version made? You who take care of it? Example: Old: `composer require proengsoft/laravel-jsvalidation:2.4` 
New: `composer require proengsoft/laravel-jsvalidation:2.5`
- What are the next steps?

Thank you

**Comment by antonkomarev** [comment]
In your app you can define path to your fork in `repositories` section.

```json
"repositories": [
    {
        "type": "git",
        "url": "git@github.com:marcelogarbin/laravel-jsvalidation.git"
    }
],
```

And then in `require` section you can write:
```json
"proengsoft/laravel-jsvalidation:dev-add/laravel-v6-support"
```

Documentation seems outdated. But it's in Wiki - so it's another one place to make changes and it could be done after merging this feature to master branch.

Next step - create Pull Request.

I hope @torrentalle have a time to make new release.

**Comment by marcelogarbin** [comment]
@antonkomarev Very nice, I didn't know that. I hope that with your help I can contribute to more projects. I confess that I still need to see more of the tests.

At first the installation was successful here. But I did not test all the features in this new version, because I am starting a new project.

![image](https://user-images.githubusercontent.com/9335588/64254914-b7a79280-cef6-11e9-8177-249911ebda90.png)

thanks for your attention

**Comment by marcelogarbin** [comment]
https://github.com/proengsoft/laravel-jsvalidation/pull/391

There is already a pull for this, I just didn't notice before sending mine.
