### ISSUE TITLE
Show loading spinner while checking

### ISSUE THREAD

**Issue by BechirAhmed** [proengsoft/laravel-jsvalidation#396]
Is it possible to show the user spinner loading while the system checking for validation, if it's not already implemented in this package, how can i implement it manually?
how to trigger the package events?

**Comment by OppPMatos** [comment]
Validation should not be taking enough time to justify a spinner.
And you risk adding unnecessary processes that will slow down the validation itself, since validation is triggered by changes on single field.

**Comment by BechirAhmed** [comment]
Thanks for your answer @OppPMatos
