### ISSUE TITLE
Using laravel-jsvalidation with other packages

### ISSUE THREAD

**Issue by garbinmarcelo** [proengsoft/laravel-jsvalidation#405]
I'm using the https://github.com/yairEO/tagify package, so when it is activated it ends up changing the HTML structure, as in the image: 

![image](https://user-images.githubusercontent.com/9335588/72904358-8694f680-3d0d-11ea-9bef-bd948cd87f4e.png)

Would there be any way to use laravel-jsvalidation when the HTML structure is changed from the standard used by the package?

Thanks

**Comment by bytestream** [comment]
JS validation should work on any input element.
