### ISSUE TITLE
Disable submit button while checking unique rule

### ISSUE THREAD

**Issue by garbinmarcelo** [proengsoft/laravel-jsvalidation#406]
Hello, 

How can I disable the submit button while checking the unique rule, which files should I check?

I have a problem using ajaxForm, when I update, the form is being sent 2 times.

Thanks

**Comment by marcelogarbin** [comment]
I found a way, I don't know if it is more correct, but at the moment it seems to have worked and it comes up against the same problem that I had in 2017 and is still open as mentioned in this issue.

in: _jsvalidation/js/jsvalidation.js_ => ```$.validator.addMethod("laravelValidationRemote", function(value, element, params)```

inside the ajax function in beforeSend I added:
`$('button[type=submit]').prop('disabled', true);`

on always method:
`$('button[type=submit]').prop('disabled', false);`

it seems that now it was agreed, because first it checks the unique rule and at first the submit button is blocked, after the return of the ajax query the button returns to its normal state.

If anyone has any idea of improvement in this case, please comment. 

Thanks

**Comment by bytestream** [comment]
I've responded to your other issue.

**Comment by hendralin** [comment]
i have got same issue when I update field with unique rule, the form is being sent 2 times.

**Comment by bytestream** [comment]
Check my reply here;
https://github.com/proengsoft/laravel-jsvalidation/issues/285#issuecomment-598911377

Kind regards,
Kieran Brahney

Sent via mobile.
Please excuse the spelling, brevity and punctuation.

**Comment by hendralin** [comment]
got another error : 

`Uncaught ReferenceError: validator is not defined`

**Comment by bytestream** [comment]
That's probably something to do with https://github.com/proengsoft/laravel-jsvalidation/issues/411

Feel free to submit PR for your issues.

**Comment by hendralin** [comment]
#FormRequest.php
Using Laravel 7
```php
public function rules()
    {
        return [
            'nama' => 'required|max:30|unique:akuns,nama,' . $this->id,
            'kode' => 'required|max:5|unique:akuns,kode,' . $this->id,
            'kelompok_akun_id' => 'required',
        ];
    }
```
After define validator, error is gone and when I submit form still sent 2 times.

bootstrap4.php
```javascript
            submitHandler: function (form) {
                    $(form).find(':submit').prop('disabled', true);

                    var validator = $(form).validate();

                    // Validate the form.
                    if (validator.form()) {
                        // Handle remote validation rules.
                        if (validator.pendingRequest) {
                            validator.formSubmitted = true;
                            return false;
                        }

                        // Submit the form (will cause the page to refresh etc).
                        // form.submit();
                    } else {
                        $(form).find(':submit').prop('disabled', false);
                        validator.focusInvalid();
                        return false;
                    }
                },

                focusInvalid: true,
                <?php if (Config::get('jsvalidation.focus_on_error')): ?>
                invalidHandler: function (form, validator) {

                    // Enable submit button again (necessary for invalid remote validation).
                    $(this).find(':submit').prop('disabled', false);
```
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19182964/77385700-748e0d80-6dbb-11ea-822f-c91ea1bed0e9.gif)

**Comment by hendralin** [comment]
after change button type from submit to 'button' now the unique validation working well...
I'm sorry for my mistake and thanks you laravel-jsvalidation :)

**Comment by bytestream** [comment]
@hendralin please submit a PR for your fixes.
