### ISSUE TITLE
Form still submits with jsvalidation

### ISSUE THREAD

**Issue by iamphedz** [proengsoft/laravel-jsvalidation#408]
Hi. i'm having this problem with the project im doing right now. 

i already included the script and blade src of the requestform class. but the form still submits. and the inputs that supposed to have error only turns their border color to red w/o the validation error.
Here's a screenshot of what the form looks like after submission:
[https://imgur.com/a/iLwHkvp](url)

anyone knows how to fix this? thanks in advance.

PS. I'm using version 1.1 of this package. currently using laravel 5.2

**Comment by bytestream** [comment]
Sorry that version of the package isn't supported. Please upgrade to latest and reopen if the issue continues.
