### ISSUE TITLE
Object doesn't support property or method 'validate' IE Explorer

### ISSUE THREAD

**Issue by krutarthcactus** [proengsoft/laravel-jsvalidation#410]
Hello,

I am getting Object doesn't support property or method 'validate' only with IE Explorer because of which my entire site is not working
Not sure what is the problem. 

PartialController.php
```
$validator = JsValidator::make([
    'email' => 'required|email|regex:/[a-z0-9_\-\+\.]+@[a-z0-9\-]+\.([a-z]{2,4})(?:\.[a-z]{2})?/i'
], 
[
    'email.email' => 'Recheck Your :attribute Address',
    'email.required' => ':attribute cannot be empty',
    'email.regex' => 'Recheck Your :attribute Address',
    'password.required' => ':attribute cannot be empty',
],
[
    'password' => 'Password',
    'email' => 'Email'
]);

return view(patial', compact('validator'));
```

partial.blade.php
```
@extends('layouts.app')
....
....
@section('custom-js')
    {!! $validator->selector('#formId') !!}
@endsection
```

app.blade.php
```
<script src="{{ mix('/js/app.js') }}"></script>
@yield('custom-js')
```

Not sure what I am doing wrong here, could anyone help me here, please.

Note: 
IE Explorer version 11.9
Using Bootstrap 4

**Comment by thewebartisan7** [comment]
Did you include also this scripts?

https://github.com/proengsoft/laravel-jsvalidation/tree/master/resources/assets/js

**Comment by krutarthcactus** [comment]
@thewebartisan7 
Actually the issue was with other library which was loaded into the project and was not compatible with IE Explorer, changed the version of library which had compatibility with IE

Thanks for replying 
Closing this issue
