### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by LocalHeroPro** [proengsoft/laravel-jsvalidation#411]
When I used default example:
```html
<script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js') }}"></script>
{!! JsValidator::formRequest('App\Http\Requests\MyFormRequest') !!}
```
I got twice error in console:
```console
Uncaught ReferenceError: jQuery is not defined
```
So i added `defer` to first script declaration, like this
```html
<script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js') }}" defer></script>
```
Now only one error present in console.

So, how to achieve `defer` solution in second line, or something similar to prevent auto loading that validation rules before jQuery are set?

**Comment by thewebartisan7** [comment]
Most probably you are using default laravel layouts, which load app.js using defer, see

https://github.com/laravel/ui/blob/2.x/src/Auth/bootstrap-stubs/layouts/app.stub#L13

So you can just remove defer from this

**Comment by LocalHeroPro** [comment]
I don't wanna remove form anywhere `defer`.
I wan to have ability to add `defer` to `{!! JsValidator::formRequest('App\Http\Requests\MyFormRequest') !!}`.

**Comment by thewebartisan7** [comment]
Then you can edit generated script tag from this view:

https://github.com/proengsoft/laravel-jsvalidation/blob/master/resources/views/bootstrap4.php

For override it you can add in your resources/views/vendor/jsvalidation/bootstrap4.blade.php or create a new view anywhere and then edit config here:

https://github.com/proengsoft/laravel-jsvalidation/blob/master/config/jsvalidation.php#L10

**Comment by bytestream** [comment]
Yes, please override and modify the default view as @thewebartisan7 suggests.
