### ISSUE TITLE
Question about ignore: "<?= $validator['ignore']; ?>",

### ISSUE THREAD

**Issue by garbinmarcelo** [proengsoft/laravel-jsvalidation#416]
Hello,
I would like to know how and when ignore (`ignore: "<?= $validator['ignore']; ?>",`) is used in this package.

Could you give an example?

**Comment by bytestream** [comment]
`ignore` is a jquery validate function, more info @ https://jqueryvalidation.org/validate/#ignore

**Comment by garbinmarcelo** [comment]
> `ignore` is a jquery validate function, more info @ https://jqueryvalidation.org/validate/#ignore

right, but how to call this ignore using the laravel-jsvalidation package?

In the case of laravel I create a Request with all the validation rules I want and on the blade I just call for example: `{!! JsValidator::formRequest('Modules\XXX\Http\Requests\RequestXXX') !!}`

This ignore is not used within the request so, is that it?

Because as I mentioned in this question, I'm passing the ignore: [] (empty), to be able to validate the CKEditor.

**Comment by bytestream** [comment]
You can pass it using:
```php
JsValidator::formRequest(FeedbackFormRequest::class)->ignore('[]')
```

**Comment by garbinmarcelo** [comment]
> You can pass it using:
> 
> ```
> JsValidator::formRequest(FeedbackFormRequest::class)->ignore('[]')
> ```

this does not seem to work with the formRequest method. Would you have any alternative or suggestion to adjust this?

![image](https://user-images.githubusercontent.com/9335588/76684421-b6b09580-65ea-11ea-82f1-64931f6a96fd.png)

**Comment by bytestream** [comment]
The formRequest function doesn't return a string -
https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/JsValidatorFactory.php

What's the code you used?

Kind regards,
Kieran Brahney

Sent via mobile.
Please excuse the spelling, brevity and punctuation.

**Comment by garbinmarcelo** [comment]
> You can pass it using:
> 
> ```
> JsValidator::formRequest(FeedbackFormRequest::class)->ignore('[]')
> ```

I used this...
