### ISSUE TITLE
I want to show the laravel error to the client

### ISSUE THREAD

**Issue by dilipdk** [proengsoft/laravel-jsvalidation#425]
### Subject of the issue
Describe your issue here.
I want to list error from backend. while im checking unique validation, it seems js validation says an error like "Whoops, looks like something went wrong." instead of this i want to show the error like ":attribute has been taken already".
### Your environment
* version of this package:
* version of Laravel: 6.x

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by bytestream** [comment]
Please provide a minimal test case to replicate the issue.
