### ISSUE TITLE
Unable to install laravel-jsvalidation on laravel 7

### ISSUE THREAD

**Issue by weeliem** [proengsoft/laravel-jsvalidation#427]
### Subject of the issue
Unable to install laravel-jsvalidation on laravel 7

### Your environment
* version of this package: proengsoft/laravel-jsvalidation:^2.5
* version of Laravel: laravel/framework 7.3.0

### Steps to reproduce
Run composer require proengsoft/laravel-jsvalidation:^2.5

### Expected behaviour
Install successfully

### Actual behaviour
- Can only install one of: laravel/framework[6.x-dev, v7.3.0].
    - don't install illuminate/view 5.4.x-dev|don't install laravel/framework v7.3.0
    - don't install illuminate/view 5.8.x-dev|don't install laravel/framework v7.3.0
    - don't install illuminate/view 6.x-dev|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.4.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.4.13|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.4.17|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.4.19|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.4.27|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.4.36|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.4.9|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.11|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.12|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.14|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.15|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.17|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.18|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.19|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.2|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.20|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.22|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.24|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.27|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.28|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.29|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.3|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.30|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.31|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.32|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.33|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.34|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.35|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.36|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.4|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.8|don't install laravel/framework v7.3.0
    - don't install illuminate/view v5.8.9|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.0.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.0.1|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.0.2|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.0.3|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.0.4|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.1.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.10.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.11.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.12.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.13.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.13.1|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.14.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.15.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.15.1|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.16.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.17.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.17.1|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.18.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.18.1|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.18.2|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.18.3|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.2.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.3.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.4.1|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.5.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.5.1|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.5.2|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.6.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.6.1|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.6.2|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.7.0|don't install laravel/framework v7.3.0
    - don't install illuminate/view v6.8.0|don't install laravel/framework v7.3.0
    - Installation request for laravel/framework (locked at v7.3.0, required as ^7.0) -> satisfiable by laravel/framework[v7.3.0].

**Comment by bytestream** [comment]
Version 3.0 is required for Laravel 7 support.

Kind regards,
Kieran Brahney

Sent via mobile.
Please excuse the spelling, brevity and punctuation.
