### ISSUE TITLE
Route Model Binding Form Request Validation Error

### ISSUE THREAD

**Issue by seanthepottingshed** [proengsoft/laravel-jsvalidation#44]
Excellent package, should be part of the Laravel core in my opinion, but there you go. However, I can't seem to get this to work using Route Model binding for edit form. I am using the Eloquent-Sluggable package in order to reference via slug rather than id:

https://github.com/cviebrock/eloquent-sluggable

Here is an example using Menu as an example:

**app/Http/RouteServiceProvider.php**

```
public function boot(Router $router)
{
        $router->bind('menus', function($slug)
        {
           return Menu::findOrThrowException($slug);
        });
}
```

**app/Http/Providers/UpdateMenuRequest.php**

```
public function rules()
{
	return [
		'title' => 'required|unique:menus,title,' . $this->route('menus')->id,
       ];	
}
```

**menus/edit.php**

```
{!! JsValidator::formRequest('App\Http\Requests\UpdateMenuRequest', '#menu') !!}
```

I get the following error:

```
ErrorException in UpdateMenuRequest.php line 27:
Trying to get property of non-object (View: /home/vagrant/Code/TpsCMS/resources/views/admin/menus/edit.blade.php)
```

Line 27 being...

```
'title' => 'required|unique:menus,title,' . $this->route('menus')->id,
```

Could you pleas advise me further?

**Comment by torrentalle** [comment]
I can't make work your example without JsValidation
Did you try if your validation work without using JsValidation?

**Comment by torrentalle** [comment]
Ok, I found the error.
Before Javascript Validations are generated, Request should be passed to FormRequest.
I'm looking how do that

**Comment by torrentalle** [comment]
I the master branch this issue is resolved

**Comment by seanthepottingshed** [comment]
**torrentalle** you are a legend. I was looking through the source yesterday but couldn't figure out how to do it. In answer to your earlier question the **UpdateMenuFormRequest FormRequest** validation works as intended with the form model binding.

**Comment by torrentalle** [comment]
Republish Javascript files after composer update to apply the patch

```
composer update
php  artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider" --tag="public" --force
```
