### ISSUE TITLE
PHP memory limit

### ISSUE THREAD

**Issue by undjike** [proengsoft/laravel-jsvalidation#455]
I was unable to install the package because of PHP memory limit exceed. I got the message **Allowed memory size exhausted**. Reading composer troubleshooting to handle out this issue, I had to set my PHP.ini memory_limit to -1 for it to work (It was at 128M, I've tried 500M but the problem remained).

PHP manual defined this option to prevent memory waste for a script. Setting this to unlimited may be harmful for the system. 

I'm using Laravel 7 and the version of the package to be installed is ^4.0.

**Comment by bytestream** [comment]
This shouldn't be anything to do with this package specifically. Composer is known to use a lot of memory if your `composer.json` defines a lot of dependencies
