### ISSUE TITLE
Error method is undefined

### ISSUE THREAD

**Issue by a-komarev** [proengsoft/laravel-jsvalidation#50]
I've got an error in Firefox console:
>TypeError: $.validator.methods[method] is undefined

In Chrome:
> jquery.validate.js:617 Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by samuelfa** [comment]
I have the same problem. On line 618 the var method it's a object with the parameter laravelValidation and contains an Array with 4 entries:

["Required", [], "The username field is required", true]

Currently I'm using the version 1.0.5 by this reason.

**Comment by a-komarev** [comment]
@samuelfa thanks. `v1.0.6` is working too.

**Comment by samuelfa** [comment]
Hmm I don't see v1.0.6 there https://github.com/proengsoft/laravel-jsvalidation/releases it's the list of versions. On 1.1.0 I have the same error and when They released v1.1.1, I hope that this fail wad fixed

**Comment by torrentalle** [comment]
Did you republished the Javascript files after upgrade?
Try to execute this command after package update
```
php artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider" --tag="public" --force
```

**Comment by a-komarev** [comment]
@torrentalle Thanks! That's helped me!

I've installed it with `php artisan vendor:publish` but that didn't worked.
