### ISSUE TITLE
The form input not remove error class when input correct data 

### ISSUE THREAD

**Issue by FaruquiSahab** [proengsoft/laravel-jsvalidation#500]
### Subject of the issue
Error class not removing back after correct data enter

### Your environment
* laravel-jsvalidation 4.3.0:
* Laravel 7.24:

### Steps to reproduce
First I submitted the blank(empty) form it highlight the validation fields add the red error class.
After then when the correct data is entered, it does not remove the error class and for is submitting

### Expected behavior
After the error displayed on empty or wrong data 
when user inputs the correct data is should remove the error class 

### Actual behavior
After the error displayed on empty or wrong data 
when user inputs the correct data error class not removing

**Comment by FaruquiSahab** [comment]
**Blade**
{!! JsValidator::formRequest('App\Http\Requests\createaccountrequest', '#hiddenformusernametest'); !!}

**Comment by FaruquiSahab** [comment]
**Request**
`<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class createaccountrequest extends Request
{

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'txtAccountName' => 'required|min:3|max:100|regex:/^([a-zA-Z-.\(\)& ]+)$/',
            'txtAccountEmail' => 'required|email|max:50|regex:/^([a-z0-9\+_\-]+)(\.[a-z0-9\+_\-]+)*@([a-z0-9\-]+\.)+[a-z]{2,6}$/',
            'txtAccountPassword' => 'required|min:6|max:100|regex:/^.*(?=.{6,})(?=.*[a-z])(?=.*[A-Z])(?=.*[\d])(?=.*[\W]).*$/',
            'txtAccountNTN' => 'regex:/^[0-9]{7}(-)[0-9]{1}$/|max:9',
            'txtAccountSTRN' => 'regex:/^[0-9]{2}(-)[0-9]{2}(-)[0-9]{4}(-)[0-9]{3}(-)[0-9]{2}$/|max:17',
            'txtAccountZIP' => 'numeric',
            'txtAccountContact' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:8|max:30',
            'txtAccountbillingAddress' => 'required|min:3|max:200',
            'txtAccountDollarRate' => 'required|numeric',
            'txtAccountUserName' => 'required|min:6|regex:/^([a-zA-Z0-9\-@_#]+)$/|max:12',
            'txtAccountUserNametest' => 'required|min:6|regex:/^([a-zA-Z0-9\-@_#]+)$/|max:12',
        ];
    }

}
`

**Comment by FaruquiSahab** [comment]
```
<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class createaccountrequest extends Request
{

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'txtAccountName' => 'required|min:3|max:100|regex:/^([a-zA-Z-.\(\)& ]+)$/',
            'txtAccountEmail' => 'required|email|max:50|regex:/^([a-z0-9\+_\-]+)(\.[a-z0-9\+_\-]+)*@([a-z0-9\-]+\.)+[a-z]{2,6}$/',
            'txtAccountPassword' => 'required|min:6|max:100|regex:/^.*(?=.{6,})(?=.*[a-z])(?=.*[A-Z])(?=.*[\d])(?=.*[\W]).*$/',
            'txtAccountNTN' => 'regex:/^[0-9]{7}(-)[0-9]{1}$/|max:9',
            'txtAccountSTRN' => 'regex:/^[0-9]{2}(-)[0-9]{2}(-)[0-9]{4}(-)[0-9]{3}(-)[0-9]{2}$/|max:17',
            'txtAccountZIP' => 'numeric',
            'txtAccountContact' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:8|max:30',
            'txtAccountbillingAddress' => 'required|min:3|max:200',
            'txtAccountDollarRate' => 'required|numeric',
            'txtAccountUserName' => 'required|min:6|regex:/^([a-zA-Z0-9\-@_#]+)$/|max:12',
            'txtAccountUserNametest' => 'required|min:6|regex:/^([a-zA-Z0-9\-@_#]+)$/|max:12',
        ];
    }

}

```

**Comment by bytestream** [comment]
You probably need to uncomment https://github.com/proengsoft/laravel-jsvalidation/blob/master/resources/views/bootstrap.php#L29

**Comment by FaruquiSahab** [comment]
I did the change you mentioned, but still same problem exist
![image](https://user-images.githubusercontent.com/44661979/92718414-38576500-f37b-11ea-83a9-29624ad6331f.png)

**Comment by bytestream** [comment]
Suggest to read over the documentation https://jqueryvalidation.org/validate/. The highlighting / unhighlighting of fields is controlled by the validate config - https://github.com/proengsoft/laravel-jsvalidation/blob/master/resources/views/bootstrap.php. If it's not working, then changes need to be made to that config.
