### ISSUE TITLE
I search options to check and store data in ajax post request

### ISSUE THREAD

**Issue by sergeynilov** [proengsoft/laravel-jsvalidation#502]
Hello ,
I have worked with proengsoft/laravel-jsvalidation in several laravel 6 apps and 
it is good when I store/update data with POST/PUT requests
and data are validated on client but if validation is ok data are saved with page reloading and 
I want to escape it.

I store my data from JS code :
        function taskstore() {
            $.ajax({
                url: 'tasks',
                type: "post",
                dataType: 'json',
                data: {'_token': '{{csrf_token()}}'},
                success: function (data) {
                   ...
                },
                error: function (xhr) {
                    console.error(xhr)
                }
            });

        }

I do not see how this pluging can be usefull in my case...
Or have it some additive options?

Thanks!

**Comment by bytestream** [comment]
Please could you clarify what you mean? This library is only intended for validation.
