### ISSUE TITLE
Multiple instances of the error message

### ISSUE THREAD

**Issue by almamundinajpuri** [proengsoft/laravel-jsvalidation#51]
Hello,
After update I'm noticing multiple instances of the same error message. As I type input or hit submit button, new error messages just keep appending. See the screenshots please

Regards

**Screenshot 1**
![capture](https://cloud.githubusercontent.com/assets/5769361/9313447/df389604-4544-11e5-8c5f-62ff18392bf0.PNG)
**Screenshot 2**
![capture2](https://cloud.githubusercontent.com/assets/5769361/9313449/e0b2356c-4544-11e5-997c-d877796dc70c.PNG)

**Comment by torrentalle** [comment]
Try to republish the views and assets.
```
php artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider" --force
```

**Comment by almamundinajpuri** [comment]
I noticed the issue with something else. You see in the 1st screenshot, I've enabled Bootstrap tooltips.
```
<script>
$("[data-toggle='tooltip']").tooltip();
</script>
```
 I think they are conflicting. If I disable tooltips, the issue is gone.

**Comment by torrentalle** [comment]
Thank's I will check it

**Comment by torrentalle** [comment]
This issue is related to #27 . Fixed in `dev-master` branch

**Comment by torrentalle** [comment]
duplicated with #35
