### ISSUE TITLE
Empty messages array

### ISSUE THREAD

**Issue by a-komarev** [proengsoft/laravel-jsvalidation#53]
`messages` array will be always empty.

`vendor/proengsoft/laravel-jsvalidation/src/Validator.php`
```php
public function validationData()
{
    $jsMessages = array();
    $jsValidations = $this->generateJavascriptValidations();

    return [
        'rules' => $jsValidations,
        'messages' => $jsMessages,
    ];
}
```

Am I missed something? Because in previous version as I understand messages array were taken from `generateJavascriptValidations()` method:

```php
public function js()
{
    list($jsRules, $jsMessages)=$this->generateJavascriptValidations();
    return [
        'rules' => $jsRules,
        'messages' => $jsMessages
    ];
}
```

Displaying messages still working. This array key is deprecated or what?

**Comment by torrentalle** [comment]
Yes ,`messages` should be empty, It's deprecated
