### ISSUE TITLE
Js error when using 'after' validation rule

### ISSUE THREAD

**Issue by sp-k-tsuji** [proengsoft/laravel-jsvalidation#530]
### Subject of the issue
Js error occurs when i use `after` validation rule.

### Your environment
* version of this package: 4.4.0
* version of Laravel: 8.15.0

### Steps to reproduce

1. Validation rule in FormRequest. Using 'after' rule and compare with other field.
    ```php
    [
        'start' => ['required', 'date'],
        'end' => ['required', 'date', 'after:start'],
    ];
    ```
2.  Those fields are in blade template.
    ```html
    <form method="post" action="./">
       <input type="text" name="start" class="datepicker">
       <input type="text" name="end" class="datepicker">
    </form>
    ```
3. Enter the correct format date in the `end` field.

### Expected behaviour
No js errors,  `after` validation works fine.

### Actual behaviour
I get this js error.

```
    jquery.validate.js:1053 Uncaught TypeError: string.replace is not a function.  Exception occurred when checking element , check the 'laravelValidation' method.
    at $.validator.escapeCssMeta (jquery.validate.js:1053)
    at $.validator.findByName (jquery.validate.js:1076)
    at Object.dependentElement (helpers.js:1820)
    at Object.compareDates (helpers.js:1694)
    at $.validator.After (validations.js:705)
    at String.<anonymous> (jsvalidation.js:182)
    at Function.each (jquery.min.js:2)
    at Array.<anonymous> (jsvalidation.js:181)
    at Function.each (jquery.min.js:2)
    at validateLocalRules (jsvalidation.js:170)
```

**Comment by bytestream** [comment]
Thanks. Please check https://github.com/proengsoft/laravel-jsvalidation/commit/40a4ab965735b5a572819f88768e51f034c564e5 and let me know if it helps.

`compare require proengsoft/laravel-jsvalidation:dev-fix-530`

**Comment by sp-k-tsuji** [comment]
@bytestream Thank you. It works.
