### ISSUE TITLE
Unique doesn't seems to work?

### ISSUE THREAD

**Issue by seirralanzce** [proengsoft/laravel-jsvalidation#545]
### Subject of the issue
Added unique but it doesn't seem to validate it properly?

under the jsvalidation formRequest shown this.
`"laravelValidationRemote":[["Unique",["grn_number","eyJpdiI6IkFiYmJSdjBvdVJ1clBLVFMzNWJBQkE9PSIsInZhbHVlIjoiNXdYdHpEVnJ0c2VEMjZpTnNrWURxNnhMRC9wNFV6M1lHcHJLRFZLdWs3NitqY0ZFTExaM0cxNW5rcUVOMFBHaksvSVhkSlg3UkFBU2lZTG14LzJzc2c9PSIsIm1hYyI6IjExYTZiOGY5YzYzODg4YmMzODU5NzlhZmNjMDQyOWNiZjA2ZDQ1Y2IyMWYxZDBiMWE4NjM1YWQ4M2FiM2RlMGUifQ==",false]`

is this supposing correct?

### Your environment
* version of this package: ^4.4.0
* version of Laravel: ^7.0

### Steps to reproduce
added rules to have unique:table,column

### Expected behaviour
Return that the value is already used

### Actual behaviour
Accepted and turn into is valid

**Comment by bytestream** [comment]
I'm not aware of an issue with the unique rule. If jsvalidations allows you to submit the form, Laravel should block the rule if there's a problem. Is that the case?

**Comment by seirralanzce** [comment]
> I'm not aware of an issue with the unique rule. _If jsvalidations allows you to submit the form, Laravel should block the rule if there's a problem. Is that the case?_

Yes the the overall form still function as it is, but would love to make the if unique found, to not allow user to continue.

**Comment by bytestream** [comment]
I cannot replicate this:
```php
JsValidator::make([ 'email'   => 'required|unique:user,email', ])
```

Please can you provide a **minimal** GitHub repo that demonstrates the issue.
