### ISSUE TITLE
Javascript validation of dates when date is '0000-00-00'

### ISSUE THREAD

**Issue by mankowitz** [proengsoft/laravel-jsvalidation#556]
### Subject of the issue
Users can enter invalid date beginning with 0, and it is parsed as correct

### Your environment
* version of this package: 3.0.1
* version of Laravel: 7.28.4

### Steps to reproduce
Create a validation for a date field, as an example, date of birth as below
```
            'dob' => 'nullable|date|before:today|after:1900-01-01',
```

### Expected behaviour
The input should be invalid for a date of '0000-00-00'

### Actual behaviour
The input is accepted

### Potential explanation or fix
The javascript `Date` function is used to parse the date. Whenever the passed string begins with '0', it reports the current time. 
```
> Date("0000-00-00")
"Fri Dec 11 2020 09:39:09 GMT-0500 (Eastern Standard Time)"
```

**Comment by bytestream** [comment]
Thanks for the report. Makes sense.

**Comment by bytestream** [comment]
I cannot replicate this on `v4.4.2`

```html
<input type="text" name="date" value="000-00-00" />
```

```php
'date|before:today|after:1900-01-01'
```

Produces `The date must be a date after 1900-01-01.`
