### ISSUE TITLE
Hidden input raising an error

### ISSUE THREAD

**Issue by a-komarev** [proengsoft/laravel-jsvalidation#58]
If hidden input presented - validator trying to validate it instead of visible fields.

```html
<label>Rate user</label>
<input type="hidden" name="rating" value="">
<div class="radio-list">
    <span class="star-rating">
        <input id="rating5" type="radio" name="rating" value="5">
        <label for="rating5">5</label>
        <input id="rating4" type="radio" name="rating" value="4">
        <label for="rating4">4</label>
        <input id="rating3" type="radio" name="rating" value="3">
        <label for="rating3">3</label>
        <input id="rating2" type="radio" name="rating" value="2">
        <label for="rating2">2</label>
        <input id="rating1" type="radio" name="rating" value="1">
        <label for="rating1">1</label>
    </span>
</div>
```

In current example `rating` field is `required`. Even if one of the visible radio controls is checked - validator ignores it and continue to display an error that rating is required (it rendering right after hidden input). But as soon as value of hidden input will be setted as `value="0"` - form will work as expected.

As I know in HTML each next checked control overriding values of controls with same named which were met before and only latest one is sending. In current case it looks like validator trying to validate first occurrence.

**Comment by a-komarev** [comment]
In case when hidden input is defined this way:
```html
<input type="hidden" name="rating" value="0">
```
And in FormRequst rules:

```php
public function rules()
{
    return [
        'rating' => 'required|in:1,2,3,4,5',
        'body' => 'required',
    ];
}
```
Even if visible radio controls are checked - an error will be raised near the hidden input:

> The selected rating is invalid.

And even if this hidden input is placed inside of `.radio-list` - this error rendering right after it and not after `<div class="radio-list">` block.

**Comment by torrentalle** [comment]
Remove this line from your `resources/views/vendor/jsvalidation/bootstrap.php` file
```js
ignore: "",  // validate all fields including form hidden input
``` 
In the next release this will be fixed
