### ISSUE TITLE
Submit button don't work...

### ISSUE THREAD

**Issue by almaweb** [proengsoft/laravel-jsvalidation#61]
Hello,

I have this in my formrequest :

		$id = Sentinel::getUser()->id;
		return $rules = [
			'first_name' => 'required',
			'last_name' => 'required', 
			'email' => 'required|email|unique:users,email,' . $id
 
		];
		the probleme is the last line...because all work without it...
I cant'submit the form...submit button don't work...

**Comment by torrentalle** [comment]
Can you post the javascript generate by JsValidation ?

**Comment by torrentalle** [comment]
Try with the latest release, maybe tour issue is related to #59

**Comment by torrentalle** [comment]
Hi @almaweb  I can't reproduce your issue. Did you try the latest release?

**Comment by torrentalle** [comment]
Your issue could be realted to issue #81
