### ISSUE TITLE
Image rule doesn't work

### ISSUE THREAD

**Issue by qjgm** [proengsoft/laravel-jsvalidation#63]
I get this error whenever i use the 'image' or 'mimes:photo' rule, i'm using FormRequest, the other rules are working such as required, etc. 

![screen shot 2015-08-29 at 3 10 48 pm](https://cloud.githubusercontent.com/assets/7346328/9560887/2f6566a6-4e60-11e5-9e6a-e8e3b24ee963.png)

**Comment by qjgm** [comment]
this is via ajax post on a bootstrap modal

**Comment by torrentalle** [comment]
Upgrade to latest release and if your issue persist, post the javascritp generated by JsValidation

**Comment by torrentalle** [comment]
Hi @qjgm I can't reproduce your issue. Did you try the latest release?

**Comment by qjgm** [comment]
Yes sir sorry for the inconvenience, it's working already.

**Comment by torrentalle** [comment]
Thank's
