### ISSUE TITLE
Unique Rules

### ISSUE THREAD

**Issue by bihlmaierh** [proengsoft/laravel-jsvalidation#64]
Unique Roles currently are not checked via your plugin.

How can I use it ?

Currently I use version 1.1.1 ... thanks!

**Comment by torrentalle** [comment]
Can you post your rules?

**Comment by bihlmaierh** [comment]
For example the rule

`'email' => 'unique:users,email_address'`

doesn't work.

Here is first a post request and then the rule come as error. No ajax request ...

**Comment by torrentalle** [comment]
Try with the latest release, maybe tour issue is related to #59

**Comment by torrentalle** [comment]
@bihlmaierh , did you solve your issue?

**Comment by bihlmaierh** [comment]
I've tested it this morning and all seems okay now.
Thanks for help.
