### ISSUE TITLE
after rule with date does not work

### ISSUE THREAD

**Issue by mankowitz** [proengsoft/laravel-jsvalidation#647]
### `after` rule not working for specific date
I have a rule as follows:
`            'dob' => 'nullable|date|before:yesterday|after:1900-01-01',`

When I enter a date (e.g. "1944-04-02"), it fails. 

### Your environment
* version of this package: 4.4.4
* version of Laravel: 8.37.0

### Steps to reproduce
create a rule with
`            'dob' => 'nullable|date|before:yesterday|after:1900-01-01',`
Enter "1944-02-04"

### Expected behaviour
rule should pass

### Actual behaviour
the rule fails

### My explanation
When this rule is parsed, it generates the following javascript
```
"dob":{"laravelValidation":[["Nullable",[],"validation.nullable",false,"dob"],
["Date",[],"The dob is not a valid date.",false,"dob"],
["Before",[1618891200],"The dob must be a date before yesterday.",false,"dob"],
["After",[-2208970800],"The dob must be a date after 1900-01-01.",false,"dob"]]},
```
As you can see, it correctly transforms 1900-01-01 into -2208970800.
However, it is later passed into the `parseTime` helper function with arguments

value: -2208970800
format: undefined

this results in the value being passed to **strtotime**, which returns _now,_ and the rule fails.

```
        parseTime: function (value, format) {

            var timeValue = false;
            var fmt = new DateFormatter();

            if (typeof format === 'object') {
                var dateRule = this.getLaravelValidation('DateFormat', format);
                if (dateRule !== undefined) {
                    format = dateRule[1][0];
                } else {
                    format = null;
                }
            }

            if (format == null) {
                timeValue = this.strtotime(value);
            } else {
                timeValue = fmt.parseDate(value, format);
                if (timeValue) {
                    timeValue = Math.round((timeValue.getTime() / 1000));
                }
            }

            return timeValue;
        },
```

**Comment by bytestream** [comment]
PR welcome. I guess it's something to do with use of a negative number with `strtotime`

**Comment by bytestream** [comment]
Maybe the simple fix is to remove `strtotime` from https://github.com/proengsoft/laravel-jsvalidation/blob/fc8f502a585a63aee1a5f9aa3b0750019a62fda4/src/Javascript/JavascriptRulesTrait.php#L47 given it already runs in the JS.

**Comment by mankowitz** [comment]
Or remove it from js given it runs in php. Only advantage to having it run in js is that you have timezone information.

**Comment by mankowitz** [comment]
So strange. I thought I had submitted this PR in April. Guess not.
