### ISSUE TITLE
How to run JSValidator Facade on change event OR How to check remote validation on change event

### ISSUE THREAD

**Issue by DK19490** [proengsoft/laravel-jsvalidation#677]
### How to run JSValidator Facade on change event OR How to check remote validation on change event

In my form, I've two controls 
 - one is **select_store**  Having normal validation 
 - second is **coupon_code** having remote validation based on select_store
Based on the selected store, my coupon code will be unique like 
- select_store is US, SE, and coupon_code is XYZ then the US, SE are not able to take the coupon_code XYZ

**Issue:**
- In my system already has some old and duplicate records. like US having coupon_code XYZ, US having XYZ 
- so, In my edit form, selected select_store = US, coupon_code = XYZ, and when I click on submit button validation is fire on coupon_code is already taken but after that, my submit but is disable due to the form is invalid so when change the select_store value I need to recall the remote validation for coupon code

### Your environment
* version of this package: "^2.5"
* version of Laravel: "^6.2"

### Steps to reproduce
Take to two controls and second controls validation is dependent on first control value as dynamically 

### Expected behaviour
I need to recall JSvalidation remote method for particular control on any other controls change event 

### Actual behaviour
I am not able to recall JSvalidation remote method for particular control on any other controls change event
I've added my control flow in the below attachments. If anyone can know about this and or where I'm going the wrong pl. let me know 

![1](https://user-images.githubusercontent.com/85663593/121471108-c8930b00-c9dc-11eb-9528-7e7d8d9c92cc.png)
![2](https://user-images.githubusercontent.com/85663593/121471128-d183dc80-c9dc-11eb-99a6-94fda04932c7.png)
![3](https://user-images.githubusercontent.com/85663593/121471135-d47ecd00-c9dc-11eb-93a9-365c9e5e718f.png)
![4](https://user-images.githubusercontent.com/85663593/121471137-d779bd80-c9dc-11eb-906f-1429f5cb8777.png)
![5](https://user-images.githubusercontent.com/85663593/121471149-da74ae00-c9dc-11eb-84c4-8e6d3eeb2a67.png)
![6](https://user-images.githubusercontent.com/85663593/121471162-dcd70800-c9dc-11eb-8892-5b733e7bd206.png)
![7](https://user-images.githubusercontent.com/85663593/121471174-dfd1f880-c9dc-11eb-8b17-87d7383aff7a.png)
![8](https://user-images.githubusercontent.com/85663593/121471184-e2345280-c9dc-11eb-8e7c-730579f7b91c.png)
![9](https://user-images.githubusercontent.com/85663593/121471196-e496ac80-c9dc-11eb-8d79-75ec7dc6e6d4.png)

@bytestream Can you pl. help me to come out of this scenario? It'll huge thanks for you :)

**Comment by bytestream** [comment]
It'll be something to do with the use of select2, or whatever dropdown library you're using. Sometimes you have to tweak the jquery validation library config to get it to play nicely with other js libraries esp those that use hidden inputs, or have their own form submit handlers.

See https://github.com/select2/select2/issues/215#issuecomment-7082248 for some ideas. Google, and other issues in this library may also return helpful info.
