### ISSUE TITLE
How to reset form after submit 

### ISSUE THREAD

**Issue by faisalkhokher** [proengsoft/laravel-jsvalidation#685]

**Comment by faisalkhokher** [comment]
![Capture](https://user-images.githubusercontent.com/31187090/122977856-4e389280-d3af-11eb-893d-7a7160f872b9.PNG)

**Comment by RahibHasan** [comment]
just clear your form

**Comment by RahibHasan** [comment]
Like 
    $('#form_id')[0].reset();

**Comment by faisalkhokher** [comment]
@RahibHasan  not  work this condition $('#form_id')[0].reset();
