### ISSUE TITLE
Manager::__toString() must not throw an exception error

### ISSUE THREAD

**Issue by tpacuszka** [proengsoft/laravel-jsvalidation#69]
Hello I try to implement laravel-jsvalidation in my app, and in controller I try:

$validator = JsValidator::make(['field0' => 'min:3']);
return view('registration.registration')->with(['validator' => $validator]);

and than in view:
{!! $validator !!}

and I get:
Manager::__toString() must not throw an exception error
What's the problem? It's laravel 5.1

**Comment by torrentalle** [comment]
I can't reproduce your issue. 
In the view render validator using ```{!! $validator->render() !!}``` and post the exception that is throwed

**Comment by a-komarev** [comment]
I've recieved this error when used [Unique With Validator](https://github.com/felixkiss/uniquewith-validator).
But I'm not sure it's an error of current package, because here is a ticket with [similar issue](https://github.com/felixkiss/uniquewith-validator/issues/21).

**Comment by torrentalle** [comment]
Currently only is supported native Laravel Validations. [Laravel Validation Factory resolder](http://laravel.com/api/5.1/Illuminate/Validation/Factory.html#method_resolver) only accepts one resolver, so only one Validation package can be installed.
I'm working on a solution to solve this limitation

**Comment by dennisoderwald** [comment]
Update eta @torrentalle?

**Comment by torrentalle** [comment]
This feature is ready to test. See pull #79

**Comment by torrentalle** [comment]
This feature is published to [v1.2.0rc1](https://github.com/proengsoft/laravel-jsvalidation/tree/v1.2.0rc1) pre-release.
I'm preparing the documentation before to launch the production release
