### ISSUE TITLE
Unique validation issue under update

### ISSUE THREAD

**Issue by sabari-shankar** [proengsoft/laravel-jsvalidation#697]
When I using the unique validation the form is not submitted 

* version of this package:1.14.0
* version of Laravel:8+

Use unique validation in the request class 
'institute_code'=>'required|unique:institutions,institute_code,'.$this->institution.'',
When I try to update the data I click submit button unique validation is perform and return true but the form data is not posted again I click the submit button then only the data stored in DB

**Comment by bytestream** [comment]
> version of this package:1.14.0

There is no such version of this package

**Comment by sabari-shankar** [comment]
@bytestream Thanks for your response
![image](https://user-images.githubusercontent.com/25339305/124725029-278b6780-df2a-11eb-8753-4948d59248c6.png)

**Comment by sabari-shankar** [comment]
@bytestream Thanks for your response 
Here I'm using botble CMS in that it shows a jquery validation plugin version 
![image](https://user-images.githubusercontent.com/25339305/124727864-bc8f6000-df2c-11eb-9b84-7b53d59ed9ed.png)

**Comment by bytestream** [comment]
You'll be able to see what version of this package you have installed by looking in composer.json / composer.lock for proengsoft/laravel-jsvalidation

**Comment by sabari-shankar** [comment]
@bytestream Sorry I couldn't find this package in Botble CMS, I think they wrote a customized package
