### ISSUE TITLE
Bootstrap 5.x support

### ISSUE THREAD

**Issue by LocalHeroPro** [proengsoft/laravel-jsvalidation#728]
### Subject of the issue
Add support for Bootstrap 5.x.

### Your environment
* version of this package: newest
* version of Laravel: 8.x.x

**Comment by bytestream** [comment]
You can do this yourself by overriding the view in the config https://github.com/proengsoft/laravel-jsvalidation/blob/97863a4ba43fc9f7f75c2e5ada2a682f0a7c8a69/config/jsvalidation.php#L10

I guess I'll accept a PR which adds it to the existing predefined views https://github.com/proengsoft/laravel-jsvalidation/tree/master/resources/views
