### ISSUE TITLE
bootstrap.php file not in correct place

### ISSUE THREAD

**Issue by mankowitz** [proengsoft/laravel-jsvalidation#740]
### Subject of the issue
When building with webpack and using `.copy()`, the `bootstrap.php` file is not in the right place.
 
### Your environment
* version of this package: 4.4.3
* version of Laravel: 8.60.0

### Steps to reproduce
publish resources
`$ php artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider"`
put `.copy()` commands into webpack
`  .copy('vendor/proengsoft/laravel-jsvalidation/resources/views', 'resources/views/vendor/jsvalidation')
  .copy('vendor/proengsoft/laravel-jsvalidation/public', 'public/vendor/jsvalidation')`

### Expected behaviour
Should build correctly

### Actual behaviour
(node:250856) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/var/www/html/...../public/resources/views/vendor/jsvalidation/bootstrap.php'

The files (i.e. bootstrap.php) appear to be in `resources/views/vendor/jsvalidation/` instead of `./public/resources/views/vendor/jsvalidation/`

When I change the command to this, it works.
`  .copy('vendor/proengsoft/laravel-jsvalidation/resources/views', 'public/resources/views/vendor/jsvalidation')`

**Comment by bytestream** [comment]
This sounds like an issue with the way your using webpack, rather than an bug in this library. The template files are available in the `resources/views/` directory and it's up to you to decide how to use them. Perhaps I have misunderstood?

**Comment by mankowitz** [comment]
What I meant is that I followed the instructions in the docs and it didn't put the files in the "public" directory. Probably need to update the docs, not the library.

**Comment by bytestream** [comment]
Please could you link to said docs?

**Comment by mankowitz** [comment]
https://github.com/proengsoft/laravel-jsvalidation/wiki/Laravel-7.x-installation

**Comment by bytestream** [comment]
The documentation is correct. blade / twig / php template files shouldn't be exposed in the `public` directory.

My guess is that https://github.com/laravel/laravel/blob/8.x/config/view.php#L16 is set to load template files from the `public` directory and not the `resources` directory.
