### ISSUE TITLE
unique value not working on laravel 8 & 7

### ISSUE THREAD

**Issue by ikooshk** [proengsoft/laravel-jsvalidation#758]
### Subject of the issue
Hello dear,
 I tested the last package on laravel 7 & 8 but its problem **is not show errors** of the unique values
![3](https://user-images.githubusercontent.com/59804223/136617199-08b4c07d-0de6-403f-86a6-b83bbeaf580a.png)
(after submit and tray again write dddd and dont show errors under field)
![2](https://user-images.githubusercontent.com/59804223/136617206-e15cda7a-74ab-40b2-94eb-3a3ec969bc7d.png)
(my db)
![1](https://user-images.githubusercontent.com/59804223/136617209-685199e3-34b4-41ff-b322-60589fe434d8.png)
(error in my browser)

### Your environment
* version of this package: 7
* version of Laravel: 7 & 8

**Comment by julles** [comment]
same issue

**Comment by bramgrootjen** [comment]
Same issue.

**Comment by bramgrootjen** [comment]
Every rule that contains some logic doenst work. 

- extending a rule via serviceprovider => broken
- callback in rules => broken
- creating new Rule() in the rules set => broken

Currently working on Laravel 8 with php 8..
