### ISSUE TITLE
 Same should match, regardless of if its set or not.  Leave the required, to required.

### ISSUE THREAD

**Issue by MGParisi** [proengsoft/laravel-jsvalidation#763]
### Subject of the issue
Trying to validate passwords for Updates.  If the password is blank, it shouldn't update the field.  The validation thus should be nullable, but the nullable isn't working.  At all.

`    public function rules($update = FALSE) {
        $rules = [
            'name'        => 'required',
            'roles'       => 'required',
            'zip-codes'   => 'required|array|min:1',
            'zip-codes.*' => 'required|postal_code_with:US',

        ];

        if($update) {
            $rules['password'] = 'nullable|same:confirm-password;
            $rules['confirm-password'] = 'nullable|same:password';
            //$rules['password'] ='same:confirm-password|max:255';
            $rules['email'] = 'required|email';
        } else {
            $rules['password'] = 'required|string|same:confirm-password|max:255|min:3';
            $rules['email'] = 'required|email|unique:users,email';
        }
        return $rules;
    }`

### Your environment
* version of this package: Latest
* version of Laravel: 8

### Steps to reproduce
add the above rule, and find that same is required.  When same is not required (check docs).  Same is just same and can be same if its blank.

### Expected behaviour
Should check if they're null, and if not, check if their string and the same.  Tried a huge number of these, but nothing works.

### Actual behaviour
It keeps reporting password is enabled.  Even when Update is true.

**Comment by MGParisi** [comment]
Possible Solution:
In jsvalidation.js  Line 5574
`
        /**
         * Validate that two attributes match.
         *
         * @return {boolean}
         */
        Same: function(value, element, params) {

            var target=laravelValidation.helpers.dependentElement(
                this, element, params[0]
            );

            if (target!==undefined) {
                return String(value) === String(this.elementValue(target));
            }
            return false;
        },
`

if (target!==undefined) { shouldn't be here.  Looking into how we can test both, the target and the source for undefined.

**Comment by MGParisi** [comment]
https://laravel.com/docs/8.x/validation#rule-same
https://laravel.com/docs/8.x/validation#rule-required-if

The required_unless also seems to be incorrect.  As I leave both null, and its still asking for them to be confirmed.

**Comment by bytestream** [comment]
The PR stops using client-side validation and uses jquery validation to do server side validation before the form is submit. The main disadvantage is that you lose the instant validation on key press / changing between fields. The biggest advantage is that it uses Laravel validation server-side so you don't have to worry about broken / in-complete / inconsistent client side rules.

**Comment by MGParisi** [comment]
Ok, warning though.  The solution above is not correct.  And doesn't fix it.
