### ISSUE TITLE
Possible error on password confirmation validation

### ISSUE THREAD

**Issue by drjoju** [proengsoft/laravel-jsvalidation#77]
Hi Albert,

I think there is a problem with the password, password confirmation validation on the javascript side.
This are the rules:
        'contacto.password' => 'min:3|confirmed',
        'contacto.password_confirmation' => 'min:3'

When I submit the form, in server side, the validation it's verified correctly. But previously, in client side the "confirmed" validation is not executed, only the "min:3".
I don't see any reference to the confirmed rule in the html/javascript generated code.

Is this rule implemented yet?

Best regards

**Comment by a-komarev** [comment]
Why did you assigned this rule:

```php
'contacto.password_confirmation' => 'min:3'
```

`confirmed` rule for the `password` field should be enough.

**Comment by drjoju** [comment]
Hi a-komarev,

you are right. The validation in password confirmation is the problem. If I delete this rule, the "Equal to" rule works fine. 

Thanks!

This issue can be closed
