### ISSUE TITLE
must extends 'Illuminate\Foundation\Http\FormRequest' 

### ISSUE THREAD

**Issue by almamundinajpuri** [proengsoft/laravel-jsvalidation#8]
Hello,

I'm trying to validate login form following your FormRequest Validation example in my view
```
{!! JsValidator::formRequest('App\Http\Request\UserLoginRequest'); !!}
```
and my UserLoginRequest
```
<?php namespace App\Http\Requests;

use App\Http\Requests\Request;

class UserLoginRequest extends Request {
	public function authorize()
	{
		return true;
	}
	public function rules()
	{
		return [
			'email'     => 'required|email',
            'password'  => 'required|min:5'
		];
	}
}
```
Still I'm getting error
```
App\Http\Request\UserLoginRequest must extends 'Illuminate\Foundation\Http\FormRequest' ..
```

Could you pls give me some hint what I'm missing?
Thanks

**Comment by torrentalle** [comment]
Hello,

Can you post the code from class `App\Http\Requests\Request` to debug it?

thank's

**Comment by almamundinajpuri** [comment]
Here it is
```
<?php namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

abstract class Request extends FormRequest {

	//

}
```

**Comment by RickLancee** [comment]
You have an typo
{!! JsValidator::formRequest('App\Http\Request\UserLoginRequest'); !!}
Should be: {!! JsValidator::formRequest('App\Http\\**Requests**\\UserLoginRequest'); !!}

**Comment by almamundinajpuri** [comment]
Thanks Rick. It solved.
I copied it from this wiki page https://github.com/proengsoft/laravel-jsvalidation/wiki/FormRequest-Validation-Example
You might want to update the page

**Comment by torrentalle** [comment]
I update the page. Thank's
