### ISSUE TITLE
Problem required_with 

### ISSUE THREAD

**Issue by winiarmc** [proengsoft/laravel-jsvalidation#822]
### Subject of the issue
Problem with (required_with) validation rule.

### Your environment
* version of this package: 4.7.0
* version of Laravel: 8

### Steps to reproduce
No error message is displayed when these rules are applied. 
            'method_ids' => 'sometimes',
            'online_delivery_amount.*' => 'required_with:method_ids.*',

* (method_ids. *) is ignored.  if I enter a number e.g. method_ids.1 validation is works. 

### Expected behaviour

if the. * tag is present, the validation should work, it should display an error

### Actual behaviour
Currently, validation does not occur for this method and the use of * (ids of the array)

**Comment by bytestream** [comment]
Try using https://github.com/proengsoft/laravel-jsvalidation/pull/505 for better array validation support.

**Comment by winiarmc** [comment]
Unfortunately, this does not solve the problem.

**Comment by winiarmc** [comment]
is there any other solution?
