### ISSUE TITLE
How to change the rulesList elements names

### ISSUE THREAD

**Issue by diegomagikal** [proengsoft/laravel-jsvalidation#823]
Hi,

If I take a look into the HTML of my page, I can see the words `laravelValidation` and `laravelValidationRemote` exposed in the javascript code (at `rules` param of the `validate` function). 

There is a way to change/obfuscate them? I've been working hard to hide any mention of "Laravel" on my website, for security purposes.

**Comment by bytestream** [comment]
That would only be possible by forking the library and changing those names - https://github.com/proengsoft/laravel-jsvalidation/search?q=laravelValidation
