### ISSUE TITLE
Validation message are not working

### ISSUE THREAD

**Issue by OzanKurt** [proengsoft/laravel-jsvalidation#838]
### Subject of the issue
Validation messages are not working after moving `./resources/lang` to `./lang`

### Your environment
* version of this package: 4.7.0
* version of Laravel: v9.0.1

### Steps to reproduce
Just add any validation rule.

### Expected behaviour
It should display the correct message

### Actual behaviour
It doesn't display the correct message

**Comment by bytestream** [comment]
I don't think this should be anything to do with this package? The messages come from the Laravel validation component.
