### ISSUE TITLE
Inconsistent behavior when number field is empty or input is alphabet

### ISSUE THREAD

**Issue by TasneemAllam** [proengsoft/laravel-jsvalidation#839]
### Subject of the issue
Inconsistent behavior when number field is empty or input is alphabet, Field validation rules " required|integer|min0 ". 

### Your environment
* version of this package: 4.4
* version of Laravel: 8

### Steps to reproduce
when user enters alphabet or when field is empty
Field type is number, field validation rules " required|integer|min0 ". 

### Expected behavior
when field is empty the error message should be "Field is required"
when the user enters alphabet the error message should be "Field should be integer"

### Actual behavior
when field is empty the error message should be "Field is required"
when the user enters alphabet the error message should be "Field is required"

**Comment by bytestream** [comment]
What's the HTML for the field?

**Comment by TasneemAllam** [comment]
Its an in put field with type number.

**Comment by bytestream** [comment]
Don't think there's anything we can do here - https://jsfiddle.net/bytestream/v95pyuex/2/. Alphabetical input is not valid in `input[type=number]` and as a result the API doesn't return a value.
