### ISSUE TITLE
Hidden input validation

### ISSUE THREAD

**Issue by a-komarev** [proengsoft/laravel-jsvalidation#84]
After successful solving an issue #58 I faced another one thing:

I've got 3 input fields: `year`, `month`, `day` and on javascript I'm imploding them as hidden field `date` as `YYYY-MM-DD` to easier validate it with `date` validator on frontend.

But now because `ignore` option is removed this field is being ignored. Right now I'm thinking about hardcoded including `ignore: ''` option on some pages, but thats kinda tricky thing and it wouldn't work in case when there are hidden fields with dates exists on page together with hidden fields which should be ignored because they are created only for fallback in case of not provided values.

What is best solution for it?

**Comment by torrentalle** [comment]
`ignore` option value accepts any [jQuery selector](https://api.jquery.com/category/selectors/). The default the value is [`:hidden`](https://api.jquery.com/hidden-selector/). You can choose any selector to select wich fields to ignore.

For example, with `ignore:'.no-validate'` only *field2* will be validated
````html
<input type="hidden" name="field1" class="no-validate" />
<input type="hidden" name="field2"  />
````
