### ISSUE TITLE
Using with Laravel Translation Manager throws error

### ISSUE THREAD

**Issue by bihlmaierh** [proengsoft/laravel-jsvalidation#86]
Hello!

When I use your package with the laravel translation manager (https://github.com/vsch/laravel-translation-manager) it throws an error. This error calls

> Method Proengsoft\JsValidation\Manager::__toString() must not throw an exception

Reason for that, is that the translation manager use an own translation service provider who extends the laravel translation service provider.

Can u imagine this and correct this error, because nothing on my frontend works!

Greetings!

**Comment by torrentalle** [comment]
I take a look

**Comment by torrentalle** [comment]
Can you render your validator using *render* methond and post the error?
```html
{!! $validator->render() !!}
```

**Comment by torrentalle** [comment]
I can reproduce the error
> FatalErrorException in ClassLoader.php line 314: Maximum function nesting level of '100' reached, aborting!

This is causing the infinite recursion
```php
// return false to use the translator missing key lottery, true to always check missing keys for the user
\UserCan::macro("bypass_translations_lottery", function ()
{
    return ($user = Auth::user()) && ($user->is_admin || $user->is_editor);
});
```

If I force a return  value JsValidator works well

```php
// return false to use the translator missing key lottery, true to always check missing keys for the user
\UserCan::macro("bypass_translations_lottery", function ()
{
    return true;
});
```

```php
// return false to use the translator missing key lottery, true to always check missing keys for the user
\UserCan::macro("bypass_translations_lottery", function ()
{
    return false;
});
```
If ` Auth::user()`is called I get the error. It's strange behaivour, I'm looking into package `vsch/laravel-translation-manager` what's happening

**Comment by torrentalle** [comment]
**Xdebug is causing the error**, The default value of [xdebug.max_nesting_level](http://xdebug.org/docs/all_settings#max_nesting_level) is *100*.
I have made some tests and it's working setting **max_nesting_level** to **102** 
Increase this value to a safety value and should Work
```ini
xdebug.max_nesting_level=200
```
I'm investigating the cause of this recursion.
