### ISSUE TITLE
Issue with Laravel Vite

### ISSUE THREAD

**Issue by CodeliaNet** [proengsoft/laravel-jsvalidation#895]
### Subject of the issue
I installed this package with Laravel 9 (Vite Scaffolding ), but I can't submit form always redirect to the index page without doing anything

### Your environment
* version of this package: 4.7
* version of Laravel: 9.19

### Steps to reproduce
.- I created a Form request & added it to the store method while clicking submits redirected to the index page without storing any data, while checking the result of a request by DD(), nothing is back & redirect to the index page.

- with the normal request, I can store data

### Expected behavior
help on configuration with Laravel vite (Laravel 9 with Jetstream & livewire)

**Comment by bytestream** [comment]
Please provide an example repo to replicate
