### ISSUE TITLE
Typos in the Wiki

### ISSUE THREAD

**Issue by asugrad** [proengsoft/laravel-jsvalidation#9]
{!! JsValidator::formRequest('App\Http\Request\StoreBlogPostRequest', '#my-form'); !!}

Should be 
{!! JsValidator::formRequest('App\Http\Requests\StoreBlogPostRequest', '#my-form'); !!}

And the name of the template post_edit.balde.php should be post_edit.blade.php.

Very minor stuff. But the typo in the form request example had me chasing a non-existent error for a couple of hours.

Excellent piece of work though. Cheers.

**Comment by torrentalle** [comment]
Now typos are fixed

Thank's
