### ISSUE TITLE
Conflict with other Laravel funcionality ?

### ISSUE THREAD

**Issue by monsterdream** [proengsoft/laravel-jsvalidation#90]
Hi,
I installed that plugin and love it! Works as it should for example for contact page. But now when I try to register user without initiating your plugin I get json response:

{"email":["The email field is required."],"password":["The password field is required."]}

Insted of my old validation way just in case if JavaScript will be blocked on client computer.

So it changing a little bit and overwrite default behaviour ? Can I omit this problem somehow ?

Best regards

**Comment by torrentalle** [comment]
Hi,
The default validation behaviour only is overrided when `Request` object has a field named  `__jsvalidation`.

Can you post your `Controller` and `FormRequest` (if you ar using it)?

Sorry for late response.

**Comment by torrentalle** [comment]
In master branch this code is rewrriten to avoid Validator override
