### ISSUE TITLE
Error Placement and Radio Buttons - Correct Markup for Bootstrap?

### ISSUE THREAD

**Issue by haakym** [proengsoft/laravel-jsvalidation#92]
Apologies if this is out of scope for the package, but I'm having issues with error placement when using radio buttons with the markup as recommended in the [bootstrap docs](http://getbootstrap.com/css/#checkboxes-and-radios)

I have the following markup for radio buttons:

``` html
<div class="form-group">
    <div class="radio">
      <label>
        <input type="radio" name="has_transferred" value="1"> Yes
      </label>
    </div>
    <div class="radio">
      <label>
        <input type="radio" name="has_transferred" value="0"> No
      </label>
    </div>
</div>
```

When I submit the form causing an error in the aforementioned radio buttons, the error placement comes after the first radio button:

``` html
<div class="form-group has-error">
    <div class="radio">
      <label>
        <input type="radio" name="has_transferred" value="1" aria-describedby="has_transferred-error"> Yes
      </label>
      <span id="has_transferred-error" class="help-block error-help-block">
        The has transferred field is required when submission type is complete.
      </span>
    </div>
    <div class="radio">
      <label>
        <input type="radio" name="has_transferred" value="0"> No
      </label>
    </div>
</div>
```

Ideally it would come before the closing tag of `div.form-group`

I noticed in the docs on [Javascript Rendering](https://github.com/proengsoft/laravel-jsvalidation/wiki/Javascript-Rendering) there is the following code related to the error placement and radio buttons:

``` javascript
errorPlacement: function(error, element) {
    if (element.attr("type") == "radio") {
        error.insertAfter(element.parents('div').find('.radio-list'));
    } else {
        if(element.parent('.input-group').length) {
            error.insertAfter(element.parent());
        } else {
            error.insertAfter(element);
        }
    }
}
```

So I've tried many different way of wrapping my radio buttons within `<div class="radio-list"> ... </div>` but got the same results. I feel like I'm doing something wrong? For now the following mark up seems to work:

``` html
<div class="form-group">
    <div>
        <label for="has_transferred">Has the student been transferred to PhD*:</label>
    </div>
    <div>
        <input type="radio" name="has_transferred" value="1"> Yes
        <input type="radio" name="has_transferred" value="0"> No
    </div>
</div>
```

For which I get the following when causing a validation error:

``` html
<div class="form-group has-error">
    <div>
        <label for="has_transferred">Has the student been transferred to PhD*:</label>
    </div>
    <div>
        <input name="has_transferred" type="radio" value="1"> Yes
        <input name="has_transferred" type="radio" value="0"> No
    </div>
    <span id="has_transferred-error" class="help-block error-help-block">
        The has transferred field is required when submission type is complete.
    </span>
</div>
```

However the downside to this is that the radio button needs to be clicked to check it, whereas with the original mark up the label text or radio button can be clicked and the radio button will then be checked.

Not a huge issue, but one I believe which is resolvable. Any advice on this would be much appreciated! Thank you.

**Comment by torrentalle** [comment]
This code is changed in master branch. Try new release if it works in your case

**Comment by haakym** [comment]
Great! Thanks I will give it a shot and feedback.

**Comment by stringsanbu** [comment]
I used the latest one but still received the same error. as @haakym. This is what I'm using, almost same except it also uses a btn-group from bootstrap. Might be causing the issue, I'll try and look into it later this weekend.

    <div class="form-group btn-group">
                    <label class="btn bg-navy btn-flat btn-lg">
                        <input type="radio" name="status" id="status_empty" autocomplete="off" value="empty"> Empty
                    </label>
                    
                    <label class="btn btn-success btn-flat btn-lg">
                        <input type="radio" name="status" id="status_full" autocomplete="off" value="full"> Full
                    </label>
                </div>

**Comment by benedict-w** [comment]
Any resolution for this? experiencing it in latest version (2.5) with Bootstrap 4+

**Comment by bytestream** [comment]
@benedict-w not that I'm aware of. You'll need to play with the errorPlacement function. If you show me the HTML before and after the error is inserted then maybe I can point you in the right direction.
