### ISSUE TITLE
Add Support For Laravel 10.*

### ISSUE THREAD

**Issue by ilhamlutfi** [proengsoft/laravel-jsvalidation#926]
I want to install js-validation, but i am getting the problem like this :

  Problem 1
    - proengsoft/laravel-jsvalidation[v1.0.0, ..., v1.5.0] require illuminate/support ~5.0 -> found illuminate/support[v5.0.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation v2.0.0 requires illuminate/config 5.4.* -> found illuminate/config[v5.4.0, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation 2.1.0 requires illuminate/config 5.4.*|5.5.* -> found illuminate/config[v5.4.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation[2.2.0, ..., 2.3.0] require illuminate/config 5.4.*|5.5.*|5.6.* -> found illuminate/config[v5.4.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation[2.3.1, ..., 2.3.2] require illuminate/config 5.4.*|5.5.*|5.6.*|5.7.* -> found illuminate/config[v5.4.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation 2.4.0 requires illuminate/config 5.4.*|5.5.*|5.6.*|5.7.*|5.8.* -> found illuminate/config[v5.4.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation 2.5.0 requires illuminate/config ^5.4|^6.0 -> found illuminate/config[v5.4.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation[3.0.0, ..., 3.0.1, 4.0.0] require illuminate/config ^5.6|^6.0|^7.0 -> found illuminate/config[v5.6.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation[4.1.0, ..., v4.5.1] require illuminate/config ^5.6|^6.0|^7.0|^8.0 -> found illuminate/config[v5.6.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation[v4.6.0, ..., v4.6.1] require illuminate/config ^6.0|^7.0|^8.0 -> found illuminate/config[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - proengsoft/laravel-jsvalidation[v4.7.0, ..., v4.7.6] require illuminate/config ^6.0|^7.0|^8.0|^9.0 -> found illuminate/config[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires proengsoft/laravel-jsvalidation * -> satisfiable by proengsoft/laravel-jsvalidation[v1.0.0, ..., v1.5.0, v2.0.0, ..., 2.5.0, 3.0.0, 3.0.1, 4.0.0, ..., v4.7.6].

I have tried in laravel 9 and it is running fine, how about laravel 10.?

**Comment by bytestream** [comment]
Laravel 10 is currently unsupported. I need to check and merge https://github.com/proengsoft/laravel-jsvalidation/pull/923

**Comment by OzanKurt** [comment]
@bytestream Any ETA about this topic?

**Comment by OzanKurt** [comment]
Thank you! ❤️
