### ISSUE TITLE
Exception: Instance of Proengsoft\JsValidation\Factory, instance of Illuminate\Validation\Factory given

### ISSUE THREAD

**Issue by heikobihlmaier** [proengsoft/laravel-jsvalidation#95]
I've got the following error when I generate my ide helper file:

`Exception: Argument 1 passed to Proengsoft\JsValidation\JsValidatorFactory::__construct() must be an instance of Proengsoft\JsValidation\Factory, instance of Illuminate\Validation\Factory given, called in \vendor\proengsoft\laravel-jsvalidation\src\JsValidationServiceProvider.php on line 44 and defined`

Greetings.

**Comment by bihlmaierh** [comment]
No help here ? You Plugin is not working!

**Comment by bihlmaierh** [comment]
Push...

**Comment by jhuliano** [comment]
Did you follow this steps https://github.com/proengsoft/laravel-jsvalidation/wiki/Installation ?

If you can paste a little bit of your code you may get more/better help.

**Comment by torrentalle** [comment]
Hi @heikobihlmaier did you solved your issue? How can I help you?

**Comment by torrentalle** [comment]
This code is removed in master branch. This will disapear.....

**Comment by komol-chandra** [comment]
Argument 2 passed to Proengsoft\JsValidation\JsValidatorFactory::__construct() must be of the type array, null given, called in /home/kiri2ka/CodeWork/Laravel/New Work/hospital-management/vendor/proengsoft/laravel-jsvalidation/src/JsValidationServiceProvider.php on line 38 (View: /home/kiri2ka/CodeWork/Laravel/New Work/hospital-management/resources/views/backend/pages/account/index.blade.php)
