### ISSUE TITLE
Error when using FormRequest validation

### ISSUE THREAD

**Issue by extrakun** [proengsoft/laravel-jsvalidation#96]
Hi,

When doing a form request validation, using Laravel 5.0, I run into this error:

Argument 1 passed to Illuminate\Foundation\Http\FormRequest::failedValidation() must be an instance of Illuminate\Validation\Validator, instance of Proengsoft\JsValidation\Validator given, called in C:\Users\xxxx\Documents\xxxx\vendor\laravel\framework\src\Illuminate\Validation\ValidatesWhenResolvedTrait.php on line 26 and defined

**Comment by dennisoderwald** [comment]
+1

**Comment by torrentalle** [comment]
This bug is fixed in dev-master. Now default Laravel validator is no overwriten

**Comment by torrentalle** [comment]
Also other validation packages (like [intervention/validation](https://github.com/Intervention/validation)) are supported and validated via AJAX
