### ISSUE TITLE
Validation of image dimensions

### ISSUE THREAD

**Issue by seanthepottingshed** [proengsoft/laravel-jsvalidation#97]
I have Laravel validation of image dimensions like so:

``'file'  => 'required|image|mimes:jpg,jpeg,png,gif|image_size:>=500,>=500'``

...using **Colin Viebrock's** image-validator package:

https://github.com/cviebrock/image-validator

Is there anyway to incorporate these rules via AJAX?

**Comment by torrentalle** [comment]
The  master release has this feature. The rules provide for other packages are validated via AJAX automatically

**Comment by kyranb** [comment]
Laravel has support for this built in now. Would it be possible to support with this with the following syntax:

```php
'avatar' => 'dimensions:min_width=100,min_height=200'
```

https://laravel.com/docs/5.2/validation#rule-dimensions
