### ISSUE TITLE
Critical error with numeric min & max values

### ISSUE THREAD

**Issue by a-komarev** [proengsoft/laravel-jsvalidation#98]
If you are checking numeric values javascript is checking it for a length, not the min & max values.

For example:
```php
'age_min' => ['numeric', 'min:6', 'max:50'],
```

Will return error if you are bypassing `age_min = 30`, but will return ok if you will write `123456`.

**Comment by bastman69** [comment]
i have same kind of validation but working.
try it that way
'vessels'   =>  'required|numeric|min:1|max:1000'

**Comment by a-komarev** [comment]
But this field is not required :(

**Comment by a-komarev** [comment]
I've rechecked just copy pasted your code, but and bypassed `vessels = 0`. Javascript said it's ok. But backend blocked me.

**Comment by bastman69** [comment]
do you have your validation in the controller or in a request class?

**Comment by bastman69** [comment]
![screen shot 2015-11-20 at 6 47 44 pm](https://cloud.githubusercontent.com/assets/3406020/11305820/37aa3ac4-8fb7-11e5-878a-835b8fa7dc83.png)

**Comment by bastman69** [comment]
opps you are write. not working for me either. i will check more and revert if i find a solution.

**Comment by a-komarev** [comment]
You've asked a good question. I'm performing validations using FormRequests only.

**Comment by a-komarev** [comment]
Thanks for fixes, will check in couple of days.

**Comment by a-komarev** [comment]
After first check it's looks like partially working for me. It's understanding that it's numeric values, but still throwing an error that value should be between 14 and 75, when my value is 15.
I've tried validators `between` and `min` + `max`.

**Comment by a-komarev** [comment]
Solved an issue:

```sh
php artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider" --force
```

**Comment by torrentalle** [comment]
Update your `composer.json` to run publish on composer update

```php
{
    "require": {
        "laravel/framework": "5.1.*",
        ...
        "proengsoft/laravel-jsvalidation": "~1.1"
    },
    ...
    "scripts": {
        "post-update-cmd": [
            ....
            "php artisan vendor:publish --provider=\"Proengsoft\\JsValidation\\JsValidationServiceProvider\" --tag=public --force"
        ],
    },
}
```
You can follow the  [Configuration Guide](https://github.com/proengsoft/laravel-jsvalidation/wiki/Configuration)
