### ISSUE TITLE
Validation on Update on uqnique rule

### ISSUE THREAD

**Issue by bastman69** [proengsoft/laravel-jsvalidation#99]
UpdateCustomerRequest
====================
<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class UpdateCustomerRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $id = $this->request->get("id");
        
        return [
            'name'      =>  'required|min:5|unique:customers,name,'. $id,
            'contact'   =>  'required|unique:customers,contact,'. $id,
            'email'     =>  'email|unique:customers,email,'. $id,
            'address'   =>  'required',
            'phone'     =>  'required',
            'vessels'   =>  'required|numeric|min:1|max:1000'
        ];
    }
}
============================================================
Without JsValidation Working. 
With JsValidation lets say in email field says "The email has been taken".
Maybe this functionality not working <<unique:customers,email,'. $id,>>

**Comment by AEK-BKF** [comment]
Same issue with me, please did you find the solution ?

**Comment by bastman69** [comment]
unfortunately not yet.

**Comment by AEK-BKF** [comment]
@bastman69  please I set the issue in stackoverflow site, could you help me if you saw this error ? :
http://stackoverflow.com/questions/34442196/laravel5-1-jsvalidation-unique-rule-issue
Thanks.

**Comment by torrentalle** [comment]
Hi,
This is not supported yet. In ajax request only the validation field is sent.
I'm rewriting the code to allow this feature.

**Comment by torrentalle** [comment]
duplicated #88

**Comment by torrentalle** [comment]
fixed in release **v1.3.1**

**Comment by leoneljdias** [comment]
In release v1.3.1 this problem to "Forcing A Unique Rule To Ignore A Given ID" just occurred to me.
I can't this rule: "'email' => 'unique:users,email_address,'.$user->id"
