### ISSUE TITLE
Why is it suggested to ignore vendor directories?

### ISSUE THREAD

**Issue by MansourM** [proengsoft/laravel-jsvalidation#992]
Hi
Great work on the library, I was following the steps in wiki and i reached this line where it is suggested to add these to git ignore
```
/resources/views/vendor/
/public/vendor/
```
I was wondering what benefits this gives us? because as far as i understand these are only generated once with `publish` command and stay the same afterwards.
also if we ignore these files, we need to add
`
$ php artisan vendor:publish --provider="Proengsoft\JsValidation\JsValidationServiceProvider"
`
to the production steps.
we will also need every body who works on the project to run this line.
is that the best-practice/intended-behaviour or im missing something.

Thank you

**Comment by MansourM** [comment]
nvm, :D after re reading and paying more attention i saw that is is stated that ou need to copy the files using the mix.copy, i think since it was mix my mind kinda auto ignored those lines ;D
ill do the vite equivalent and add them here

**Comment by MansourM** [comment]
Here is how to do it in vite (Laravel 9/10+), maybe add this to wiki/docs?
1. install static copy plugin for vite:
```
npm i -D vite-plugin-static-copy
```
2. change your `vite.config.js`
```js
...
import {viteStaticCopy} from 'vite-plugin-static-copy'
...

export default defineConfig({
    build: {
        ...
    },
    plugins: [
        laravel(
            ...
        ),
        viteStaticCopy({
            targets: [
                {
                    src: 'vendor/proengsoft/laravel-jsvalidation/resources/views',
                    dest: __dirname + '/resources/views/vendor/jsvalidation'
                },
                {
                    src: 'vendor/proengsoft/laravel-jsvalidation/public',
                    dest: __dirname + '/public/vendor/jsvalidation'
                },
            ]
        }),

    ],
});
```
Still why not just add these files to git?

**Comment by bytestream** [comment]
> Still why not just add these files to git?

It just adds bloats to your git repository, they're not files that need to be tracked. If you want to track them you can.
